### ISSUE TITLE
Not able to test Glitch setup| Help Needed Urgent!!

### ISSUE THREAD

**Issue by abhishek-bafna** [OmerTu/GoogleHomeKodi#100]
Hi Everyone,

I need your help please!!

I have followed all steps as mentioned on Omertu. But I am not able to get my Glitch test working. I am kinda struck on very beginning of this.
IMp: My kodi is connected via LAN/Ethernet wire but share same internet connection as my Google Home Mini which is on WIFI. Would that be a problem?
Steps followed:
1) I have created username, password and port: 8090 in kodi.
2) Went to system information in kodi and got my ip address from there.
3) Configured Port Forwarding on my router (New to this)
4) Set external IP address : 0.0.0.0 , port: 8090, Internal IP Address : 192.168.x.x Port: 8090, TCP
5) Created Glitch project and imported omertu project. Changed env setting to my kodi username, password, port, and KODI_IP_ADRESS via my laptop (connected on same wifi as google home mini)
6) Click on Show live.
7) Glitch open another browser with my project URL :https://abhishek-kodi.glitch.me/
    ---> The functionality you would like to test: /koditestconnection
    -----> Click on Button : Test Connection to Kodi

8) Have created all steps for IFTTT.
9) Failed : Gateway timed out.

Please help what i am doing wrong, I know your expert advice would definitely help me.

Awaiting your response.

Thanks,
Abhishek

**Comment by p0psicles** [comment]
You entered the external or internal ip adres in glitch env config for your kodi?

**Comment by abhishek-bafna** [comment]
Hi..

I entered internal ip address in glitch env. Settings.

On 28 Dec 2017 14:43, "p0ps" <notifications@github.com> wrote:

You entered the external or internal ip adres in glitch env config for your
kodi?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OmerTu/GoogleHomeKodi/issues/100#issuecomment-354355139>,
or mute the thread

**Comment by abhishek-bafna** [comment]
@p0psicles @OmerTu 

After adding external IP to env. settings in Glitch configuration. Test was successful. 
but when i am trying to hit 
http://YOUR_INTERNAL_KODI_IP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}
Its working

but external ip , its doesnt work. It keeps asking for username and password and says Connection is not private in popup dialog box.
http://YOUR_EXTERNAL_IP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}

Next thing I tried:
I asked : Hey google, kodi play movie ****, i saw Applet got failed in IFTTT. Please let me know.

**Comment by OmerTu** [comment]
Follow the instructions in [https://github.com/OmerTu/GoogleHomeKodi#troubleshooting](https://github.com/OmerTu/GoogleHomeKodi#troubleshooting) and compare your settings to the examples [here](https://github.com/OmerTu/GoogleHomeKodi/tree/master/examples)
When it asks for username and password you should use the ones you configured in Kodi (step A)4 in the guide)

**Comment by rkumarblr** [comment]
I have the same issue, whatever I do I am unable to get across to Kodi from the external ip.
It gives the 504 timeout message. Port forwarding has been setup correctly on my time capsule 
The http://YOUR_EXTERNAL_IP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}} 
times out 

How to check and fix the timeout issue for external IP?

**Comment by keydon** [comment]
Are you sure your external ip did not change in the meantime and is identical to the one you see here: http://whatismyip.com/ ? 
For dynamic IPs its necessary to setup some kind of dynDNS service.

**Comment by abhishek-bafna** [comment]
@keydon @p0psicles @OmerTu 

My external IP is not changed.
I am highly confused with one thing now. In GLITCH which IP_ADDRESS should be mentioned external or internal? Please help me asap.

**Comment by rkumarblr** [comment]
/koditestconnection was successful but when i use the /playpause command it timeout on the gateway. The glitch log is what i find below. 
There seems to be a second issue when I issues the command ok google kodi pause which is what I have defined in IFTTT and look up the Activity, I see the message Applet skipped.

I double checked the IFTTT definition with the sample and all is fine. 
I think I have a gateway time out as well as an IFTTT issue, Please help 

Loaded config from .env
9:17 PM
🍏👣 Your app is listening on port 3000
9:17 PM
9 minutes ago
Authentication succeeded
9:18 PM
Command sent = {"jsonrpc":"2.0","id":1,"method":"GUI.ShowNotification","params":{"title":"Initiated by IFTTT","message":"Test Successful!"}}
9:18 PM
Authentication succeeded
9:18 PM
Play/Pause request received
9:18 PM
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.PlayPause","params":{"playerid":0}}
9:18 PM
request failed
9:20 PM
route:  /koditestconnection
9:20 PM
query:  {}
9:20 PM
error:  { FetchError: request to http://*.*.*.*:8080/jsonrpc failed, reason: connect ETIMEDOUT *.*.*.*:8080
9:20 PM
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
9:20 PM
    at emitOne (events.js:96:13)
9:20 PM
    at ClientRequest.emit (events.js:188:7)
9:20 PM
    at Socket.socketErrorListener (_http_client.js:309:9)
9:20 PM
    at emitOne (events.js:96:13)
9:20 PM
    at Socket.emit (events.js:188:7)
9:20 PM
    at emitErrorNT (net.js:1277:8)
9:20 PM
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
9:20 PM
    at process._tickCallback (internal/process/next_tick.js:104:9)
9:20 PM
  name: 'FetchError',
9:20 PM
  message: 'request to http://*.*.*.*:8080/jsonrpc failed, reason: connect ETIMEDOUT *.*.*.*:8080',
9:20 PM
  type: 'system',
9:20 PM
  errno: 'ETIMEDOUT',
9:20 PM
  code: 'ETIMEDOUT' }
9:20 PM
body:  { token: 'mytoken' }
9:20 PM
request failed
9:21 PM
route:  /playpause
9:21 PM
query:  {}
9:21 PM
error:  { FetchError: request to http://*.*.*.*:8080/jsonrpc failed, reason: connect ETIMEDOUT *.*.*.*:8080
9:21 PM
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
9:21 PM
    at emitOne (events.js:96:13)
9:21 PM
    at ClientRequest.emit (events.js:188:7)
9:21 PM
    at Socket.socketErrorListener (_http_client.js:309:9)
9:21 PM
    at emitOne (events.js:96:13)
9:21 PM
    at Socket.emit (events.js:188:7)
9:21 PM
    at emitErrorNT (net.js:1277:8)
9:21 PM
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
9:21 PM
    at process._tickCallback (internal/process/next_tick.js:104:9)
9:21 PM
  name: 'FetchError',
9:21 PM
  message: 'request to http://*.*.*.*:8080/jsonrpc failed, reason: connect ETIMEDOUT *.*.*.*:8080',
9:21 PM
  type: 'system',
9:21 PM
  errno: 'ETIMEDOUT',
9:21 PM
  code: 'ETIMEDOUT' }
9:21 PM
body:  { token: 'mytoken' }
9:21 PM
Authentication succeeded
9:25 PM
Play/Pause request received
9:25 PM
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.PlayPause","params":{"playerid":0}}

**Comment by rkumarblr** [comment]
I have masked the external ip in the log above had put starts but looks like it got totally masked and yes I have kodi listening at 8080 and have port forwarded 8080

**Comment by keydon** [comment]
> /koditestconnection was successful
according to your provided log it was not successful at all, it also timed out.
You did not see a test message appearing on your kodi tv while testing the connection, did you?

> In GLITCH which IP_ADDRESS should be mentioned external or internal?
External! please dont mask out the whole IP. At least provide the first two sections. This enables out to see if its an actual valid external ip.
Everything outside your own four walls can only reach you through your external ip.

> as well as an IFTTT issue
lets not get ahead of ourselfs, first lets make the communication between kodi and glitch work.

**Comment by abhishek-bafna** [comment]
@keydon Thanks for your fast response. 
I did some change in settings, now both my internal and external ip calls are made.
Change made: updated port from 8090 to 8080 and chnage password which had special characters. I am not sure which of this work but i am happy that it worked.

**IFTTT Issue:** When i say "hey google, kodi play movie Frozen".. 
Google says : Playing movie Frozen on kodi (which i setup) but i dont see any movie played. I was expecting it to play from exodus but nothing played and my IFTTT applet states "Applet failed".
I want to know will it play movie from local or will search (where?) and play?
Please guide further.

**Comment by rkumarblr** [comment]
Thanks for looking it up. Glitch is set for external IP, I unmasked the first two octets. 
I need to get to a dynamic dns but for now, the external ip has not changed, so eliminating that possibility 
You are correct the /koditestconnection also time-out 

❤️🐈 Your app is listening on port 3000
10:12 PM
2 minutes ago
Authentication succeeded
10:15 PM
Command sent = {"jsonrpc":"2.0","id":1,"method":"GUI.ShowNotification","params":{"title":"Initiated by IFTTT","message":"Test Successful!"}}
10:15 PM
Authentication succeeded
10:17 PM
Stop request received
10:17 PM
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.Stop","params":{"playerid":0}}
10:17 PM
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.Stop","params":{"playerid":1}}
10:17 PM
request failed
10:17 PM
route:  /koditestconnection
10:17 PM
query:  {}
10:17 PM
error:  { FetchError: request to http://183.82.*.*:8080/jsonrpc failed, reason: connect ETIMEDOUT 183.82.*.*:8080
10:17 PM
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
10:17 PM
    at emitOne (events.js:96:13)
10:17 PM
    at ClientRequest.emit (events.js:188:7)
10:17 PM
    at Socket.socketErrorListener (_http_client.js:309:9)
10:17 PM
    at emitOne (events.js:96:13)
10:17 PM
    at Socket.emit (events.js:188:7)
10:17 PM
    at emitErrorNT (net.js:1277:8)
10:17 PM
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
10:17 PM
    at process._tickCallback (internal/process/next_tick.js:104:9)
10:17 PM
  name: 'FetchError',
10:17 PM
  message: 'request to http://183.82.*.*:8080/jsonrpc failed, reason: connect ETIMEDOUT 183.82.*.*:8080',
10:17 PM
  type: 'system',
10:17 PM
  errno: 'ETIMEDOUT',
10:17 PM
  code: 'ETIMEDOUT' }
10:17 PM
body:  { token: 'mytoken' }

My glitch .env 

KODI_PROTOCOL="http"
KODI_IP="183.82.*.*"
KODI_PORT="8080"
KODI_USER="kodi"
KODI_PASSWORD="********"
AUTH_TOKEN="mytoken"

**Comment by rkumarblr** [comment]
My port forward setting on my time capsule 
<img width="416" alt="screen shot 2017-12-29 at 22 25 32" src="https://user-images.githubusercontent.com/8880946/34442303-43eb852e-ece7-11e7-9036-8bd95e9cfd97.png">

**Comment by rkumarblr** [comment]
my private ip I have set is 10.0.1.X which is mapped to the Mac address and so is always the same for my Shield where I run my Kodi

**Comment by abhishek-bafna** [comment]
@keydon Thanks for your fast response.
@p0psicles @OmerTu @keydon 
I did some change in settings, now both my internal and external ip calls are made.
Change made: updated port from 8090 to 8080 and chnage password which had special characters. I am not sure which of this work but i am happy that it worked.

**IFTTT Issue:** When i say "hey google, kodi play movie Frozen"..
Google says : Playing movie Frozen on kodi (which i setup) but i dont see any movie played. I was expecting it to play from exodus but nothing played and my **IFTTT applet states "Applet failed".**
I want to know will it play movie from local or will search (where?) and play?
Please guide further.

**Comment by Stefan300381** [comment]
I thought it's limited to local videos (or network shares) but no support for AddOns like Exodus. Or did I miss something?

**Comment by abhishek-bafna** [comment]
@p0psicles @OmerTu @keydon 
1 quick question, Is this limited to only local videos and shows? Can i run movies via addon like exodus or someother? I am sorry to ask but I dont see that information anywhere.

**Comment by p0psicles** [comment]
Only with videos that have been added to your library.

**Comment by keydon** [comment]
@abhishek-bafna @Strefan300381 thats correct, we currently dont support addons, especially the illigal ones. i consider this issue closed.

@rkumarblr time capsule has not built in modem, correct? So how is it connected to the internet? maybe you need another port forwarded. but in any case, please reopen another issue, i consider this one closed,
