### ISSUE TITLE
[REQUEST] Next/Previous song and party mode

### ISSUE THREAD

**Issue by talondnb** [OmerTu/GoogleHomeKodi#101]
Apologies if I've missed it, but I use Kodi as my primary music player in my living room. It would be good to be able to skip to the next/previous song, also to enable music party mode (randomise songs from library).

Thanks!

**Comment by keydon** [comment]
should be straight forward to add that, we will look into it.

**Comment by keydon** [comment]
i just stumbled upon 
```
/playercontrol?q=next
```
there is also `previous`, but it does not work as desired for now.

As for the party-mode, a pull-request is pending (8d90bc9)

**Comment by talondnb** [comment]
Great, thank you!
