### ISSUE TITLE
Difficulty getting Glitch to open Kodi connection

### ISSUE THREAD

**Issue by jackdholmes** [OmerTu/GoogleHomeKodi#103]
Hi All,

I've been working on this for a couple of days now to no avail so I'm hoping somebody will be able to help. I am a novice when it comes to this stuff so please bear with me.

I have set the webserver side up on Kodi correctly. I can now access the functionality through my browser using http://192.168.1.xx:8080.

I believe the difficulty is when trying to port forward (something I have never attempted before). From reading through other threads this may be down to my internet connection being modem > router > computer.

I have accessed my router and have set up port forwarding to the IP above using port 8080. When I use canyouseeme.org it says SUCCESS: I can see your service. This suggests to me that I have done this part correctly.

However, when using Show Live on Glitch and entering my access token I only get the result 504 Gateway Time-out. Also when trying to access http://84.93.1xx.xxx:8080 I get asked for my login details, I put in the same username and password as the kodi ones and then it just hangs until saying this site cannot be reached.

Despite this I persevered with the IFTTT applet which I got working but when I select to play a movie on my local network, google home confirms it has understood but nothing plays.

I really have tried to solve this alone but I have run out of ideas. I plugged my computer directly into my modem and ran ipconfig but no ip address on there worked either when putting it into Glitch.

I am sure it is glaringly obvious but please can someone let me know what I'm doing wrong?

**Comment by keydon** [comment]
> When I use canyouseeme.org it says SUCCESS: I can see your service. This suggests to me that I have done this part correctly.

handy litte service, did not know this one. thanks for the hint.
But not sure how "deep" it checks the forwarded port. So i am not sure if this helps.
Could you post your port forwarding configuration?

**Comment by jackdholmes** [comment]
Port forwarding:
![image](https://user-images.githubusercontent.com/34924202/34453172-d69ebbcc-ed44-11e7-82d7-5c72624d41ca.png)
I have blanked out part of my ip but this is the same as the ip that is on my amazon fire.

Glitch env:
![env](https://user-images.githubusercontent.com/34924202/34453197-91acc4e0-ed45-11e7-9862-f9655dc98b67.JPG)
I have blanked out part of my ip but this is the same as what ip I have when I type whats my ip into Google. I have also removed my password but this is the same as the password I used in Kodi.

**Comment by keydon** [comment]
looks all good to me, mmmh

**Comment by jackdholmes** [comment]
Nothing to do with my modem/router setup?

**Comment by coulddobetters** [comment]
I'm also having the same issue. I can type in playmovie?q=Aladdin on the test part of my glitch and it all works fine and opens the movie. I have put the same info into the web app but nothing happens ports all look fine to.

**Comment by keydon** [comment]
@coulddobetters 
> I'm also having the same issue. I can type in playmovie?q=Aladdin on the test part of my glitch and it all works fine and opens the movie. I have put the same info into the web app but nothing happens ports all look fine to.

what do you mean with _"web app"_ ? glitch is the web app

**Comment by coulddobetters** [comment]
Sorry no I have created an app on IFTTT to link it to my google home but when I say the command it my google home it reply's as should but dose not open the film. If I type in the  playmovie?q=Aladdin into the glitch test it will play that movie so it would suggest my ports ect work but the IFTTT is not linking to the command for some reason.

**Comment by coulddobetters** [comment]
forget that I have managed to find out what it was I had not put the Body right I had just  put in my password not {"token":"password"} so it now all works amazing thanks. Is there a way to make this work for Covenant or open traket?

**Comment by keydon** [comment]
>Is there a way to make this work for Covenant or open traket?

highly unlikely

**Comment by coulddobetters** [comment]
I think I have found a way to get it to play my  Covenant collection by downloading my trakt to my nas via covenant and then setting it as my main tv and movie folder so when I say play 8 mile it then starts the film using covenant so that is good enough for me for now.

**Comment by keydon** [comment]
closed due to inactivity.

**Comment by vlamikov** [comment]
Any solution to the Glitch time-out?
