### ISSUE TITLE
Working with MySQL/MariaDB or Local DB Only?

### ISSUE THREAD

**Issue by gbaldridge** [OmerTu/GoogleHomeKodi#104]
Ive set everything up. However I cannot initate the play of anything. I can command Kodi to Pause and Resume so I know those function work and all of the connectivity is there. However it is not Initiating the play of anything.

"I looked for XXXX on Kodi but it either isnt availble or cant be played right now.

**Comment by keydon** [comment]
The phrase you have chosen is the problem. Your request never reaches our app nor your kodi.
Bad phrase:
> Play XXXX on Kodi

This wont work, since commands starting with "Play" is reserved for google and its partners.
We recommend using a prefix like "Kodi" 

Good phrase:
> Kodi play XXXX

**Comment by gbaldridge** [comment]
My mistake that is the phrase I was using. Ill test again just to triple check.

**Comment by gbaldridge** [comment]
Yeah same error. I have a feeling its due to the DB being on my NAS being accessed by the entire house and not stored locally?

**Comment by keydon** [comment]
It should make no difference if the local sqlite-db or an external MySQL DB is used. We dont access the Datebase direcly, only through the JSON-RPC-API which should support both types.

And the spoken error the google home strongly suggests that it still triggers the "wrong" play phrase. You can see that in IFTTT, that your applet did not run.

**Comment by gbaldridge** [comment]
Well. Im dumb, It works just fine.....

Kodi play MOVIE Shaun of the Dead.......works perfect.

I was leaving out MOVIE.

We can remove or delete this. Apologies and great work. Thank you.

**Comment by keydon** [comment]
no problem, glad it works for you now :)
