### ISSUE TITLE
local node.js server playing wrong episodes/series

### ISSUE THREAD

**Issue by robwrightcomputer** [OmerTu/GoogleHomeKodi#106]
Have a weird problem where I ask google to play a tv show and it plays a completely different show
example:
ok google.  Kodi play stargate atlantis season 1 episode 1.
Get a response saying ok playing stargate atlantis season 1 episode 1
It actually plays a ransom episode of f is for family.  Any clue as to why this would be?

Oddly enough the kore kodi remote would do the same thing when I went to play a tv show directly from the app instead of scrolling to the show through kodi's menu on the tv.  Yatse is the only app that actually plays tv shows correctly for me when I choose one from within the app.  Is this maybe a problem with kodi itself?  Just trying to figure this out.  Any help would be appreciated.  Thanks.

**Comment by keydon** [comment]
can you provide some logs of the node app?

**Comment by BlindfoldNL** [comment]
I've been having some strange lookups as well. Don't want to hijack this thread, so if my issue is something different I'll gladly open a new one. Here are my logs for an example of a strange lookup. Try to search for War for the Planet of the Apes, but it ended up with Storks. Second try it cutoff my search and god War 4 and it actually found it correctly, so lucky me.
 Don't know if the fact that it includes the word "of" in a lot of searches that messes up the lookup.

But mostly it finds the things well, but sometimes things like things happen, so still very happy with this. Best solution I've found so far.

Log info:

Movie request received to resume "of War for the Planet of the Apes"
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies"}
best fuzzy match for 'of War for the Planet of the Apes' is: { label: 'Storks', movieid: 241 }
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.Open","params":{"item":{"movieid":241},"options":{"resume":true}}}
Authentication succeeded
Stop request received
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.Stop","params":{"playerid":0}}
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.Stop","params":{"playerid":1}}
Authentication succeeded
Movie request received to resume "War 4"
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies"}
best fuzzy match for 'War 4' is: { label: 'War for the Planet of the Apes', movieid: 261 }
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.Open","params":{"item":{"movieid":261},"options":{"resume":true}}}
Authentication succeeded

**Comment by BlindfoldNL** [comment]
One thing I have noticed is that Storks was actually the previous movie I had played. unfortunately that wasn't in my log, but I'll try and test a bit more to produce some logging, because I have a suspicion it has something to do with somehow caching the previous request. I've had the issue before where I tried to play a movie and it just played the last movie I had played with voice search. Hasn't happened with TV Series so far.

**Comment by keydon** [comment]
@BlindfoldNL your example is not a caching issue. i can reproduce your results on http://fusejs.io/ itself. thats the library we use for fuzzy-matching. when playing with the fuzzy-settings i can get the desired result (tokenize = true) but not sure if this change would break other cases. maybe we need some kind of test-suite to avoid regressions.

**Comment by BlindfoldNL** [comment]
ok thanks for the clarification!

**Comment by keydon** [comment]
I did a change a couple commits back which cuts off the leading "of", which seems to throw off the algorythm the most. Not much more I can do for now, this issue is not severe enough to lookout for other libraries. For now I consider this resolved.
