### ISSUE TITLE
Resume tv episode?

### ISSUE THREAD

**Issue by BlindfoldNL** [OmerTu/GoogleHomeKodi#107]
Hi. I have a question. Is it possible to resume watching a the latest TV episode of a show? I sometimes stop watching, but asking play latest episode of.... starts from the beginnen and I'm either overlooking the command for resume in the instructions, or it's not there.

**Comment by keydon** [comment]
yeah it is missing but can easily be added

**Comment by cammerton** [comment]
Any tips on how to add this? I'm trying to get my head around the helper.js file but my less than mediocre coding skills are 20 years behind me now! I would love to tinker though.

This is such an awesome project. Much kudos and thanks!

**Comment by keydon** [comment]
cool, i gladly help you to get started.
Yes, the helper.js is awful huge. I have plan on breaking it up, but not sure when i get around to it.

So basicly all you would have to do is to split up the method `kodiPlayNextUnwatchedEpisode` and extract out the part, which executes the `Player.Open` command. This extracted but would have to differ between the regualar-play-request and the resume-request.

We already support resuming movies, so you can check how its done there. Compare `kodiPlayMovie` with `kodiResumeMovie`

**Comment by BlindfoldNL** [comment]
ok, so reading this. Am I correct that I can copy the part from 

``
const kodiPlayNextUnwatchedEpisode until 
return Kodi.Player.Open(paramPlayerOpen); // eslint-disable-line new-cap
        });
};
``
And call it kodiResumeNextUnwatchedEpisode and use that for the new command (Since I usually want to resume the latest unwatched episode I was watching.
But I'm a bit confused on where to put the 
``
options:

 {
            resume: true
        } 
``
part. Because in the resume movie it's used right after the player.open command, right after the item, but in the unwatched episode part, the item is used before the player.open command, so should I put the resume part after the item, or after the player.open in this case (or am I completely wrong in everything I'm thinking in the first place). Glad to wait for someone to do it, but don't want to be a leech only, so if I can do stuff myself, I'm happy to learn.

**Comment by keydon** [comment]
please dont copy the whole method `kodiPlayNextUnwatchedEpisode`.
rename it to `kodiGetNextUnwatchedEpisode` and make it return the episode it found instead of directly playing it.
that way both, the old `kodiPlayTvshow` and your new `kodiResumeTvshow` share some common code. Only the Play-Command itself will differ.

**Comment by BlindfoldNL** [comment]
Sorry to maybe waste your time, but that's already going above my understanding. 
I think I understand what the idea is, but I'm missing something obviously.

I now have kodiplaytvshow in the original file:
```
exports.kodiPlayTvshow = (request, response) => { // eslint-disable-line no-unused-vars
    tryActivateTv(request, response);
    let param = {
        tvshowTitle: request.query.q.trim().toLowerCase()
    };

    console.log(`TV Show request received to play "${param.tvshowTitle}"`);

    return kodiFindTvShow(request, response, param)
        .then((data) => kodiPlayNextUnwatchedEpisode(request, response, data));
};
``` 

So if I understand you correctly I would need to crate another one of these calles kodiResumeTvshow. 

But If I rename my 'kodiPlayNextUnwatchedEpisode' then what will the `kodiPlayTvshow` refer to in the last part? 
Apart from the fact I don't even know how to change the play to return in the first place, so I'm afraid I'll wait and compare, since I don't want to waste anyones time with noobish questions.

**Comment by keydon** [comment]
well if you want to persue a career in software engineering we could see how this plays out. Otherwise i could just make the changes, it is indeed quicker than implemented than explained. 20min tops.

`kodiPlayTvshow` AND `kodiResumeTvshow` will refer to the same renamed method, but they both will do different things with the result of that method.

**Comment by BlindfoldNL** [comment]
I'm afraid I'll never get beyond tinkering with other people's work. If you have the time to do the changes, I'd be grateful and certainly check it out and reverse engineer (and probably go: AAAH, that's what he meant).

**Comment by Blaisun** [comment]
I didn't see the need for two separate functions between initial play and resume as the resume will start from the beginning if it has not been played before. What i did is just add the resume to the existing play function and it has been working well enough for me.

Comment out the following lines in the Helper.js file in the kodiPlayNextUnwatchedEpisode function:

```
// let paramPlayerOpen = {
           //     item: {
           //         episodeid: episdoeToPlay.episodeid
           //     }
           // };
          //  return Kodi.Player.Open(paramPlayerOpen); // eslint-disable-line new-cap
```
and add in the following lines:
```
 //  edit to auto resume tvshows 
      return Kodi.Player.Open({ // eslint-disable-line new-cap
            item: {
                episodeid: episdoeToPlay.episodeid
            },
            options: {
                resume: true
            }
                });   

```

**Comment by keydon** [comment]
you are right, usually ppl want to resume their not fully watched episodes. even if the episode was not partially watched, the resume option should do no harm.
my solution was based on the assumption that i would want to choose if i want to resume or start from the beginneing

**Comment by keydon** [comment]
i still went with the extra route, enables the user to choose as he wishes. pull-request pending

**Comment by BlindfoldNL** [comment]
Thanks a lot for your efforts. Very much appreciated!
