### ISSUE TITLE
controlling search feature within addons?

### ISSUE THREAD

**Issue by DJdavid1441** [OmerTu/GoogleHomeKodi#109]
any chance of some help on controlling addons within kodi

**Comment by p0psicles** [comment]
Your going to add api routes for different addons in kodi. And you want us to help you with that? Or you want us to implement those api endpoint in Google kodi home?

**Comment by DJdavid1441** [comment]
i have looked every where to try and find examples of how to add api routes but haven't been successful

**Comment by p0psicles** [comment]
You should get in contact with kodi devs.
