### ISSUE TITLE
"I dont see any chromocasts or cast enabled tvs"

### ISSUE THREAD

**Issue by 01** [OmerTu/GoogleHomeKodi#11]
Not sure if I did something wrong during set up. But very interested in giving this a try and possibly adding more functionality. But Google Home seems to keep assuming I am trying to cast something

**Comment by OmerTu** [comment]
You need to make sure the triggering phrase you set in IFTTT isn't being used by Google Home.
For example, you can't choose something like: "Hey Google, play [movie name] on TV"
Try: "Kodi agent play video $" or anything like that

**Comment by 01** [comment]
I figured as much I was using recipe Kodi play movie $, ill try something more specific

**Comment by 01** [comment]
Are you sure "Play movie" isnt reserved? I just tried recipe "Kodi microeconomics dog play movie $ " still not having it.  By using a recipe that didnt involve Play movie seems to work. Curious if you were able to get it to work with the recipe Kodi play movie $

**Comment by OmerTu** [comment]
:) It's possible that 'play movie' is now reserved.
I'm using a differed phrase.  I changed the instructions to recommend on "kodi play $" instead.

**Comment by 01** [comment]
Ya seems so i changed it and have it all working. Thanks!
