### ISSUE TITLE
Play Music by Genre

### ISSUE THREAD

**Issue by cammerton** [OmerTu/GoogleHomeKodi#112]
This is a feature request (unless I've missed something). It'd be great to be able to ask Kodi to play either a random selection of tracks of a certain genre or if that's too tricky a random album of a certain genre. I'm wondering if the existing random film of a specific genre function could serve as the base.

Thanks again for your awesome work!

**Comment by keydon** [comment]
Yes this could be implemented.

Basically its taking `kodiPlayRandomMovie` and replacing `Movie` with `Album` or `Songs`. Well a very little more.

**Comment by cammerton** [comment]
Ok cool. I'll try to copy and edit the random movie function although I'm a bit lost with some of the syntax. I may well jag it!

**Comment by cammerton** [comment]
Just having a look at this now. I guess trying to playing songs of a certain genre means creating a random playlist. The random movie function only plays one thing. Hopefully I can at least hack that function to play a random album of a specific genre anyway. Any tips greatly appreciated!

**Comment by keydon** [comment]
nah, was quite easy to implement, pullrequest is pending.
