### ISSUE TITLE
Multiple Kodi Instance via Glitch

### ISSUE THREAD

**Issue by cammerton** [OmerTu/GoogleHomeKodi#113]
Just wondering if it is possible to set up a second Glitch server in order to control another instance of Kodi? If so what specific changes (apart from the glitch url) would I need to make in the IFTTT calls?

No linux here so can't run a local server unfortunately.

Thanks for any help!

**Comment by keydon** [comment]
well i guess all you have to do is to use different phrases. so maybe instead of just _kodi_ before all commands you could use _living room kodi ..._ for one instance and something else for the other.

**Comment by keydon** [comment]
ah and btw, node.js should also run on windows. i havent tested it though.

**Comment by cammerton** [comment]
Thanks so much for the feedback Keydon. Will try the 2nd Glitch server model first and report back. Will also look into node.js on Windows. Thanks again.

**Comment by cammerton** [comment]
Just tested multiple Glitch servers for mutliple Kodi instances and it works perfectly. Too easy! Now installing node.js on my windows machine to see if I can get a local server going. Bit unsure how to translate the Linux instructions for Windows but will pass on any tips if I make it through,

**Comment by cammerton** [comment]
No luck with node.js on my Windows machine. Have node.js installed and the repo cloned with an edited config file but opening server.js does nothing (it's associated with node.js). Any others got this working on Windows? 

Also just in regards to the config file - I am assuming all ip addresses have to be external (same as with the Glitch setup). I understand this local setup must be faster but I don't get how it is safer given that the web server still needs to be turned on in Kodi? Forgive my ignorance :)

**Comment by cammerton** [comment]
So sorry to bug you on this. but I think I'm close to getting the Windows. node.js server option working. Server now seems to be successfully running (had to install npm dependencies as per a previous post I saw). 

So do I use the internal IP address of each Kodi instance in the config file? And then what is the full server URL for the IFTTT applets? Obviously it has to start with my external IP address. it how does it know to look for the node.js server?

Thanks heaps for your help.

**Comment by p0psicles** [comment]
Please take a look at the documentation. It's explained.

**Comment by keydon** [comment]
> had to install npm dependencies

yeah sorry, we will add that to the readme soon.

> do I use the internal IP address of each Kodi instance in the config file?

yes thats right

> And then what is the full server URL for the IFTTT applets?

well, when with your first setup your kodi was reachable with `http://1.2.3.4:8080` then your node js server will be reachable like so `http://1.2.3.4:8099` (or whatever port you did configure).
The port is beeing announced on startup of your nodejs-server.

> how does it know to look for the node.js server?

thats what to port is for

> Please take a look at the documentation. It's explained.

there is not mention of ports in the local-setup documentation. So i guess there is a lot of room for improvement ;O

**Comment by cammerton** [comment]
Keydon, you're an absolute legend. Thanks so much for your explanation and help here. All makes sense and will have a play later tonight and see if I can get it working locallly. Should all be golden now!

Popsicles, I did read and re-read all the documentation, but as Keydon mentioned the port stuff and some other basic stuff was not mentioned. My lack of knowledge obviously hampered me as well :)

**Comment by cammerton** [comment]
Apologies for another question or two but I've managed to get the local node.js server working on Windows and controlling my primary Kodi instance - awesome! I'm just setting up the separate instances now. There's some disparity between the comments in the .dist config file and the readme, where the .dist file says that the instance id can be used as the main keyword when talking to Google, ie. "Ok Google, bedroom pause". The readme says that the Kodi keyword still needs to be used and then the id gets called at the end of the sentence. 

I was hoping there might be some way around having to make unique IFTTT applets for each instance with the local node.js setup but I guess not? Anyway it's easy enough to copy and remake via the IFTTT maker platform (why they don;t offer that interface/functionality with the stock standard IFTTT I will never know).

Thanks again for any help.

**Comment by keydon** [comment]
The problem is the limitation of IFTTT. They allow only one Text-Parameter.

For simple commands without parameters you can control both instances with one IFTTT-Applet .
```
URL: /playpause
{
 "token": "secret",
 "kodiid": "{{TextField}}"
}
```

But as soon as you need a Text-Parameter for the command itself, like in `kodi play an episode of the simpsons`. you are one parameter short. In this case you need a 2nd applet.

```
URL: playtvshow?q={{TextField#1}}
{
 "token": "secret",
 "kodiid": "{{TextField#2}}"
}
```

**Comment by cammerton** [comment]
Thanks for that Keydon. I see the issue. All good on making separate applets. Unfortunately though I can't seem to get my node.js setup to work with a second instance. I've tried both approaches I mentioned in the post above but neither seem to work. Is there any special magic to the IFTTT "what do you want to say" field and the body field beyond the stuff stated above?

**Comment by keydon** [comment]
i dont follow.

If you are using the two-applet approach you dont need magic at all. You are the magic!
```
PHRASE: bedroom play an episode of the simpsons
URL: /playtvshow?q={{TextField}}
BODY:
{
 "token": "secret",
 "kodiid": "myBedroomId"
}

**Comment by cammerton** [comment]
Haha, I am the magic indeed 😀 is you have a look at my 2nd last post I mentioned that the readme states that the Kodi keyword still needs to be used?

Alse in your example in you last post,

"kodiid": "myBedroomId"

Do I need the "my" prefix and "Id" suffix around "bedroom", assuming I've used "bedroom" as an I'd in the config file?

I realise these are dumb questions to folks that code but I'm clearly not in that group 😗

**Comment by cammerton** [comment]
Apologies for typos, on phone.

**Comment by cammerton** [comment]
I've tried every variation I can think of now and I just can't get IFTTT/node.js to access a 2nd instance of kodi. The same applet works fine when I remove the kodiid line from the body field and just point to the main instance of Kodi but when I add it in to access another instance Google tells me it doesn't understand and I get nothing logged via node.js. Weirdness!

**Comment by keydon** [comment]
> The readme says that the Kodi keyword still needs to be used and then the id gets called at the end of the sentence.

i dont know what you are referring to. please quote the part of the readme.

> Do I need the "my" prefix and "Id" suffix around "bedroom", assuming I've used "bedroom" as an I'd in the config file?

of course not, just use "bedroom" in your case. it is case sensitive. use the exact same id in the body and in the config.

**Comment by cammerton** [comment]
Here's the bit from the readme

`Example scan library If you normally would use a sentence like: "Hey Google, kodi scan library" --> Will start a full library scan. For running this command on your second kodi instance, you could copy the applet, and change it to: "Hey Google, kodi scan library in the bedroom".`

> of course not, just use "bedroom" in your case. it is case sensitive. use the exact same id in the body and in the config.

I figured as much but thought I best ask. Yes I've been using the same case for the id. Just can;t see why it won't work. All other aspects of the node.js setup are working. Obviously it's something dumb I'm doing somewhere!

**Comment by cammerton** [comment]
And now it works! I wish I knew what changed or why it's now working but I'll shutup and replicate the IFTTT applets and enjoy it. And just in case anyone else is confused by the readme instructions, the example that Keydon mentioned above (and is mirrored in the original config file) is correct - don't use the kodi keyword for other instances.

Now to work out how to start the server.js app with Windows. Bat file?

**Comment by cammerton** [comment]
For those using node.js on Windows, I've managed to install the server.js app as a Windows Service using this:
https://github.com/coreybutler/node-windows

The only problem is that the service starts and then stops a few seconds later (after the script has run I guess). When using Powershell to run the server.js manually it stays running as long as the Powershell window is open which I guess keeps the script alive. Just not sure how to keep it alive as a service. Any Window heads out there?

**Comment by keydon** [comment]
the script should not stop running. it should block, since its listening for incoming request indefinetly. most likely it does no longer find the configuration file and therefore fails starting up.
Adding `process.chdir(__dirname);` to line no 5 of the server.js might fix that.

**Comment by cammerton** [comment]
Thanks Keydon, will try that. Have managed to use a .bat file with "pause" at the end to keep the CMD window open (and the script alive). I made a shortcut to the .bat file, set the properties to minimised and put in my Windows startup folder. Working!

Thanks for all your help. Really do appreciate it.

**Comment by cammerton** [comment]
My node.js setup seems to have mysteriously stopped working and can't figure out why. So I decided to go back to the multiple glitch server approach but now this doesn't seem to working as it did before. Can I clarify something in regards to the multiple glitch server approach - if I use a unique keyword for each Kodi instance, do I need to alter any of the glitch server files? eg. "Lounge pause". I have both my instances setup up like this and they are not working ("lounge" and "theatre") but if I alter one to the default "kodi", it works.

Any tips? 

Thanks!

**Comment by keydon** [comment]
make sure your IFTTT-Applets know only one approach (glitch or selfhosted), i would not mix them (even though it is possible if obeying the following rule).
Most important rule: Exactly **one unique phrase** per command and per instance.
The code of your two glitch instances do not need any modification, configuring the environment appropiately is everything.

**Comment by keydon** [comment]
maybe check if your previously configured port forwardings did change after switching the approach.

**Comment by cammerton** [comment]
Thanks for the feedback Keydon. I'm pretty sure I've done everything you've mentioned above correctly. The weird thing is that I had the local node.js setup working fine across two instances and then for some reason stopped. In trying to resurrect things, one thing I have noticed is that if I use the keyword for the instance as a secondary word in the phrase, such as "kodi pause on lounge" (with "lounge" being the instance id). I'm a bit confused as to exactly how the phrase works and hooks into the script.

**Comment by messiah109501** [comment]
I've managed to get this working on a Windows box as a service using NSSM. 

http://nssm.cc/download

Create a new service using this, point the path to the node.exe file and as the argument, point it to the server.js file in your GoogleHomeKodi folder.

**Comment by keydon** [comment]
> I'm a bit confused as to exactly how the phrase works and hooks into the script.

In this case the phrase does not hook into the script at all. its just there to distinguish what applet to run.

> kodi pause on lounge

I would avoid the "play on X" phrases, since they are also used by google and its chromecast.

**Comment by keydon** [comment]
closed due to inactivity.
