### ISSUE TITLE
ifttt does not reach my external IP

### ISSUE THREAD

**Issue by algouye** [OmerTu/GoogleHomeKodi#115]
I have setup everything, using the local node js running.
as if I am doing it manually connected directly to the node js server, I can enter playpause and the token set and it works fine however, when I setup the ifttt with as URL my external IP+port/playpause it does not work.

I have setup the ifttt as below
![image](https://user-images.githubusercontent.com/34473479/34483665-e8ca210e-efb7-11e7-8fbb-2af7cb67bedc.png)

Port forwarding is well setup to my router, I have doubled checked it and works fine hitting my external IP with the port.

Again, any though and guidance would be welcomed.
Al.

**Comment by keydon** [comment]
does the node.js server log something to the console when triggering the ifttt-applet?
or does the ifttt-request not reach your node-server? if the later, something is wrong with your router-configuration.

**Comment by keydon** [comment]
if your isp shares IPv4-Adresses with multiple customers, you will not be able to host any service locally. https://en.wikipedia.org/wiki/Carrier-grade_NAT

**Comment by algouye** [comment]
thanks. 
The ifttt applet end up as skipped in red.
As when I setup the kodi instructions directly as part of the URL, having another router's rule to allow access of course, the ifttt works fine.

![image](https://user-images.githubusercontent.com/34473479/34484243-5a191146-efbb-11e7-87ea-277cd7436189.png)



the console does not log anything.. it seems that for some reason the ifttt is not executing/accepting the request..

**Comment by algouye** [comment]
Thanks all for your help, I have found that somehow the box which runs the node js had the wrong gateway... reset it and its now working.. thanks again.

**Comment by algouye** [comment]
Thanks all for your help, I have found that somehow the box which runs the node js had the wrong gateway... reset it and its now working.. thanks again.
