### ISSUE TITLE
"Action Skipped" in IFTTT

### ISSUE THREAD

**Issue by itm1960** [OmerTu/GoogleHomeKodi#120]
I'm trying to get this up and running with Kodi 17.6 running on Ubuntu 17.04. I've tested the Kodi web interface successfully by pausing a video using an HTTP request from an external IP address. However whenever I trigger my first IFTTT action (to play a song) I get the right response message from IFTTT but it doesn't execute and reports "Action Skipped" in the IFTTT activity log. 
My IFTTT applet is set up as follows:
What do you want to say "Kodi play song $"
What do you want the Assistant to say in response?  "OK playing $"
URL: https://myglitchname-port.glitch.me/playsong?q={{TextField}}
Method: POST
Content Type: application/json
Body: {"token":"mytokenpassword"}

Can anyone advise on how to troubleshoot this?

**Comment by keydon** [comment]
1. Open ` https://myglitchname-port.glitch.me/` in your browser
2. Put in your token
3. click _test_
-> is that successful?

If yes do the following:
1. Open ` https://myglitchname-port.glitch.me/` in your browser
2. Put in your token
3. as action put `/playsong?q=Funkytown`
3. click _test_
-> is that successful?

**Comment by itm1960** [comment]
If I put https://myglitchname-port.glitch.me/ I get the standartd index.html page ("This is a Kodi Control Thiingamajig. Go away.") but don't get prompted for my token

**Comment by keydon** [comment]
you seem to run an old version. please update to the most recent one as described in the readme, as the debugging and error handling improved greatly.

**Comment by itm1960** [comment]
Ah OK I now have the latest version and it seems to be working fine - thanks for the help!

**Comment by keydon** [comment]
great :)
