### ISSUE TITLE
TV Turn on function

### ISSUE THREAD

**Issue by reddevilmeuk** [OmerTu/GoogleHomeKodi#123]
hi, one question has anyone got the 'turn TV on' function to work..?

the firestick can turn on the TV by pressing any button but I've tested both ways in the read me section but can't get it to work...
#
thanks

**Comment by keydon** [comment]
not sure if kodi is capable of utilzing the firestick-built-in-cec-adapter, which is necessary for this feature to work.
What do you see in kodi at this location:
> System -> Settings -> Input -> Peripherals

**Comment by reddevilmeuk** [comment]
Nothing :(

**Comment by keydon** [comment]
then there is nothing we can do.
maybe checkout the official kodi frorums for cec-support on the firestick
