### ISSUE TITLE
403 Forbidden Error with Glitch App, but Kodi's Chorus2 web interface works over WAN

### ISSUE THREAD

**Issue by rtrman** [OmerTu/GoogleHomeKodi#124]
I'm running Kodi 17 via LibreElec 8 "Remix" as a VM on an UnRAID system.

I have configured GoogleHomeKodi as specified in the instructions. I have also enabled the web interface, which I can access from outside my network via dynamic DNS and use to control Kodi successfully, indicating the port is forwarded correctly, and Kodi web interface is also configured correctly.

However I continue to receive an error 403 when testing the Glitch app, and would be grateful for some support.

Thanks

**Comment by keydon** [comment]
can you please prvide the logs of the glitch app after an test-attempt?

**Comment by rtrman** [comment]
Of course. 

`Authentication succeeded
3:32 PM

Command sent = {"jsonrpc":"2.0","id":1,"method":"GUI.ShowNotification","params":{"title":"Initiated by IFTTT","message":"Test Successful!"}}
3:32 PM

request failed
3:32 PM

route:  /koditestconnection
3:32 PM

query:  {}
3:32 PM

error:  { FetchError: request to http://mydynamicip.duckdns.org:8181/jsonrpc failed, reason: connect ECONNREFUSED 12:34:56:78:8181
3:32 PM

    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
3:32 PM

    at emitOne (events.js:96:13)
3:32 PM

    at ClientRequest.emit (events.js:188:7)
3:32 PM

    at Socket.socketErrorListener (_http_client.js:309:9)
3:32 PM

    at emitOne (events.js:96:13)
3:32 PM

    at Socket.emit (events.js:188:7)
3:32 PM

    at emitErrorNT (net.js:1277:8)
3:32 PM

    at _combinedTickCallback (internal/process/next_tick.js:80:11)
3:32 PM

    at process._tickCallback (internal/process/next_tick.js:104:9)
3:32 PM

  name: 'FetchError',
3:32 PM

  message: 'request to http://mydynamicip.duckdns.org:8181/jsonrpc failed, reason: connect ECONNREFUSED 12:34:56:78:8181',
3:32 PM

  type: 'system',
3:32 PM

  errno: 'ECONNREFUSED',
3:32 PM

  code: 'ECONNREFUSED' }
3:32 PM

body:  { token: '1234' }`

(Sensitive information obviously edited)

**Comment by keydon** [comment]
and the kodi webservice works fine from outside of your network when accessing it via `http://mydynamicip.duckdns.org:8181`? Like you tested it from lets say a phone with disabled wifi?
because the error suggests otherwise.

**Comment by rtrman** [comment]
This is bizarre...
It hadn't been working all day, despite rebooting the VM, and even router just to check the port forwarding had stuck.
I couldn't access via webUI from WAN any more, so I rebooted the VM one more time, and voila, everything works! 
Not sure what did it, but thanks anyway!
