### ISSUE TITLE
not possible to use GoogleHomeKodi with Kodi 18 Leia

### ISSUE THREAD

**Issue by Elmine74** [OmerTu/GoogleHomeKodi#126]
A major change for Leia onwards is that JSON-RPC no longer accepts many of the commands via HTTP. This is a measure taken for improved security.

Do you have another way to write the commands to use GoogleHOmeKodi With Leia 18 ?

Thank you

**Comment by keydon** [comment]
what is your source an this?

**Comment by p0psicles** [comment]
I don't believe they drop an existing interface. Not without depreciating for a min of 2 releases.

**Comment by Elmine74** [comment]
https://forum.kodi.tv/showthread.php?tid=324598

**Comment by Elmine74** [comment]
Or is it only a problem with my installation....

**Comment by keydon** [comment]
as far as i can see, nothing was removed, only restricted for HTTP GET.
Since we only use HTTP POST, we should not be affected at all.

What is your problem with your installation? get some logs in here :d

**Comment by Elmine74** [comment]
I received the same message that on the linked page:
Code:
{
"jsonrpc": "2.0",
"error": {
"code": -32099,
"message": "Bad client permission."
},
"id": 1
}

**Comment by keydon** [comment]
when did you receive this message?
if you are referring to the troubleshot section, well that one indeed uses HTTP GET and therefore needs to be rewritten.
but the app itself only uses HTTP POST and should work. I will get myself a Leia Instance to play around sometime soon.

**Comment by Elmine74** [comment]
I’m going to try it again. Thank you

**Comment by dd02lygp** [comment]
hi guys,
this is so awesome. Has anyone managed to get kodi to play series or movies from the addon's using voice?

**Comment by keydon** [comment]
@dd02lygp currently no addons supported.

closed due to inactivity of the original author

**Comment by dd02lygp** [comment]
Hi,
I found this on another site. I am not too clueed up, but doesnt this reference the addon?

http://server:8080/jsonrpc?request={
"jsonrpc":"2.0","method":"Addons.ExecuteAddon","pa rams":{
"wait":false,"addonid":"plugin.video.addon","param s":{
"action":"tvshows","url":"trending"
}
},"id":2
}

**Comment by keydon** [comment]
@dd02lygp i meant not supported by us. and please dont hijack threads that have nothing to do with your issue.

**Comment by dd02lygp** [comment]
Dude!! Dont be a prick!! Rather guide newbies like me elsewhere instead of just telling us off.
Ffs!! 
Cheers smuck

**Comment by keydon** [comment]
@dd02lygp 
lol, where on earth was i beeing a prick? please tell me that in pm, i really want to know,
all i did is stating the facts that we currently dont support addons and that u hijacked an issue completly irrelevant to your request. And i would direct you to another project if i knew one, but i dont, sorry!

i am going to delete the latest comments now, for the following reasons:
1. off-topic (aka hijacking a thread)
2. completly inappropriate choice of words
