### ISSUE TITLE
[feature request]  open 'app' via word or hotword  location 

### ISSUE THREAD

**Issue by SamJongenelen** [OmerTu/GoogleHomeKodi#128]
Would it be possible to open a custom addon or kodi location via voice command?

**Comment by keydon** [comment]
what do you mean with 
> kodi location


Something like [this](http://kodi.wiki/view/Opening_Windows_and_Dialogs#AddonBrowser)? If yes, then its coming with pull request #125

**Comment by SamJongenelen** [comment]
Yeah I think I mean an URI yes. Thanks for #125!
