### ISSUE TITLE
Can't connect without glitch... :(

### ISSUE THREAD

**Issue by doscas** [OmerTu/GoogleHomeKodi#129]
Hi all,

First of all, congrats to OmerTu! This is a great project.

I tried to follow all the instructions, step by step, but I could not get this to work.
I'm trying not to use glitch, but I am afraid I could not be totally clear on the instructions for that.
I've tried a bunch of different things, but something is wrong.

I went trough the troubleshooting and I can pause/resume my Kodi both from internally and externally.
I have Kodi running on a RPi3 with OSMC.

I am not sure about the token / authToken we see in the IFTTT and on /etc/systemd/system/kodiassistant.service. Is put them matching (sorry, I am a newbie when it comes to this), but I'm not sure...
Please let me know if there's something different that I should do that is not on the instructions for my case, if OSMC is not compatible with this or what is that you need so you can help me.

Thank you so, so much in advance.

**Comment by keydon** [comment]
**_First:_ 
Please also read the improved and in part rewirtten new README in the [development branch](https://github.com/OmerTu/GoogleHomeKodi/blob/develop/README.md)**

After reading the improved instructions::
> Can't connect without glitch  

What does that even mean? Whats the error? What do da Logs say? What does The console say? What doesnt work?

> I can pause/resume my Kodi both from internally and externally
 Finally some usefull information, so now we at least know you Kodi webservice is running.

> I am not sure about the token / authToken

What dont you understand about the token? Just ask. I cannot look into your mind.

> /etc/systemd/system/kodiassistant.service

That is the least important part of the whole README. Just ignore it if you dont know what to do with it.

> OSMC is not compatible

Everything with a full Kodi on it is supported.

**Comment by keydon** [comment]
closed due to inactivity.
