### ISSUE TITLE
Kodi correctly set up but not able to control via glitch

### ISSUE THREAD

**Issue by LukasPrj** [OmerTu/GoogleHomeKodi#13]
Hi all,

I have kodi correctly set up and have successfully controled it by sending json data to both the internal and external IP. However, when I try to integrate via Google home, IFTTT and Glitch, it does not do anything.

When curling with the (example) command:
curl -H "Content-Type: application/json" -X POST -d '{"token":"sample_toke"}' https://green-ball.glitch.me/playpause 
I get the following error:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /playpause</pre>
</body>
</html>

I followed the tutorial to the letter so not sure what is going wrong.

Any ideas?

Kr,

Lukas

**Comment by LukasPrj** [comment]
Update, when looking into the application logs, I find the following error:
connect EHOSTUNREACH xxx.xxx.xxx.xxx
However, when I provide the exact same host into the following URL:
http://xxx.xxx.xxx.xxx:8080/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22id%22:1,%22method%22:%22Player.playpause%22,%22params%22:{%22playerid%22:1}} it works absolutely fine

**Comment by keydon** [comment]
1. Are you sure you used your external IP-address? 
2. Is the port forwarding enabled (external port opens and directed to your internal IP) That's a router configuration

**Comment by LukasPrj** [comment]
I am 100% sure :). I literally copied the application log entry (containing the URL that was targetted and the request that was made). I pasted it in my browser and it works fine ...

Yes, port forwarding is enabled. I have done this many times for custom java apps :)

I am currently trying a different approach by installing the project on a raspberry pi and setting up everything on that machine. Will keep you posted.

Thanks for any suggestions!

**Comment by LukasPrj** [comment]
Latest: Again I am able to target my raspberry Pi using port forwarding but currently having a new error:

Error: native promise missing, set Fetch.Promise to your favorite alternative
    at new Fetch (/home/osmc/GoogleHomeKodi/node_modules/node-fetch/index.js:41:9)
    at Fetch (/home/osmc/GoogleHomeKodi/node_modules/node-fetch/index.js:37:10)
    at Kodi.sendHTTP (/home/osmc/GoogleHomeKodi/kodi-connection/api.js:30:12)
    at Kodi.send (/home/osmc/GoogleHomeKodi/kodi-connection/api.js:53:17)
    at Object.result.(anonymous function) [as PlayPause] (/home/osmc/GoogleHomeKodi/kodi-connection/api.js:9:22)
    at kodiPlayPause (/home/osmc/GoogleHomeKodi/server.js:66:15)
    at IncomingMessage.<anonymous> (/home/osmc/GoogleHomeKodi/server.js:49:11)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

**Comment by LukasPrj** [comment]
Got it to work in both ways:
1) Via glitch: my router did not have an option remote access enabled. When enabling this, it worked. However, this is not something I want to enable.
2) Via RPI: upgrade nodejs and works perfectly.

Thanks a lot!

Kind regards,

Lukas

**Comment by manofsteel2017** [comment]
> Update,

 when looking into the application logs, I find the following error:
connect EHOSTUNREACH xxx.xxx.xxx.xxx
However, when I provide the exact same host into the following URL:
http://xxx.xxx.xxx.xxx:8080/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22id%22:1,%22method%22:%22Player.playpause%22,%22params%22:{%22playerid%22:1}} it works absolutely finE

> 

mine worked with this format too but doesn't work if i past it through iftt
smh

**Comment by keydon** [comment]
the original issue seems to be resolved -> closing this issue

@manofsteel2017 if you still have a problem, please open your own issue.
