### ISSUE TITLE
[feature request] turn off tv via json-cec

### ISSUE THREAD

**Issue by llonca13** [OmerTu/GoogleHomeKodi#130]
Could you please add this feature?

Its supported in home assistant via json-cc. I think the command is "standby" (tu torn off tv via cec, kodi stays on)

https://home-assistant.io/components/media_player.kodi/

**Comment by keydon** [comment]
This feature is already added to the develop branch and it will be merged to master soon.

**Comment by OmerTu** [comment]
#122
