### ISSUE TITLE
Kodi with Google Home Mini on Local network

### ISSUE THREAD

**Issue by rkumarblr** [OmerTu/GoogleHomeKodi#133]
I am unable to port forward due to the ISP tunneling etc.
Can I not use Google Home Mini to talk to Google Assistant package in nodejs and then to kodi all in the local network, Without having to use IFTTT  and port forward etc.

If its possible ? I know that mean coding which I am fine to build, but is it even possible ?
Can nodejs and required package be deployed on the shield directly, if not I can have the nodejs server running on a Unix box or Mac Book on the local  network and redirect to the kodi server on the shield 

Please advise.

**Comment by keydon** [comment]
well there are two possible solutions i see right now.

1. build your [own hackable google home](https://aiyprojects.withgoogle.com/voice).
   this enables you to react programatically on that device to your spoken words in your network (only the speech recogniction is outside of your network, which is fine)

2. using a [vpn service](https://www.reddit.com/r/VPNTorrents/comments/3oar5m/list_of_vpns_that_allow_p2p_and_port_forwarding/) (or build one yourself too) which allows port forwarding into your netwrok through the vpn.

good luck.

**Comment by rkumarblr** [comment]
Yes I found the later which is a service from ngrok that helped me tunnel back into my network.
GH -> IFTTT->ngrok-> My server running the node.js-> Kodi 
 
The intent is to run kodi on a macbook pro, run node.js as well on the same mac. In doing so be able to use GH to control kodi (which I achieved through the VPN mentioned above). It would be nice if I can extend the capability to control youtube and google music as well which the GH natively does on Nvidia shield. There is a google assistant package for node.js and I suppose youtube and google play music expose API. Any pointers on how I could go about that would be much appreciated

If you do have any reference to the point 1 on hackable google home, please do let me know, since I do not even know where to start on that one.

**Comment by keydon** [comment]
ad 1.
https://aiyprojects.withgoogle.com/voice
https://developers.google.com/assistant/sdk/reference/library/python/
https://github.com/google/aiyprojects-raspbian

for controlling youtube, that already works. basic search & play
google music currently not supported

**Comment by rkumarblr** [comment]
Thanks for the tips and response much appreciated
