### ISSUE TITLE
Missing Access Token 

### ISSUE THREAD

**Issue by danmiller84** [OmerTu/GoogleHomeKodi#134]
Brilliant app and very excited to get it to work, but I have hit a brick wall. 

This is the info I have filled out on the .env file.

![img_1667](https://user-images.githubusercontent.com/35435091/35008813-b9ce9c10-faf5-11e7-9ee0-3b950ab9d709.JPG)

Here is the IFTTT stuff I've entered 

![img_1666](https://user-images.githubusercontent.com/35435091/35008911-004e39fc-faf6-11e7-88a7-e2941978f9d6.PNG)

The "test connection" always comes back as Test Success and I can access the kodi online. But asking Google home to put a film on, she comes back with what she's meant too but nothing happens. 

Putting playmovie?q=stargate into web browser brings up the following; 

{ "message": "401 - Missing access token", "name": "ResponseException", "status": 401, "statusText": "401 - Missing access token" }

Thanks in advance for the help

**Comment by keydon** [comment]
The problem is your apple phone, for some stupid reason it uses weired quotes.
We need the standard ones, so maybe retype them on a pc.

Bad:
```
{“token”:”connectplus”}
```

Good:
```
{"token":"connectplus"}
```

**Comment by keydon** [comment]
ah no, i was too, fast.

you simple cannt test the play command in the browser address bar. just use the test-functionality in the startpage of the app.

**Comment by keydon** [comment]
what do the logs say, when triggered by ifttt?

**Comment by danmiller84** [comment]
the log says

> Authentication succeeded
8:09 PM Command sent = {"jsonrpc":"2.0","id":1,"method":"GUI.ShowNotification","params":{"title":"Initiated by IFTTT","message":"Test Successful!"}}
8:09 PM Test Successful! { id: 1, jsonrpc: '2.0', result: 'OK' } 

and just waiting for IFTTT to update

**Comment by danmiller84** [comment]
and the test of /playmovie?q=stargate says "ok" - i think its working - fingers crossed for Google Home - thanks v much!

**Comment by danmiller84** [comment]
Well it's working, sort of. The film is playing on the kodi app on my tablet but it is not casting it

**Comment by danmiller84** [comment]
There is an error log on IFTTT = "Unable to make web request. Your server returned a 400"

**Comment by keydon** [comment]
> The film is playing on the kodi app on my tablet but it is not casting it

what?

i only care about glitch logs :)

**Comment by keydon** [comment]
closed due to inactivity
