### ISSUE TITLE
google home says "sorry, I can't play from kodi yet" when i tell it to play

### ISSUE THREAD

**Issue by paulie99** [OmerTu/GoogleHomeKodi#136]
If anyone can help, it would be greatly appreciated.

I have set everything up as the instructions show. test connection is successful, IFTTT set up, not showing any issues. I can connect to my kodi through my external ip address with port 8080 via the web. But when I give the command, google home says:

"sorry, I can't play from kodi yet" 

I'm in Canada (I don't know if that makes any difference). Has anyone else had this issue?

Thanks in advance!

**Comment by kingofslackerz** [comment]
Are you sure you are saying your commands starting with "Kodi play...."?  The only time I receive that response from mine is when I start a command with "Play" instead of "Kodi play".

**Comment by paulie99** [comment]
Thanks for the response. I did make that mistake a couple of times, but I went through again and made sure I said "OK Google, kodi play X". Still get the sorry can't play from kodi yet.

**Comment by paulie99** [comment]
![glitch test connection](https://user-images.githubusercontent.com/35583142/35151063-d6f39d8a-fcea-11e7-8bdd-c057b3d6bec8.PNG)
![env config](https://user-images.githubusercontent.com/35583142/35151081-e5f1564c-fcea-11e7-898c-814630bd9526.PNG)
![ifttt 1](https://user-images.githubusercontent.com/35583142/35151092-ecf08f3a-fcea-11e7-8e94-d4d482c112c8.PNG)
![ifttt 2](https://user-images.githubusercontent.com/35583142/35151097-f173f218-fcea-11e7-8f3d-c05a170de547.PNG)
![ifttt 3](https://user-images.githubusercontent.com/35583142/35151099-f3b20470-fcea-11e7-99aa-e5285dd49adb.PNG)

Here are the screenshots if that helps anyone. Hopefully I'm just missing something small. Cheers!

**Comment by keydon** [comment]
> sorry, I can't play from kodi yet

this indicates, that google home did not run the IFTTT-Applet. Either it did not unserstand you or your IFTTT is not correctly connected to the google account of your google home.

try it from the assistant app of your phone by typing out the phrase instead of saying it out loud.

**Comment by dasilvafamily** [comment]
keydon, that was exactly the issue. Fixed up the accounts, all running smooth now. Thanks very much!

**Comment by tchirou** [comment]
I had this setup working for months and it was great. 
And since 2 days ago, I have the exact same problem. I can do everything else through ifttt and google home, except using kodi so it is not a problem of account

**Comment by keydon** [comment]
@tchirou plz open up an own issue if your problem persists. provide the exact response of google home when you do so. you seem to have a different problem

**Comment by tchirou** [comment]
Actually, I find the bug
I am French, and a few months back, google assistant in French didn’t
recognize “Kodi” but “Cody” so I made all my ifttt applets with “Cody”.
Turns out since a few days, the French google assistant recognizes “kodi”
only when I speak so I just had to replace “Cody” by “Kodi” and everything
works again

Hope it can helps other non English users.

Thanks

Le 20 janv. 2018 à 18:30, Lukas <notifications@github.com> a écrit :

@tchirou <https://github.com/tchirou> plz open up an own issue if your
problem persists. provide the exact response of google home when you do so.
you seem to have a different problem

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OmerTu/GoogleHomeKodi/issues/136#issuecomment-359187783>,
or mute the thread

**Comment by emko** [comment]
@dasilvafamily how did you fix this? i can connect to my IP using my phones internet connection and i see the IFTTT test page and i can trigger playpause etc but when i try with google assistance its always saying Sorry, I can't play from Kodi yet yes i did reconnect to wifi. I even fully rest my Google home by holding mute and the top button for 20 seconds and reconfigured it still same result. I added a google assistance applet in IFTTT find my phone and this works fine? i just dont get why Kodi won't

**Comment by keydon** [comment]
@emko did you try typing out your phrase in the google assistant app on your phone instead of speaking it out load?

**Comment by emko** [comment]
@keydon it was a issue with google or IFTTT they said its fixed now and its working fine for me now

**Comment by keydon** [comment]
great :)
