### ISSUE TITLE
Unable to resume movie

### ISSUE THREAD

**Issue by sg1102** [OmerTu/GoogleHomeKodi#139]
Hi
So everything works perfectly (my limited testing so far) and thank you for that.. except .. when i ask Kodi to play a movie, it plays the movie fine. but then if I stop the movie and ask google home to play the same movie again, Kodi thinks for a second and does nothing. I don't see any errors. 
I tried changing the default Kodi selection to Play/Resume .. didn't help

Any suggestions?

**Comment by keydon** [comment]
well, provide us with some logs.
kodi logs and glitch logs (if you chose the glitch-hosting, otherwise the console output of your node server)
