### ISSUE TITLE
Kodi correctly set up but not able to control via glitch with everything already set up

### ISSUE THREAD

**Issue by manofsteel2017** [OmerTu/GoogleHomeKodi#14]
Hello everyone, I am back again 
seems like i'd never get this to work
Everything is set up correctly 
I can even test my externalip:8080 and able to log in to the kodi web remote 
but when google home says Ok playing xxx command. nothing happened
I texted play command, pause, stop. none of them worked. 
i'm not sure what to do. I hope someone can guide me through this 
I've been trying for a week now lol 
I think maybe my glitch server is not working properly? i do got the "hello world " when i click on liVE
ANY HEP WOULD BE GREATLY APPRECIATED 
![capture](https://user-images.githubusercontent.com/30217010/28493939-5542743a-6eee-11e7-8f64-a1e3bd38a338.PNG)

**Comment by OmerTu** [comment]
Go to your glitch server, and click on **Logs** (on the left)
Then, try to ask Google to pause kodi and attach the logs from Glitch here (remember to replace  sensitive info with xxx)

**Comment by manofsteel2017** [comment]
https://tested-rugby.glitch.me/

that's my server it doesn't show anything only hello world. i don't see any logs ??
oh f my life lol

**Comment by OmerTu** [comment]
Go to:
[(https://glitch.com/edit/#!/tested-rugby)]
and click Logs on the left side 
<img width="960" alt="logs glitch" src="https://user-images.githubusercontent.com/7314947/28496820-af758a9c-6f42-11e7-8ed9-458857225507.png">

Then, it should write stuff to the log while you try to run the past command.
If it doesn't write anything to the logs.. you have some problem with your IFTTT settings

**Comment by manofsteel2017** [comment]
.env: line 11: unexpected EOF while looking for matching `"'
10:27 AM
Jump to
.env: line 14: syntax error: unexpected end of file
10:27 AM
4 minutes ago
Jump to
.env: line 11: unexpected EOF while looking for matching `"'
10:27 AM
Jump to
.env: line 14: syntax error: unexpected end of file
10:27 AM
🚶🍜 Your app is listening on port 3000
10:27 AM
3 minutes ago
Request token = xxxxxxxx
10:28 AM
Authentication succeeded
10:28 AM
Movie request received to play "John Wick"
10:28 AM
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies"}
10:28 AM
Request token =xxxxx2017
10:29 AM
Authentication succeeded
10:29 AM
Movie request received to play "John Waite"
10:29 AM
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies"}
10:29 AM
{ FetchError: request to http://xxxxxxxxxx8080/jsonrpc failed, reason: connect ETIMEDOUT xxxxxxxxxx:8080
10:30 AM
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
10:30 AM
    at emitOne (events.js:96:13)
10:30 AM
    at ClientRequest.emit (events.js:188:7)
10:30 AM
    at Socket.socketErrorListener (_http_client.js:309:9)
10:30 AM
    at emitOne (events.js:96:13)
10:30 AM
    at Socket.emit (events.js:188:7)
10:30 AM
    at emitErrorNT (net.js:1277:8)
10:30 AM
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
10:30 AM
    at process._tickCallback (internal/process/next_tick.js:104:9)
10:30 AM
  name: 'FetchError',
10:30 AM
  message: 'request to http://xxxxxxxx:8080/jsonrpc failed, reason: connect ETIMEDOUT xxxxxxxxx:8080',
10:30 AM
  type: 'system',
10:30 AM
  errno: 'ETIMEDOUT',
10:30 AM
  code: 'ETIMEDOUT' }
10:30 AM

**Comment by cardomon** [comment]
Help! as a Glitch newbie (and a JS newbie and nearly everything else) like Man of steel, I’m getting stuck trying to get my project to make RPC calls to my Kodi server.

I’m trying to find the Album ID for a Fleet Foxes album. The RPC call works from a browser window (with internal AND external IP addresses), but when I use the same structure in Glitch I get this log entry:
<<Log starts>>
Command sent = {“jsonrpc”:“2.0”,“id”:1,“method”:“AudioLibrary.GetAlbums”,“params”:{“limits”:{“start”:0,“end”:50},“properties”:[“playcount”,“artist”,“genre”,“rating”,“thumbnail”,“year”,“mood”,“style”],“filter”:{“field”:“album”,“operator”:“is”,“value”:“Fleet Foxes”},“sort”:{“order”:“ascending”,“method”:“album”,“ignorearticle”:true}}}

{ FetchError: invalid json response body at http://xx.xx.xx.xx:8080/jsonrpc reason: Unexpected end of JSON input

at /app/node_modules/node-fetch/lib/body.js:48:31

at process._tickCallback (internal/process/next_tick.js:109:7)

name: ‘FetchError’,

message: ‘invalid json response body at http://xx.xx.xx.xx:8080/jsonrpc reason: Unexpected end of JSON input’,

type: ‘invalid-json’ }
<< Log ends>>

As you can see I have added code to find an album.  I get the same error trying to find a movie with unmodified Omertu code.
I take it that /app/node_modules/node-fetch/lib/body.js is in somebody else’s code?

Any ideas where to start?

Thanks

C

**Comment by cardomon** [comment]
Some progress

I had to set the username and password for my Kodi implementation, which are stored in the .env file of my glitch application to be all lower case.  This is different to the values actually in the Kodi implementation which are mixed case!

I can now get Kodi to stop, but not play a movie or, what I really want, find an album.  Log file says

Command sent = {“jsonrpc”:“2.0”,“id”:1,“method”:“AudioLibrary.GetAlbums”}
8:45 PM
TypeError: Cannot read property ‘length’ of undefined
8:45 PM
at Fuse._startSearch (/app/node_modules/fuse.js/src/fuse.js:170:23)
8:45 PM
at Fuse.search (/app/node_modules/fuse.js/src/fuse.js:141:10)
8:45 PM
at /app/server.js:306:27
8:45 PM
at process._tickCallback (internal/process/next_tick.js:109:7)
8:45 PM

Same error structure for GetMovies

Any ideas?

C

**Comment by manofsteel2017** [comment]
I've given up since I couldn't get it to work sadly.
I'm hoping someone on youtube made a video about it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cardomon** [comment]
OK, I got it to work - my new code referred to 'album.results.album' rather than 'albums.results.albums' which is what the JSON scheme for the RPC says.  Thanks Omertu!

Manofsteel - don't give up.  Sounds like your issues are at the Kodi end of the chain not in Glitch

C

**Comment by S1ntax** [comment]
Hello,

I am receiving an odd error I was hoping someone can look at. It gets all the way to kodi now but doesnt play because it states it can not find anything error message below.  I do have a build on Kodi so not 100% sure if that may be causing the issue. Let me know if you have run into this before.

Request token = *************
8:15 PM
Authentication succeeded
8:15 PM
Movie request received to play "Jurassic Park"
8:15 PM
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies"}
8:15 PM
Error: no results
8:15 PM
    at /app/server.js:156:13
8:15 PM
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by keydon** [comment]
I am closing this issue.
the original author seems to have given up.

@S1ntax if your problem still exists, please open a seperate issue. But as far as i can see, you simply dont have that movie in your local movie library. we currently dont support kodi-addons as sources for movies.
