### ISSUE TITLE
Integrate media automation, like Sonarr, Radarr?

### ISSUE THREAD

**Issue by gurabli** [OmerTu/GoogleHomeKodi#140]
Hi!
This project is really nice, thanks for your hard work!
I wonder if you would like to add Sonarr and Radarr integration, like it is done in [Phlex](https://github.com/d8ahazard/Phlex)?
For example: 

> OK Google, Ask Flex TV to download Season 2 Episode 5 of the show The Americans.
> OK Google, Ask Flex TV to fetch The Avengers Age of Ultron.

Then Sonarr (for shows) and Radarr (for movies) grabs and downloads the content.
Maybe the code (API instructions, etc) can be used from the Phlex project?

**Comment by keydon** [comment]
we control kodi and kodi alone. all the other apps or services are not in our scope. especially the illegal ones.
