### ISSUE TITLE
cannot install on Mac OSX

### ISSUE THREAD

**Issue by RegisMaltais** [OmerTu/GoogleHomeKodi#141]
Hi,

Can you describe on how to install on a Mac OSX ?

thanks

**Comment by keydon** [comment]
there are amost no OS-specific instructions on how-to-install this app. so where are you stuck?

**Comment by RegisMaltais** [comment]
Hi,

Where I can find the access token between ifttt and kodi ?

Thanks

Regis


Le 3 févr. 2018 à 11:03, Lukas <notifications@github.com<mailto:notifications@github.com>> a écrit :


there are amost no OS-specific instructions on how-to-install this app. so where are you stuck?

**Comment by keydon** [comment]
Just make one up. Think of it as a password.

**Comment by keydon** [comment]
closed due to inactivity
