### ISSUE TITLE
Anyone else having issues with Kodi 17.6?

### ISSUE THREAD

**Issue by Christyguy** [OmerTu/GoogleHomeKodi#143]
Running two boxes. Updated one to 17.6 and GoogleHomeKodi stopped working. Testing the connection I get the result that the connection was refused. I can access the box fine via the web otherwise.

17.5 box still working fine.

**Comment by keydon** [comment]
Kodi 17.6 on libreelec works fine for me

please provide some logs for further analysis.

**Comment by Christyguy** [comment]
Cleared the log on Glitch and then used the test connection page. Results below. Not at home so I can't get a log from Kodi box.

This box will take JSON commands just fine. I can play an item, start, stop (all of it) via remote url and it works fine. I have two servers running (one for each Kodi box) and their setup is identical except for the port numbers in the .env file. If I change the port number to the Kodi 17.5 box, it also works fine.
Thinking about doing a reinstall of Kodi on the box in questin.

________________________________________________________________________________________________________
Authentication succeeded

Command sent = {"jsonrpc":"2.0","id":1,"method":"GUI.ShowNotification","params":{"title":"Initiated by GoogleHomeKodi","message":"Test Successful!"}}

request failed

route:  /koditestconnection

query:  {}

error:  { FetchError: request to http://xxx.duckdns.org:8090/jsonrpc failed, reason: connect ECONNREFUSED 173.217.xx.xx:8090

    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)

    at emitOne (events.js:96:13)

    at ClientRequest.emit (events.js:188:7)

    at Socket.socketErrorListener (_http_client.js:309:9)

    at emitOne (events.js:96:13)

    at Socket.emit (events.js:188:7)

    at emitErrorNT (net.js:1277:8)

    at _combinedTickCallback (internal/process/next_tick.js:80:11)

    at process._tickCallback (internal/process/next_tick.js:104:9)

  name: 'FetchError',

  message: 'request to http://xxx.duckdns.org:8090/jsonrpc failed, reason: connect ECONNREFUSED 173.217.xx.xx:8090',

  type: 'system',

  errno: 'ECONNREFUSED',

  code: 'ECONNREFUSED' }

body:  { token: 'xxxx' }

**Comment by keydon** [comment]
does not look like a compatibility / kodi-version issue.

more like a connectivity problem.
make sure the option 'Allow remote control from applications on other systems' is enabled in your settings.

**Comment by Christyguy** [comment]
It's definitely not a version issue, I updated the other box last night and it's fine. The thing is, can control the box in question via json commands, even remotely. I am about to set this up locally anyways (as opposed to Glitch) so I will see if that resolves it.

**Comment by keydon** [comment]
Closed due to inactivity.
