### ISSUE TITLE
Question ... Slow to respond on first command for a while

### ISSUE THREAD

**Issue by cyberkid2002** [OmerTu/GoogleHomeKodi#144]
Hi all,

Using this add-on with Google Home and Kodi, and absolutely love it.  One thing I have noticed is a difference in response time between first command for a while, and subsequent commands issued soon after.

I am guessing this is an issue with the glitch.com service going into some kind of stand-by.  Is this correct?  And if so is there a work-around or just something that needs to be put up with?

Either way great work!

**Comment by keydon** [comment]
well certainly glitch has some kind of idle-mode for unused apps. that could be circumvented with a selfhosted node server like described in the readme.

but even kodi itself seems to have a idle-mode for its webservice, which afaik cannot be circumvented.

**Comment by messiah109501** [comment]
I noticed the same thing when I first started using this on Glitch. Since switching to running off a local server, the first command is just as quick as subsequent commands.

**Comment by keydon** [comment]
Closed due to inactivity + solutions available
