### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by JusCoz** [OmerTu/GoogleHomeKodi#145]
Wanted to say thank you to everyone involved on this project. I cannot seem to get the Reboot to work, my node server returns a 404. Looking over the source I cannot find where the reboot command is created. I found that this request functions on it's own --> http://192.168.100.13:8080/jsonrpc?request={"jsonrpc":"2.0","method":"System.Reboot","id":1}, but I can't find where GoogleHomeKodi creates such a call. If I'm blind and overlooking it I apologize.

**Comment by keydon** [comment]
make sure your installation is up to date, since the reboot command was just recently added to master (6 days ago).
other than that i dont know what i can tell you what a search here on this github-repository for "reboot" can not.

**Comment by JusCoz** [comment]
My apologies, I thought I had the latest version, but you are correct. Thank you so much.
