### ISSUE TITLE
How to run this with an IPv6?

### ISSUE THREAD

**Issue by Tahmid3** [OmerTu/GoogleHomeKodi#146]
How to run this with an IPv6?
I experienced some issues while I am using an IPv6 in the node in Glitch.
The error is 

> Executing request: /koditestconnection
> "request to http://[IPv6]:8080/jsonrpc failed, reason: connect EADDRNOTAVAIL IPv6:8080 - Local (:::0)"

I hope someone can help me.
Thanks in advance.

-Peace, out

**Comment by keydon** [comment]
glitch does not support IPv6, sorry. maybe find another host that does.

**Comment by Tahmid3** [comment]
Can someone give me recommendation for another host that supports ipv6 pls.

**Comment by keydon** [comment]
i guess noone know one, closed due to inactivity.
