### ISSUE TITLE
[help] Unsure how to debug my connection issue

### ISSUE THREAD

**Issue by mpartoglou** [OmerTu/GoogleHomeKodi#147]
Hi, I haven't used docker before and am unsure where i've gone wrong.

I installed docker (checked it works via helloworld), ran the commands to pull the 64 bit version - downloads runs. I've gone with the environment variables option - as follows:

```
docker run -d -p 8099:8099 \
           --restart always \
           -e KODI_PROTOCOL="http" \
           -e KODI_IP="192.168.86.20" \
           -e KODI_PORT="8080" \
           -e KODI_USER="" \
           -e KODI_PASSWORD="" \
           -e AUTH_TOKEN="YOUR_CONNECTION_PASSWORD" \
           --name googlehomekodi \
           sinedied/googlehomekodi
```
_I've removed my username and password, i haven't sent an auth_token_

I wanted to test if it was working, so i ran a local command in the web-browser. 

http://192.168.86.100:8099/navdown

This is the server where my docker image is hosted, I get no response and kodi doesn't do anything (also the url just errors). I then assumed it needed the token (which I haven't changed from default). I followed the instructions and used:

http://mydynamicipaddress.com:8099/navdown

Google Home gives me the response I programmed into IFTTT (i've done this many times when I manually programmed KODI to be controlled via IFTTT). However nothing happens in my single kodi instance.

I am sorry, I've tried looking at the instructions and can't work it out.

**Comment by keydon** [comment]
dont leave out the auth_token, it is indeed mandatory!

What do you when browsing to http://192.168.86.100:8099/ ?
Do you see the test-page? what happens if you enter there your auth_token and send the test-request? What is the output?

For debugging purposes you could try starting the container in interactive mode, that way you are able to see if it starts up successfully and how it processes the incoming requests.
For that remove the options `-d` and `--restart always` and replace them with `-it`.

**Comment by mpartoglou** [comment]
Hi Keydon,

A few follow-up questions and some answers:
- Do i set the Auth_Token to any long secure string
- I was not getting a test-page (just a 404 error) when trying the URL
- I removed the instance and re-ran it with the new command, (-it) instead of the others; I get the following error
```
$ docker run -it -p 8099:8099            -e KODI_PROTOCOL="http"            -e
KODI_IP="192.168.86.20"            -e KODI_PORT="8080"            -e KODI_USER=
""            -e KODI_PASSWORD=""            -e AUTH_TOKEN="1234567890"
    --name googlehomekodi            sinedied/googlehomekodi
Missing kodi host config. Please configure one using the .env (when using Glitch
) or the config.js file.
```

I assumed I was running it as an environment variable when pasting my command - looks like I am doing something wrong in my "run" command.

**Comment by keydon** [comment]
oh i think we dont handle the empty kodi user & password parameter very well in this case.
We consider it missing and a fallback for the file based configuration kicks in.

for now i see two options:
1. configure a kodi webservice user with a password
2. take the file based configuration approach.

**Comment by mpartoglou** [comment]
I've added a username and password - thanks, I would have never worked that out. Appreciate you update the thread to [bug] too - thanks so much!!

Now that i've added the username and password it works. (my trouble now is one for me to fix, the docker container incorrectly tries to run it on a subdomain that isn't accessible outside my network - but that's for me to fix and learn!)

A feature suggestion, have you thought about integrating this into HASS.io, it would be amazing to have this run alongside the HASS.io system so that Google Assistant would automatically have all these commands without the need to set each one up individually within IFTTT.

**Comment by utsnik** [comment]
I'm having some of the same problem. 

Whatever i do i cannot get it to work :S 
Kodi works fine from local and external ip as per your troubleshooting examples, but nothing happens with the docker server :/

Also when i forward the traffic in my router, am i supposed to forward it to the server that is running the docker? and on port 8099? 

Feels like i've been trying forever :(
