### ISSUE TITLE
IP Address For Glitch Project 

### ISSUE THREAD

**Issue by ghost** [OmerTu/GoogleHomeKodi#149]
How do I get the IP Address for my Glitch project as I need it for self hosting it

Any help is appreciated

**Comment by vijaykirann** [comment]
Try using dynamic DNS.. you can get the tutorial for usage by googling easily.

**Comment by keydon** [comment]
Closed due to inactivity

**Comment by LizcraveYT** [comment]
I don't see anything on it..
