### ISSUE TITLE
Not an issue - more of a question really 

### ISSUE THREAD

**Issue by McMoobud** [OmerTu/GoogleHomeKodi#15]
OmerTu - You are my HERO  

I got my home yesterday and got your amazing work up and running within an hour or so and it's SUPERB! 

One thing that just came to mind, do you think there's a way of adding PVR commands ? Would be awesome if you could say something like "Kodi play BBC1" or something like that. 

I'm totally new to JSON RPC commands so unsure. 

Thanks again ! 

Andrew

**Comment by OmerTu** [comment]
I've added support to play PVR channel by its name.
I don't use PVR, so I can't test if it works, but it should be straightforward (I hope :)
Perhaps you can [update](https://github.com/OmerTu/GoogleHomeKodi#how-to-update-to-the-latest-version) to the latest, and let me know if that works..

The setup is similar to play movie just using the following url instead:
> YOUR_GLITCH_SERVER_ADDRESS/playpvrchannelbyname?q= {{TextField}}

**Comment by McMoobud** [comment]
You are a true Gentleman! Thanks!

**Comment by McMoobud** [comment]
Works perfectly! Thanks again dude 💃
