### ISSUE TITLE
play random track from artist

### ISSUE THREAD

**Issue by bfenty** [OmerTu/GoogleHomeKodi#152]
The Playartist command works beautifully; however, it always starts with the same song. Could we get another command to start with a random song by that artist?

**Comment by keydon** [comment]
sure thing, we already shuffle the "play genre" command. this makes sense for playing artists as well.

**Comment by bfenty** [comment]
Awesome thanks!

**Comment by bfenty** [comment]
Another question: once it’s updated how do I update my local version? I see how to do it on Glitch but not for my local version. I don’t want to just overwrite everything...right?

**Comment by keydon** [comment]
how did you install your local version?
if you did it by cloning this repo a `git pull` should do the trick.
if you simply downloaded the zip and extracted it somewhere, redownload it and overwrite the old files and just to be on the save side do a `npm install` there afterwards.

but wait for this fix to reach the master branch aka when i close this issue ;)

**Comment by bfenty** [comment]
Yea I just unzipped and installed. 

Thanks for the help. Loving the software although IFTTT won’t communicate so I’m writing some python to call it separately. That’s another issue though and no fault of yours :)

**Comment by keydon** [comment]
what do you mean, IFTTT won´t communicate?

**Comment by bfenty** [comment]
ISP won’t let me port forward. They have an intermediate IP that shows publicly that’s not mine. I’ve read some people have solved it through VPNs or such but I’m not sure I want to be completely dependent on someone else’s service to make this work. 

I’m thinking I’m going to roll my own google home with the AIY kit. 

Also, and this is WAY off topic, but does the multi room feature not work? When I send the id tag via post nothing happens, but I drop it and it works.
