### ISSUE TITLE
Solved!! tv standby not working

### ISSUE THREAD

**Issue by crackinx** [OmerTu/GoogleHomeKodi#156]
Update #2: So it seems this was an issue and I was just running an older version, updated to the latest and it all works great now.

Update: made a process.env and put the command into it, now I can turn the tv on from standby, but it seems there is no command set from the server for putting the tv into standby. I get an authentication successful and nothing else is issued.

The instructions indicate that something needs added to the .env, but when running from a local server I have no .env, so not sure what do do here.

The script that needs to be installed is working properly. I can issue a manual command and the tv turns on and off, I just don't get anything from the voice control side.

**Comment by keydon** [comment]
i am glad you got it working!
