### ISSUE TITLE
Worked great

### ISSUE THREAD

**Issue by srmysqldba** [OmerTu/GoogleHomeKodi#157]
Hey guys,
So just returned from trip, and low and behold google doesnt understand anymore. So Ii was like ok recreate the ifttt, still not makingbthe call. Did some testing and it works with curl, so not a problem with the application. Just wondering if anyone else is seeing this issue?

**Comment by srmysqldba** [comment]
Could this be part of googles removing Kodi suggestion, and forcing you to chromecast? If so ill have to say good by to google home.

**Comment by srmysqldba** [comment]
Ok, fround a phrasenthe works now, "Hey Google, On my htpc start <movie> in the living room"

**Comment by keydon** [comment]
sometimes "kodi play" works just fine, sometime it does not. i guess it depends on the mood of the google ;)

when i check the logs i see that it sometimes understands "cody play" or "tony play".
i guess if you give kodi more common "human" name like i.e. "Peter play" it would work more reliable.
