### ISSUE TITLE
Support for multi-byte character parameters

### ISSUE THREAD

**Issue by malidong** [OmerTu/GoogleHomeKodi#158]
Hi guys, this project is awsome.
While there is some problem in handling 4-byte characters like Japanese or Chinese.
And unfortunately ifttt's webhook service does not urlencode the target url.
My solution locally is to use utf8.decode with parameters. (I'm a new bee to node js.)
Would you solve this problem in master branch ?

And another feature request if possible. ( May be this should be a kodi add-on. )
I get movie titles in many languages, while google home only support a certain language.
Is it possible to query movie title in other languages from imdb/tvdb, then do fuzzy search?
For example, I say 「ダークナイト」 and GoogleHomeKodi search and get 「The Dark Knight」(I think it has the same movie id in imdb.) , then make a fuzzy search with movie titles in kodi and play it.

**Comment by keydon** [comment]
not sure if i understand what the problem is.

For example:
![image](https://user-images.githubusercontent.com/2421541/39073877-a67c0244-44ef-11e8-9d9d-d1d2f4321c3d.png)

seems to work just fine when calling our app directly.
but you are saying that through ifttt, the charactes are not encoded correctly? is that right?

**Comment by malidong** [comment]
Sorry, it seems the ifttt's problem.
I said [あいうえお] but got a strage string.
Ifttt just use the lowest 1-byte of every charactor, and does not support multi-byte charactors.
My solution is move the "q" parameter to body (where "token" be stored.) and it works fine.

**Comment by keydon** [comment]
a good solution, thanks for sharing.
i prefer the "q" embedded in the json body aswell.
