### ISSUE TITLE
Your kodi library does not contain a single movie

### ISSUE THREAD

**Issue by ofirdoo** [OmerTu/GoogleHomeKodi#160]
hi everybody,
I managed to set everything up for Google home but whatever command for playing movie or show I try - it says "Your kodi library does not contain a single movie". What is that all about?

**Comment by keydon** [comment]
are you serious?
i thought i could not have made that error message more self explanatory.
but i guess you proved me wrong. unbelievable.

**Comment by ofirdoo** [comment]
Sorry, maybe I wasn't clear enough. Message is ok but I can't find out the reason why I have it since kodi library has more than couple movies in it.
I'll try to re-check or re-install and let you kniw if problem persist.

**Comment by keydon** [comment]
i find that hard to believe.
are you sure your movies are in the kodi library and not some addon?
