### ISSUE TITLE
Any chance for ipv6 support?

### ISSUE THREAD

**Issue by muhkuhgh** [OmerTu/GoogleHomeKodi#163]
I only got an external ipv6 from my ISP. I got none of the methods workings.. ):

**Comment by keydon** [comment]
well, since IFTTT does not currently support ipv6 natively, you need to host _GoogleHomeKodi_ somwhere, which is reachable by IFTTT/ipv4 and is also able to talk to YOU/ipv6.

i dont know such a service, but i am sure there is one out there.

**Comment by muhkuhgh** [comment]
Yeah.. I'll probably check out/try
http://www.feste-ip.net/dslite-ipv6-portmapper/universelle-portmapper/

Lukas <notifications@github.com> schrieb am Mi., 4. Juli 2018, 22:13:
