### ISSUE TITLE
Toggle fullscreen

### ISSUE THREAD

**Issue by janvitos** [OmerTu/GoogleHomeKodi#166]
Hi,

I went over the full table with available actions but did not find one to make Kodi toggle between windowed and fullscreen mode.

I believe this would be useful for me since my Kodi server is also my living room computer and Kodi isn't always in fullscreen mode.

Here is the Kodi HTTP command to toggle fullscreen:

```
{"jsonrpc": "2.0", "method": "Input.ExecuteAction", "params": {"action":"togglefullscreen"}}
```

I believe this would be a nice addition to GoogleHomeKodi.

Thank you.

**Comment by keydon** [comment]
your pull request was squash-merged into https://github.com/OmerTu/GoogleHomeKodi/commit/ccb0e6fda51531c497bd9a028614d8a9a0bd214e

tank you!
