### ISSUE TITLE
ACTIVATE_TV only documented for Glitch, here's how to do it with standalone Windows node server

### ISSUE THREAD

**Issue by janvitos** [OmerTu/GoogleHomeKodi#168]
Hi,

I noticed in the documentation that ACTIVATE_TV=true was only documented for Glitch.

I got it working on a standalone Windows node server by adding this line to the bottom of my kodi-hosts.config.js file:

process.env['ACTIVATE_TV'] = 'true';

I thought this might help anyone who wants to have their TV / Projector turned on when they play a movie, but also have a standalone node server.

Maybe this could be added to GoogleHomeKodi's documentation.

Thanks again for this great Google Home / Kodi addon.

**Comment by keydon** [comment]
merged
