### ISSUE TITLE
Add /jsonrpc endpoint support

### ISSUE THREAD

**Issue by jack1142** [OmerTu/GoogleHomeKodi#180]
Hi,
I think that it would be good to add the /jsonrpc endpoint support. We wouldn't be limited by capabilities of your API and we would be able to do any request allowed by Kodi's JSON-RPC.
For now it's just not possible to, for example, specify params for ExecuteAddon - we can only choose what addon we want to execute, which doesn't give us option to for example search for movies in custom addon without coding it into the api.

**Comment by jack1142** [comment]
It already is, as you can use the Kodi api for all those things directly anyway (or most of them).
Maybe if you would add permissions support for jsonrpc this would make more sense as there's no permissions for jsonrpc in Kodi itself, so this api could solve lack of permissions problem.
Now, your api seems to be useful only, if someone can't use HTTP Basic Auth.
I don't want to offend that project, I just was thinking about use cases for this api and I can't really see the point of using it instead of just Kodi API, so adding permissions to jsonrpc could be some added functionality, if you would want to create something like that.

Maybe this project is just not for me and I'm just complaining, sorry if that's the case, I did this issue, when I was trying to use your api, because I couldn't use HTTP Basic Auth (as it turned out, I just didn't know I can use it on IFTTT) ¯\\\_(ツ)_/¯

**Comment by keydon** [comment]
well, the primary purpose of this project is to handle high-level voice commands straight from _IFTTT_.
Due to limitiations of IFTTT (i.e. executing multiple requests and process responses of those requests) and the low-level-architecture of the kodi-API its just not possible i.e. to play the next unwatched episode of your favorite tv show with a single kodi-api request called from _IFTTT_.

There where you dont need multiple requests or fuzzy interpretation of your search terms you can go ahead and use the kodi-api directly.

**Comment by jack1142** [comment]
@keydon Okay, so what would you say about possibility to create such "chains" of requests, so user could easily create a custom request, which would call several requests in kodi-api directly? Something like possibility to create simple addons/plugins with such custom requests, so not experienced user would be able to run few requests, using one function in plugin for each for example and more expierenced user would also be able to process the data from one request and use it in another or do whatever else he wants, if he knows how to develop it. So your project could serve as a base for other's people use cases and they would be able to extend it however they want. This actually could be useful in several cases, I think I could probably find a few as well.

Of course it's already possible, if some developer would edit your code for his needs, but it would be much easier, if instead of editing it, they would just have to create a plugin.

I'm just giving an idea as this project sounds awesome, but it lacks of some expandability.
