### ISSUE TITLE
Using this in combination with VPN?

### ISSUE THREAD

**Issue by UnderControl23** [OmerTu/GoogleHomeKodi#185]
Hi

My Kodi is running on a Raspberry Pi and I have it configured to always run on my VPN. Is it possible to use this tool to control my Kodi?

Kind regards
Nathan

**Comment by axs-gentoo** [comment]
The cloud services would need to be able to reach your RPi from the external VPN end-point.  Your ability to do this would depend entirely on the VPN service you are using, but as I expect this is a very advanced feature I feel it would be unlikely.

**Comment by keydon** [comment]
timeout -> closed.
