### ISSUE TITLE
Pass full command text from IFTTT and parse locally?

### ISSUE THREAD

**Issue by axs-gentoo** [OmerTu/GoogleHomeKodi#186]
Hi - I've been playing with this module and IFTTT for a little while now, it works very nicely for what it does.  At this point my biggest peeve is that a separate IFTTT applet has to be created for every single command (multiplied by every single kodi to be addressed).

I was wondering what your thoughts are on adding a /parsetext?q= option so a single IFTTT applet using Google Assistant trigger of 'kodi $' (or 'make kodi $' or 'have kodi $') could receive the full command text and (possibly with the help of an NLS library) allow for parsing and interpretation of both command and kodi-id locally.

I realize this would be a fairly significant addition to the codebase, but it would certainly make setting it up a lot simpler for end users.

**Comment by axs-gentoo** [comment]
All good points.  

I was considering attempting to use IFTTT's publisher while the javascript "filter" handles the (somewhat limited need for) language processing, but the editor is difficult to deal with and I have concerns on the amount of code that can be provided within it, not to mention that I don't think IFTTT's Google-Assistant can output values in a way that is useful or relevant enough that we wouldn't still have to parse the whole text string ourselves anyways.  

At least if we handle it ourselves, IFTTT still provides a dead-simple way to connect Google Assistant (or Alexa or other inputs) into triggering this wrapper for Kodi commands.  Thanks for keeping it under consideration as an enhancement.

**Comment by NovaGL** [comment]
I'm using this with Alexa, instead of IFTTT I use Lamdba and let ASK (Alexa Skill Kit) try to find the best matches.

**Comment by keydon** [comment]
the PR from WallyCZ should satisfy this request. Closing.
