### ISSUE TITLE
Switch on TV not working

### ISSUE THREAD

**Issue by MrLachdanan** [OmerTu/GoogleHomeKodi#19]
Firstly, thank you for all your efforts - this is SO amazing (and easy to do for even me who am simply copy/pasting most of the time). 

I was wondering if you'd be able to help, and let me know what you need - I duplicated the play/pause IFTTT exactly like you said, and did all the other configs too, but when I test it IFTTT says my applet failed. Every other applet works flawlessly, but it seems this one fails even before it gets to Kodi

**Comment by OmerTu** [comment]
Just to make sure, everything works for you except turning on the TV?
If that's the case, start by verifying the following steps:
1. Have you update your Glitch server to the latest version of this project?
2. Have you installed the script.json-cec add-on?
3. Are you running the latest kodi?
4. Make sure CEC commands are supported and enabled in your TV (see more [here](http://kodi.wiki/view/CEC)) 
5. Try to turn on the TV by putting the following URL in your browser:
`
http://KODI_INTERNAL_IP:KODI_PORT/jsonrpc?request={"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.json-cec","params":{"command":"activate"}},"id":1}
 `
(Make sure to replace KODI_INTERNAL_IP and KODI_PORT)

**Comment by MrLachdanan** [comment]
Hi,

I thought it did (Samsung 5-series), but apparently it doesnt, because the
URL returned an OK, but the TV stays off...guess its time for a new TV!

Thanks for the help!

**Comment by OmerTu** [comment]
BTW, it's also possible that your computer doesn't support CEC commands.
(Mine didn't, I had to buy a separate CEC [adapter](https://www.pulse-eight.com/p/104/usb-hdmi-cec-adapter))

**Comment by keydon** [comment]
Issue seems to be resolved. Closing.
