### ISSUE TITLE
Selecting Sources after Play

### ISSUE THREAD

**Issue by chriskol** [OmerTu/GoogleHomeKodi#192]
I notice that when I play an item I'm streaming, there are often options for sources to choose from.  I'm wondering what options people are using for voice control to select a source for playing.  Right now the only thing I can figure is giving the voice command to navigate down/up then select?

I notice the sources often have numbers next to them.  I've tried using the select command there and the IFTTT recipe of command + number but no dice.  Any thoughts?

**Comment by keydon** [comment]
you will have to stick to the low-level up/down commands. there wont be special support for your addon.
