### ISSUE TITLE
Inconsistent results with navup/navdown

### ISSUE THREAD

**Issue by chriskol** [OmerTu/GoogleHomeKodi#193]
I'm getting some wonky stuff going on when I ask Kodi to navigate up and down. For a while, no numbers were working below 5, but now things seem to have leveled off for some reason and I'm getting the following bugs.

"Kodi navigate up/down 2" results in an "I'm sorry I don't know how to help"
"Kodi navigate up/down 4" results in an "I'm sorry I don't know how to help"
"Kodi navigate up/down 5" results in the cursor going up/down 1.

Not sure what's going on here but will fiddle around when I get some more time.

For context, I'm doing this on the Movies library screen.

**Comment by keydon** [comment]
> I'm sorry I don't know how to help
this usually means, that google did not understand your "kodi"-trigger. your command was never passed down to IFTTT or this app. Nothing we can do here other than maybe choosing another keyword which is less likly to be missunderstood as Cody/Toby or something^^ You can see in googles voice logs what you assistand actually understood.

> Kodi navigate up/down 5" results in the cursor going up/down 1
![image](https://user-images.githubusercontent.com/2421541/47882436-cbdbb880-de29-11e8-845e-93797e781e3e.png)

cannot reproduce, works fine for me.

**Comment by chriskol** [comment]
Thanks.  I'll check this in a day or so.  To me it's just odd that it's those specific instances it doesn't work.  For every other number I've tried, it works fine.  I'm pretty sure I don't have a strange speech impediment and English is my first language so I'm not sure why it wouldn't be recognizing 2 and 4, and why 5 seems to seems to equal 1.

The only thing I can think for 2 and 4 is that it's an Assistant issue where it's interpreting those as "to" and "for" and the command is messing up?

**Comment by keydon** [comment]
hmm you may be right, I just checked the code and there is a fallback to "1" in case the input was not a valid number. now it would be interesting what input gets passed to this app from IFTTT. Unfortunately there is no suitable logging for this part of the app. let me improve that, then you can retry to see whats what.

**Comment by chriskol** [comment]
That would be great.  It's interesting that a) the scenarios above appear to be working for you on voice and b) that 2 and 4 don't default to 1 but instead give a to "I'm sorry I don't know how to help".

I've noticed when I issue a "Kodi play show" command, it sometimes if it doesn't hear me properly (probably the kodi part) it talks about how there's no cast or item in the library by that name.  So I further wonder if the issue is Google hearing "2" and "4" and taking them as operators "to" and "for".  Maybe I can even test this by making the navigate command more complicated/pronounced so as to remove ambiguity as to whether it's a "4" or "four".

So like maybe instead of "kodi navigate down 4", do "kodi navigate item menu down 4" or something.

**Comment by keydon** [comment]
okay, i just pushed a new version to develop-branch, which prints out the numberinput to the console. check that out.

also try have a more natural command structure.
like _kodi go down # times_ or _kodi go down by # items_
also maybe have a second phrase for the single item case.

**Comment by chriskol** [comment]
```
Navigate down request received

could not parse input 'five' as number

Command sent = {"jsonrpc":"2.0","id":1,"method":"Input.Down"}

Authentication succeeded

Navigate down request received

parsed valid number: 1

Command sent = {"jsonrpc":"2.0","id":1,"method":"Input.Down"}
```

Am I just saying '5' wrong somehow? haha

Also in between 5 and 1, I had tried 2 and 4 with the same error.  It appears to not have even logged anything.

**Comment by keydon** [comment]
Are you sure you have set up your IFTTT applet correctly?
For numeric placeholders you need to use `#` instead of `$`. That way IFTTT forces itself to recognize a number instead of the word _five_

**Comment by chriskol** [comment]
Yes.  I'm using:
`kodi navigate down #`

If it weren't setup correctly, I can't imagine it would work for the other numbers. I've been trying random high numbers too and it seems to work.  Just recognized 'twelve' too.

It seems to be only giving me issues with not recognizing 2 and 4, as well as detecting 5 as 1 as per the above where it couldn't parse five as a number for some reason :/
