### ISSUE TITLE
Playlist control failing

### ISSUE THREAD

**Issue by ferdi-t** [OmerTu/GoogleHomeKodi#194]
Finally got Googlehomekodi to work. Thank you for this software.

However, playlists don't work. Ifttt calls them rightly and I set it up using the readme.

Thoughts, anyone?

**Comment by ferdi-t** [comment]
Well, it doesn' play the playlist I mention. 😀

Steps I verified:

- Ifttt executes the command
- kodi's logs don't show any imput
- ifttt-command is set up as per the docs
- other commands (play, volume, party mode) run perfectly

I'm running GHK as a deamon, so I don't have any output. Does it log output somewhere?

Otherwise I'll try running it manually and confirm the output.

**Comment by keydon** [comment]
I think this is a misunderstanding.
This command allows playing the previous/next item of a currently playing playlist.
Its not meant to start playing a playlist by name.

**Comment by keydon** [comment]
added `/playplaylist?q=my playlist` for you guys
