### ISSUE TITLE
Shutdown wont work

### ISSUE THREAD

**Issue by Tony4711** [OmerTu/GoogleHomeKodi#197]
Hi, 
very nice project, makes fun to control kodi with google home.
But when i try to turn kodi on or off it wont work for me.
In ifttt I get this Error: unable to make webrequest. Error: gettaddrinfo ENOTFOUND
When I try the Commando in my Browser I get this Error: {"error":{"code":-32099,"message":"Bad client permission."},"id":1,"jsonrpc":"2.0"} 

What I am doing wrong ? I set it up with a Glitch Server.

Edit:
Fixed, but I don't know what the problem was. Just typed everything knew in ifttt from my pc instead of my mobilephone and know it works.

-----Closed----

**Comment by keydon** [comment]
glad you got it working :)
