### ISSUE TITLE
Unable to make web request. Your server returned a 401

### ISSUE THREAD

**Issue by shocam** [OmerTu/GoogleHomeKodi#198]
Hi All

i am so close to getting this working now, but IFTTT keeps displaying the error:

Unable to make web request. Your server returned a 401

the test URL to pause works on both internal and external IPs - i am using option 2 Local Webserver - details below:

    // YOUR_CONNECTION_PASSWORD
    authToken: 'MyConnectionToken',

![image](https://user-images.githubusercontent.com/46050052/50344917-0c4fdc80-0525-11e9-89a1-2b6c940894c8.png)

any help you can provide will be appreciated, this is driving me nuts now!!!!

**Comment by cgmille2** [comment]
I am having this exact same issue. Test URLs from internal and external IPs work fine, but ifttt gives me the 401 error. I am using docker on libreelec. This is driving me crazy too! Thanks

**Comment by keydon** [comment]
well, what does the console output say, when an IFTTT-Execution fails?
seems like you guys configured your token incorrectly.

**Comment by keydon** [comment]
And another thing you guys can test. do the Test-Urls work from _outside_ of your home network?
like from your smartphone with disabled wifi?

**Comment by keydon** [comment]
yeah, I meant that node-std-output. thank you.
that is indeed weired. that pretty much empty log indicates, that nothing reached the app at all o.O
I hope you did not put the urls with "jsonrpc" into IFTTT. Those are only for troubleshooting problems between kodi and this app.
Also its not important to reach the kodi-jsonrpc urls from external network, thats what the app is for.
its like a gateway between IFTTT and kodi's jsonrpc-API.

You need to test the YOUR_NODE_SERVER URL from an external network and also put that into IFTTT.

**Comment by cgmille2** [comment]
I can reach my NODE_SERVER:8099 from outside my home network, but when I put in my access token it says "Executing request: /koditestconnection"  for about 2 minutes until "Executing request: /koditestconnection" turns red
However, if I put in the wrong access token it immediately says:
```
Executing request: /koditestconnection

Forbidden
{
  "message": "403 - Forbidden",
  "name": "ResponseException",
  "status": 403,
  "statusText": "403 - Forbidden"
}
```

**Comment by shocam** [comment]
> And another thing you guys can test. do the Test-Urls work from _outside_ of your home network?
> like from your smartphone with disabled wifi?

I have tested the URL from outside of my network (smartphone with WiFi turned off) and it works fine, pauses and unpauses - but still it comes up with 401 error when running through IFTTT:

![image](https://user-images.githubusercontent.com/46050052/50480585-b079cd80-09d4-11e9-9add-2ae72a47e8ed.png)

**Comment by keydon** [comment]
@cgmille2 
> I can reach my NODE_SERVER:8099 from outside my home network, but when I put in my access token it says "Executing request: /koditestconnection" for about 2 minutes until "Executing request: /koditestconnection" turns red

this indicates a connection problem between *this app* and *kodi*. Our readme says that the *EXTERNAL_IP* should be used for `KODI_IP`, which is wrong. Using `127.0.0.1`/`localhost` would also be wrong! (even though you are on the same physical machine, since its docker)
The correct address for your scenario *B.3* can be looked up in kodi itself `Settings > Systeminfo > Info > IP-Adress` or you can simply use the hostname instead of the ip (`libreelec` by default)
**Hint:** It might help enabling the LibreELEC setting "wait for network before starting kodi"

**Comment by keydon** [comment]
@shocam 
moving on from the kodi-test-urls.
What are your results with the NODE_SERVER URLs?
What does the console output say during your tests?

**Comment by cgmille2** [comment]
Thanks keydon. So simple. Everything is working perfectly now

**Comment by shocam** [comment]
> @shocam
> moving on from the kodi-test-urls.
> What are your results with the NODE_SERVER URLs?
> What does the console output say during your tests?

@keydon - how do i get the console output? I have tried searching for logs but i cannot find any.......

**Comment by keydon** [comment]
lol, if the `/playmovie` request reaches your kodi you mixed up the **URLs** and put the _wrong_ one into your _IFTTT_ (or your port forwarding forwards to the wrong port).
I recently updated the docs, reread sections **A** and **B.2** and the **troubleshooting** section.
Pay attention where you need the *KODI_IP/KODI_PORT*s and where the *YOUR_NODE_URL*, they are not interchangeable!

Basically the chain should look like this:
```
IFTTT -> /playmovie -> GoogleHomeKodi (Node)
GoogleHomeKodi (Node) -> /jsonrpc -> Kodi
Kodi -> *plays movie*
```

But according to the kodi log you provided your broken chain looks like this:
```
IFTTT -> /playmovie -> Kodi
Kodi -> **ERROR**
GoogleHomeKodi (Node) -> *sits there and does nothing*
```

**Comment by shocam** [comment]
thanks @keydon 

I have sorted the ports out now and port forwarding is working correctly - however, i am now getting the below error when running the from the /koditestconnection page:

* kodiassistant.service - Node.js Google Home Kodi Interface
   Loaded: loaded (/etc/systemd/system/kodiassistant.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-01-03 10:20:19 GMT; 13min ago
 Main PID: 221 (node)
   CGroup: /system.slice/kodiassistant.service
           `-221 /usr/bin/node /home/osmc/node/GoogleHomeKodi/server.js

Jan 03 10:29:36 osmc nodejs-example[221]:     at emitErrorNT (internal/streams/destroy.js:82:8)
Jan 03 10:29:36 osmc nodejs-example[221]:     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
Jan 03 10:29:36 osmc nodejs-example[221]:     at process.internalTickCallback (internal/process/next_tick.js:72:19)
Jan 03 10:29:36 osmc nodejs-example[221]:   name: 'FetchError',
Jan 03 10:29:36 osmc nodejs-example[221]:   message:
Jan 03 10:29:36 osmc nodejs-example[221]:    'request to http://31.54.xx.xx:XX75/jsonrpc failed, reason: connect ETIMEDOUT 31.54.161.114:7075',
Jan 03 10:29:36 osmc nodejs-example[221]:   type: 'system',
Jan 03 10:29:36 osmc nodejs-example[221]:   errno: 'ETIMEDOUT',
Jan 03 10:29:36 osmc nodejs-example[221]:   code: 'ETIMEDOUT' }
Jan 03 10:29:36 osmc nodejs-example[221]: body:  { token: 'testtoken' }

**Comment by shocam** [comment]
@keydon  - scratch my last response - i hadnt forwarded the port for my kodi box, done that and the movie plays!!!

thanks for all your help all, really appreciate it - now to set up some other actions!!!

**Comment by shocam** [comment]
great, thanks again @keydon - all sorted now and working!
