### ISSUE TITLE
Set up Docker image error on Libreelec

### ISSUE THREAD

**Issue by dynamiik** [OmerTu/GoogleHomeKodi#200]
Hi I'm stuck on set this up. I try to 'Set up local webserver using Docker' on my Raspberry Pi 3 runnig Libreelec 9. 
I installed the Docker service from Kodi.
But when i try to run this command: 
`docker build --tag omertu/googlehomekodi https://github.com/OmerTu/GoogleHomeKodi.git `
I get the following error Message:
`unable to prepare context: unable to find 'git': exec: "git": executable file not found in $PATH`
Then I downloaded the GoogleHomeKodi.git as .zip and upacked and copyed it on the Libreelec system. Then i run the following command:
`docker build --tag omertu/googlehomekodi downloads/GoogleHomeKodi-master/`
and get this Output:
Sending build context to Docker daemon  571.9kB
Step 1/12 : FROM node:alpine
 ---> 8a7c2820ad0a
Step 2/12 : ENV GOOGLE_HOME_KODI_CONFIG="/config/kodi-hosts.config.js"
 ---> Using cache
 ---> 0e8a972bc332
Step 3/12 : ENV NODE_ENV=production
 ---> Using cache
 ---> c0f687a6bc9a
Step 4/12 : ENV PORT=8099
 ---> Using cache
 ---> 7422752865da
Step 5/12 : VOLUME /config
 ---> Using cache
 ---> 47a20dfab046
Step 6/12 : WORKDIR /home/node/app
 ---> Using cache
 ---> 12a63d7f4da6
Step 7/12 : COPY package*.json ./
 ---> Using cache
 ---> 6456ca36d112
Step 8/12 : RUN npm install --production && npm cache clean --force
 ---> Running in 61a8ded5f43b

> deasync@0.1.13 install /home/node/app/node_modules/deasync
> node ./build.js

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:160:21)
gyp ERR! System Linux 4.19.8
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/app/node_modules/deasync
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.13 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-01T17_13_23_604Z-debug.log
The command '/bin/sh -c npm install --production && npm cache clean --force' returned a non-zero code: 1

What have I done wrong?

**Comment by keydon** [comment]
hmm seems some node-dependencies changed, but needs more inverstigation.

**Quickfix:**
Open the file `Dockerfile` and change the first line to:
```
FROM node:8-alpine
```

**Comment by dynamiik** [comment]
Thanks for the quick reply. I get still an error:

Sending build context to Docker daemon  571.9kB
Step 1/12 : FROM node:8-alpine
8-alpine: Pulling from library/node
5b678b67777f: Already exists
d9f0b2b885d9: Already exists
7a33101f563c: Pull complete
60d15459f816: Pull complete
Digest: sha256:f30a55706c7336a648493b926128f56176e4500cfdc968764bfdb711716e0109
Status: Downloaded newer image for node:8-alpine
 ---> b4a0777a56ee
Step 2/12 : ENV GOOGLE_HOME_KODI_CONFIG="/config/kodi-hosts.config.js"
 ---> Running in c365848e9780
Removing intermediate container c365848e9780
 ---> ada894409a62
Step 3/12 : ENV NODE_ENV=production
 ---> Running in 1faad5b1b26c
Removing intermediate container 1faad5b1b26c
 ---> cc0ed5c02723
Step 4/12 : ENV PORT=8099
 ---> Running in 0326c17069c3
Removing intermediate container 0326c17069c3
 ---> cc9df8a64553
Step 5/12 : VOLUME /config
 ---> Running in 222213c78566
Removing intermediate container 222213c78566
 ---> 7c48ae743376
Step 6/12 : WORKDIR /home/node/app
 ---> Running in e3326e9be9ab
Removing intermediate container e3326e9be9ab
 ---> 328319ca93cd
Step 7/12 : COPY package*.json ./
 ---> 651246693824
Step 8/12 : RUN npm install --production && npm cache clean --force
 ---> Running in ecb8a4aace99

> deasync@0.1.13 install /home/node/app/node_modules/deasync
> node ./build.js

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.19.8
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/app/node_modules/deasync
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.13 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-01T20_34_22_729Z-debug.log
The command '/bin/sh -c npm install --production && npm cache clean --force' returned a non-zero code: 1

**Comment by keydon** [comment]
hmm weird worked for me, when I tried it on my laptop. Guess for some cpu-architectures some npm packages contain prebuilt binaries, for others, they get compiled on the fly.

Here is another solution, this time verified on a raspi 1.
Replace the complete content of your Dockerfile with this one:
```Dockerfile
FROM node:alpine as builder

ENV NODE_ENV=production
RUN apk --update add python make g++

WORKDIR /home/node/app

COPY package*.json ./
RUN npm install --production



FROM node:alpine

ENV GOOGLE_HOME_KODI_CONFIG="/config/kodi-hosts.config.js"
ENV NODE_ENV=production
ENV PORT=8099

VOLUME /config
WORKDIR /home/node/app

COPY --from=builder /home/node/app/node_modules ./node_modules
COPY . .

EXPOSE 8099
USER node
CMD ["node", "server.js"]
```

**Comment by dynamiik** [comment]
Alright this time it seems to work. 
There was some text written in red color in the output so i post it here to verify it went all well.

Sending build context to Docker daemon  572.9kB
Step 1/17 : FROM node:alpine as builder
 ---> 8a7c2820ad0a
Step 2/17 : ENV NODE_ENV=production
 ---> Running in 44c06baf6f0a
Removing intermediate container 44c06baf6f0a
 ---> bd860af0a741
Step 3/17 : RUN apk --update add python make g++
 ---> Running in 1e4191072dc3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/armhf/APKINDEX.tar.gz
(1/23) Installing binutils (2.30-r5)
(2/23) Installing gmp (6.1.2-r1)
(3/23) Installing isl (0.18-r0)
(4/23) Installing libgomp (6.4.0-r9)
(5/23) Installing libatomic (6.4.0-r9)
(6/23) Installing pkgconf (1.5.3-r0)
(7/23) Installing mpfr3 (3.1.5-r1)
(8/23) Installing mpc1 (1.0.3-r1)
(9/23) Installing gcc (6.4.0-r9)
(10/23) Installing musl-dev (1.1.19-r10)
(11/23) Installing libc-dev (0.7.1-r0)
(12/23) Installing g++ (6.4.0-r9)
(13/23) Installing make (4.2.1-r2)
(14/23) Installing libbz2 (1.0.6-r6)
(15/23) Installing expat (2.2.5-r0)
(16/23) Installing libffi (3.2.1-r4)
(17/23) Installing gdbm (1.13-r1)
(18/23) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(19/23) Installing ncurses-terminfo (6.1_p20180818-r1)
(20/23) Installing ncurses-libs (6.1_p20180818-r1)
(21/23) Installing readline (7.0.003-r0)
(22/23) Installing sqlite-libs (3.25.3-r0)
(23/23) Installing python2 (2.7.15-r1)
Executing busybox-1.28.4-r2.trigger
OK: 178 MiB in 38 packages
Removing intermediate container 1e4191072dc3
 ---> 7f1e6bed77cb
Step 4/17 : WORKDIR /home/node/app
 ---> Running in a28c6a923f77
Removing intermediate container a28c6a923f77
 ---> 6a453e4b3803
Step 5/17 : COPY package*.json ./
 ---> 0b91b5974667
Step 6/17 : RUN npm install --production
 ---> Running in d6af3d544a82

 deasync@0.1.13 install /home/node/app/node_modules/deasync
 node ./build.js

make: Entering directory '/home/node/app/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o

> **Here starts the text in red color**


In file included from ../src/deasync.cc:3:0:
../../nan/nan.h: In constructor 'Nan::Utf8String::Utf8String(v8::Local<v8::Value>)':
../../nan/nan.h:1064:78: warning: 'v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const' is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                                                              ^
In file included from /root/.node-gyp/11.6.0/include/node/v8.h:26:0,
                 from ../src/deasync.cc:2:
/root/.node-gyp/11.6.0/include/node/v8.h:2538:31: note: declared here
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/root/.node-gyp/11.6.0/include/node/v8config.h:326:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~

> **End of red text**


  SOLINK_MODULE(target) Release/obj.target/deasync.node
  COPY Release/deasync.node
make: Leaving directory '/home/node/app/node_modules/deasync/build'
Installed in `/home/node/app/node_modules/deasync/bin/linux-arm-node-11/deasync.node`
added 121 packages from 144 contributors and audited 706 packages in 48.619s
found 11 vulnerabilities (4 low, 5 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container d6af3d544a82
 ---> f33de9c634fb
Step 7/17 : FROM node:alpine
 ---> 8a7c2820ad0a
Step 8/17 : ENV GOOGLE_HOME_KODI_CONFIG="/config/kodi-hosts.config.js"
 ---> Using cache
 ---> 0e8a972bc332
Step 9/17 : ENV NODE_ENV=production
 ---> Using cache
 ---> c0f687a6bc9a
Step 10/17 : ENV PORT=8099
 ---> Using cache
 ---> 7422752865da
Step 11/17 : VOLUME /config
 ---> Using cache
 ---> 47a20dfab046
Step 12/17 : WORKDIR /home/node/app
 ---> Using cache
 ---> 12a63d7f4da6
Step 13/17 : COPY --from=builder /home/node/app/node_modules ./node_modules
 ---> 9033317959c5
Step 14/17 : COPY . .
 ---> 910b0baaa6a2
Step 15/17 : EXPOSE 8099
 ---> Running in 1f8ce5608283
Removing intermediate container 1f8ce5608283
 ---> 760ff4b62642
Step 16/17 : USER node
 ---> Running in 918e9ad401a5
Removing intermediate container 918e9ad401a5
 ---> 66a5d211c037
Step 17/17 : CMD ["node", "server.js"]
 ---> Running in 23731a9046bf
Removing intermediate container 23731a9046bf
 ---> 496f527837b5
Successfully built 496f527837b5
Successfully tagged omertu/googlehomekodi:latest

**Comment by dynamiik** [comment]
Thanks a lot for your help. I whish you a happy new year or ä Guets Neues

**Comment by keydon** [comment]
thanks :d you too

**Comment by workino** [comment]
Hello, to solve the compiling issue I made 2 simple changes :

1) change in package-lock.json from line 454 to 456:
from:
```
Sorry I have no more the original 
```
to:
```
      "version": "0.1.14",
      "resolved": "https://registry.npmjs.org/deasync/-/deasync-0.1.14.tgz",
      "integrity": "sha512-wN8sIuEqIwyQh72AG7oY6YQODCxIp1eXzEZlZznBuwDF8Q03Tdy9QNp1BNZXeadXoklNrw+Ip1fch+KXo/+ASw==",
```
2) add in package.json under "dependencies":
```
"node-addon-api": "*"
```
remeber to place a comma at the end of previous line.

**Comment by secret-liar** [comment]
Thanks @workino ! Works very well now :)
