### ISSUE TITLE
current build instructions fail

### ISSUE THREAD

**Issue by jarkastr** [OmerTu/GoogleHomeKodi#201]
I was able to build the docker image by following the instructions  a few weeks ago.  I had to wipe my kodi/docker server and it appears to not be working again.  I tried building on a raspberry pi zero and lubuntu  Below is the errors that i was getting on building it:

Step 8/12 : RUN npm install --production && npm cache clean --force
 ---> Running in 43988467bce7

> deasync@0.1.13 install /home/node/app/node_modules/deasync
> node ./build.js

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:160:21)
gyp ERR! System Linux 4.19.8
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/app/node_modules/deasync
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.13 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-02T21_26_19_293Z-debug.log

**Comment by keydon** [comment]
pls use the workaround of [#200](https://github.com/OmerTu/GoogleHomeKodi/issues/200#issuecomment-450763012) for now.

**Comment by jarkastr** [comment]
worked for me.  Thanks!
