### ISSUE TITLE
Problem Docker Build

### ISSUE THREAD

**Issue by Bassysta** [OmerTu/GoogleHomeKodi#203]
Hi.
I've done these steps:
```
curl -L -O https://github.com/OmerTu/GoogleHomeKodi/archive/master.tar.gz
tar xzf master.tar.gz
cd GoogleHomeKodi-master
docker build --tag omertu/googlehomekodi .
```

But at last this error appear:
```
Step 1/17 : FROM node:alpine as builder
Error parsing reference: "node:alpine as builder" is not a valid repository/tag: invalid reference format
```

Alreay tried this workaround
https://github.com/OmerTu/GoogleHomeKodi/issues/200
but nothing changed.

Tnk

**Comment by keydon** [comment]
Thats odd.
What operating system are you using?
Whats the output oft `docker info`

**Comment by Bassysta** [comment]
S.O.
LibreELEC (official): 8.2.5 (RPi2.arm)

--------

LibreELEC:~/GoogleHomeKodi-master # docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187d
runc version: 9df8b30
init version: 949e6fa
Kernel Version: 4.9.80
Operating System: LibreELEC (official): 8.2.5
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 751.5 MiB
Name: LibreELEC
ID: LNT4:UGDV:7TSD:L5XD:KTBR:DNUS:PGTZ:IQTN:W4WH:VP5B:PNOL:B36A
Docker Root Dir: /storage/.kodi/userdata/addon_data/service.system.docker/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by keydon** [comment]
Crap, I am using a multi stage build feature introduced in a later version of docker.

So you can either update to a newer libreelec RC build which ships with a recent docker version or you can wait for me to write an alternative dockerfile compatible with your version. Not sure how long that will take since I don't have access to a PC at the moment.

**Comment by Bassysta** [comment]
HI.
After Kodi Upgrade to version 9 all work well.
Tnk

**Comment by keydon** [comment]
I guess I am going to sit this one out :D

**Comment by keydon** [comment]
Since the new kodi version is already out, I am closing this :D
