### ISSUE TITLE
Configuration behind a reverse proxy like nginx

### ISSUE THREAD

**Issue by IIIdefconIII** [OmerTu/GoogleHomeKodi#204]
Hi this is not a real issue, but i couldnt find another way to contact you. Is there a guide to make this work with nginx or can i run this as seperate webserver next to it?
|
Many thanks

**Comment by keydon** [comment]
Search for it in the closed issues, I think there you will find an example configuration for running node behind a nginx reverse proxy.

**Comment by talondnb** [comment]
This works for me..

```
location /kodi/ {
    rewrite /kodi/(.*) /$1 break;
    proxy_pass http://192.168.0.22:8099;
    proxy_redirect http:// https://;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
}
```

**Comment by IIIdefconIII** [comment]
> This works for me..
> 
> ```
> location /kodi/ {
>     rewrite /kodi/(.*) /$1 break;
>     proxy_pass http://192.168.0.22:8099;
>     proxy_redirect http:// https://;
>     proxy_http_version 1.1;
>     proxy_set_header Host $host;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection $connection_upgrade;
> }
> ```
Thanks for that, could you tell me what method u used 1,2 or 3? im not sure how to connect it

**Comment by talondnb** [comment]
I run LibreELEC with the Docker addon (and portainer). I’m using the sinedied docker build (https://hub.docker.com/r/sinedied/googlehomekodi).

**Comment by keydon** [comment]
timeout.
