### ISSUE TITLE
Problem with Glitch ECONNREFUSED 

### ISSUE THREAD

**Issue by Olivierr92500** [OmerTu/GoogleHomeKodi#206]
Dear All,

First of all, thank you for the work you've done. It looks really promising.
Sadly, I have not managed to make it work. I have tried to deploy it on Glitch (getting the source from GitHub and modifying then env file with the address/port information) but I always get the same message ECONNREFUSED  detailed below when trying the Glitch live.

I had to change the node version in package.json otherwise, the debugger would not even start:

  "engines": {
    "node": "10.x"
  },

Appart from that, my kodi can be reached from the outside (I can play/pause from outside my local network) and IFTTT gets the same "Unable to make web request: Error: ETIMEDOUT" which is normal since the Glitch node crashes.

Do you have any clue why I get this error?
Thank you for your help.
Kind regards
Olivier

---------------------
(node:18509) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1988   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)

(node:18509) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18509) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by keydon** [comment]
it seems you are trying to connect to `127.0.0.1:1988`?
127.0.0.1 is wrong and definitly not your external kodi IP

**Comment by Olivierr92500** [comment]
Hi Keydon,

Thank you. Yes 127.0.0.1 is definitely not my kodi IP. The right IP is set in my .env file in Glitch (I also tried to rename this .env in a kodiremote2.env but this does not change anything. Still the same error).

for me this localhost was more related to the glitch virtual machine having a problem but I do not know which one. I have no place in the code where I specify 127.0.01 and port 1988

**Comment by keydon** [comment]
well maybe its the glitch debugger. turn that off and revert the the package.json and test again.
post the console output here of the troubleshooting steps

**Comment by Olivierr92500** [comment]
Thanks again Keydon,
I finaly solved my problem by duplicating on Glitch an existing kodiremote project and adjusting it with my configuration.
I have not yet found out what differences exists between the 2 projects but it now works, integrated with IFTTT. I will complete this post once I have.
Thanks again you for help
