### ISSUE TITLE
On screen pop-up on error

### ISSUE THREAD

**Issue by shocam** [OmerTu/GoogleHomeKodi#207]
Hi
I have this working perfectly now, thanks for the help in getting it set up.
I was wondering if it is possible to have a pop-up appear in kodi screen if there is an error i.e. kodi play an episode of *whatever* - that are no unwatched episode of *whatever*?

**Comment by keydon** [comment]
yes, wanted to implement that for ages^^

**Comment by keydon** [comment]
its not too difficult. just need to find some time and ensure an error while producing the error-popup does not start an infinite loop ;O
