### ISSUE TITLE
Listen on specific IP

### ISSUE THREAD

**Issue by calisro** [OmerTu/GoogleHomeKodi#209]
Is there a way to have the server only listen on a specific IP?  In this case I want it only on loopback because I use a reverse proxy and don't need it exposed on the external machine IP outside of the proxy.

**Comment by keydon** [comment]
you could replace the last lines in your `server.js`
```js
const listener = app.listen(config.globalConf.listenerPort, () => {
    console.log(`Your app is listening on port ${listener.address().port}`);
});
```
with
```js
const listener = app.listen(config.globalConf.listenerPort, "YOUR.TARGET.IP.FOR.BINDING", () => {
    console.log(`Your app is listening on port ${listener.address().port}`);
});
```

**Comment by calisro** [comment]
Perfect!  Thank you!
