### ISSUE TITLE
Switching to a TV Channel doesn't work for me

### ISSUE THREAD

**Issue by mathojojo** [OmerTu/GoogleHomeKodi#21]
Hi,

I set every commands on IFTTT, but some are not working. It's the case for PLAYPVRCHANNELBYNAME and PLAYPVRCHANNELBYNUMBER.

When I tell the phrase, Google Home detect it, and answer correctly, but nothing happens on Kodi.
Others commands like Stop, mute, pause or playmovie work.

Here are the logs :

```
Request token = rockeurs

Authentication succeeded

PVR channel request received to play "8"

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannelGroups","params":{"channeltype":"tv"}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":1}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":2}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":3}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":4}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":5}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":6}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":7}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":8}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":9}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":10}}

Command sent = {"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":11}}
```

I hope you can help me.
Thank you

(I imported your script today, so it's up to date)

**Comment by OmerTu** [comment]
I don't have PVR on my Kodi so I can't really test this.. could your try to put the following in your browser and past the result you get?  (try doing that with channelgroupid 1, 2, 3, ..., 11).
You need to replace the URL with your the IP and port of your Kodi device.

`http://KODI_INTERNAL_IP:KODI_PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"PVR.GetChannels","params":{"channelgroupid":1}}`

**Comment by mathojojo** [comment]
Thank you for your answer : this is the result channelgroupid 1 :

```
id | 1
-- | --
jsonrpc | "2.0"
result |  
channels |  
0 |  
channelid | 21
label | "TF1"
1 |  
channelid | 13
label | "France 2"
2 |  
channelid | 23
label | "F3 Lorraine"
3 |  
channelid | 17
label | "CANAL+"
4 |  
channelid | 7
label | "France 5"
5 |  
channelid | 26
label | "M6"
6 |  
channelid | 25
label | "Arte"
7 |  
channelid | 8
label | "C8"
8 |  
channelid | 18
label | "W9"
9 |  
channelid | 2
label | "TMC"
10 |  
channelid | 19
label | "NT1"
11 |  
channelid | 16
label | "NRJ12"
12 |  
channelid | 15
label | "LCP"
13 |  
channelid | 12
label | "France 4"
14 |  
channelid | 9
label | "BFM TV"
15 |  
channelid | 4
label | "CNEWS"
16 |  
channelid | 5
label | "CSTAR"
17 |  
channelid | 14
label | "Gulli"
18 |  
channelid | 24
label | "France Ô"
19 |  
channelid | 11
label | "HD1"
20 |  
channelid | 27
label | "L'Equipe 21"
21 |  
channelid | 10
label | "6ter"
22 |  
channelid | 22
label | "NUMERO 23"
23 |  
channelid | 6
label | "RMC Découverte"
24 |  
channelid | 1
label | "Chérie 25"
25 |  
channelid | 20
label | "LCI"
26 |  
channelid | 3
label | "franceinfo:"
limits |  
end | 27
start | 0
total | 27
```

**Comment by mathojojo** [comment]
channelgroupid 2

```
{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":21,"label":"TF1"},{"channelid":13,"label":"France 2"},{"channelid":23,"label":"F3 Lorraine"},{"channelid":17,"label":"CANAL+"},{"channelid":7,"label":"France 5"},{"channelid":26,"label":"M6"},{"channelid":25,"label":"Arte"},{"channelid":8,"label":"C8"},{"channelid":18,"label":"W9"},{"channelid":2,"label":"TMC"},{"channelid":19,"label":"NT1"},{"channelid":16,"label":"NRJ12"},{"channelid":15,"label":"LCP"},{"channelid":12,"label":"France 4"},{"channelid":9,"label":"BFM TV"},{"channelid":4,"label":"CNEWS"},{"channelid":5,"label":"CSTAR"},{"channelid":14,"label":"Gulli"},{"channelid":24,"label":"France Ô"},{"channelid":11,"label":"HD1"},{"channelid":27,"label":"L'Equipe 21"},{"channelid":10,"label":"6ter"},{"channelid":22,"label":"NUMERO 23"},{"channelid":6,"label":"RMC Découverte"},{"channelid":1,"label":"Chérie 25"},{"channelid":20,"label":"LCI"},{"channelid":3,"label":"franceinfo:"}],"limits":{"end":27,"start":0,"total":27}}}
```

**Comment by mathojojo** [comment]
channelgroupid 3

`
{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":21,"label":"TF1"},{"channelid":17,"label":"CANAL+"},{"channelid":7,"label":"France 5"},{"channelid":26,"label":"M6"},{"channelid":25,"label":"Arte"},{"channelid":8,"label":"C8"},{"channelid":18,"label":"W9"},{"channelid":2,"label":"TMC"},{"channelid":19,"label":"NT1"},{"channelid":16,"label":"NRJ12"},{"channelid":15,"label":"LCP"},{"channelid":9,"label":"BFM TV"},{"channelid":4,"label":"CNEWS"},{"channelid":5,"label":"CSTAR"},{"channelid":14,"label":"Gulli"},{"channelid":11,"label":"HD1"},{"channelid":27,"label":"L'Equipe 21"},{"channelid":10,"label":"6ter"},{"channelid":22,"label":"NUMERO 23"},{"channelid":6,"label":"RMC Découverte"},{"channelid":1,"label":"Chérie 25"}],"limits":{"end":21,"start":0,"total":21}}}
`

**Comment by mathojojo** [comment]
channelgroupid 4
`
{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":11,"label":"HD1"},{"channelid":27,"label":"L'Equipe 21"},{"channelid":22,"label":"NUMERO 23"},{"channelid":6,"label":"RMC Découverte"},{"channelid":1,"label":"Chérie 25"}],"limits":{"end":5,"start":0,"total":5}}}`

**Comment by mathojojo** [comment]
channelgroupid 5
`{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":13,"label":"France 2"},{"channelid":23,"label":"F3 Lorraine"},{"channelid":12,"label":"France 4"},{"channelid":24,"label":"France Ô"},{"channelid":20,"label":"LCI"},{"channelid":3,"label":"franceinfo:"}],"limits":{"end":6,"start":0,"total":6}}}`

**Comment by mathojojo** [comment]
channelgroupid 6
`{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":17,"label":"CANAL+"},{"channelid":20,"label":"LCI"}],"limits":{"end":2,"start":0,"total":2}}}`

**Comment by mathojojo** [comment]
channelgroupid 7
`{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":13,"label":"France 2"},{"channelid":12,"label":"France 4"},{"channelid":24,"label":"France Ô"},{"channelid":3,"label":"franceinfo:"}],"limits":{"end":4,"start":0,"total":4}}}`

**Comment by mathojojo** [comment]
channelgroupid 8
`{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":8,"label":"C8"},{"channelid":9,"label":"BFM TV"},{"channelid":4,"label":"CNEWS"},{"channelid":5,"label":"CSTAR"},{"channelid":14,"label":"Gulli"}],"limits":{"end":5,"start":0,"total":5}}}`

**Comment by mathojojo** [comment]
channelgroupid 9
`{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":7,"label":"France 5"},{"channelid":26,"label":"M6"},{"channelid":25,"label":"Arte"},{"channelid":18,"label":"W9"},{"channelid":10,"label":"6ter"}],"limits":{"end":5,"start":0,"total":5}}}`

**Comment by mathojojo** [comment]
channelgroupid 10
`{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":21,"label":"TF1"},{"channelid":2,"label":"TMC"},{"channelid":19,"label":"NT1"},{"channelid":16,"label":"NRJ12"},{"channelid":15,"label":"LCP"}],"limits":{"end":5,"start":0,"total":5}}}`

**Comment by mathojojo** [comment]
channelgroupid 11
`{"id":1,"jsonrpc":"2.0","result":{"channels":[{"channelid":23,"label":"F3 Lorraine"}],"limits":{"end":1,"start":0,"total":1}}}`

**Comment by Andulien** [comment]
Hey there, did you get it to work? I have the same problem. It does not work with the numbers as the search result in line 393 always returns empty :(

**Comment by p0psicles** [comment]
Fixed in develop branch.

**Comment by keydon** [comment]
dev branch was merged into master in the meantime. So i consider this issue closed. Please open another if the problem still persists.
