### ISSUE TITLE
Path kodi-hosts.config.js Docker

### ISSUE THREAD

**Issue by dgarciadonado** [OmerTu/GoogleHomeKodi#210]
Hello,
I have set up my local server on a raspberry pi 3 with debian using Docker. I used the method with environment variables.
Now I want to edit the kodi-hosts.config.js in order to add this line: "process.env['ACTIVATE_TV'] = 'true';" for change input on TV. I don't know the path where it is located. Do you know where to find it?
Thank you

**Comment by keydon** [comment]
dont mix the two methods of configuration. its either file-based or environment variables.

just set the environment variable `ACTIVATE_TV` to `true`

**Comment by dgarciadonado** [comment]
Thank you!! It works perfect
