### ISSUE TITLE
local node.js server Deprecation warning ... have no idea how to fix.

### ISSUE THREAD

**Issue by mwink4689** [OmerTu/GoogleHomeKodi#211]
When I open the nod.js server I get the following message in the command prompt:

(node:9824) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Your app is listening on port 8099"

This message has just recently popped up. Up until now, it has been working perfectly.  I am a newbie at this and have no idea how to fix this error and I can't seem to find an answer on the web that I can understand. Any help you can provide would be greatly appreciated.

**Comment by keydon** [comment]
this warning is just a warning. it does not affect the functionality in any way.
your problem (whatever it is or how it might present) is something else^^

**Comment by mwink4689** [comment]
Many thanks!
