### ISSUE TITLE
Server.js won`t run

### ISSUE THREAD

**Issue by dublowduck** [OmerTu/GoogleHomeKodi#214]
Server.js won`t run, it brings up a dialogue that says;
![untitled](https://user-images.githubusercontent.com/47789156/53698485-53840480-3dd5-11e9-986d-e6df2ec581af.png)

Script: C:\node\GoogleHomeKodi\server.js
Line: 6
Char: 1
Error: Syntax error
Code: 800A03EA
Source: Microsoft JScript compilation error

So if anyone knows how to fix I`d be very grateful :)

**Comment by keydon** [comment]
I guess you overread step 9 of the B2 szenario.

> 9. You should now be able to start the node server by running: `node server.js.`

Hope this is the only step you skipped :d

**Comment by dublowduck** [comment]
Oh yea, didn't notice that! Thanks, but do you know what it means?

**Comment by keydon** [comment]
it means you need to open up a command-line window at the location your app lives and type that command into it.

**Comment by dublowduck** [comment]
AHH, wonderful, I should have thought of that. That helps me out of an issue I've been having for the past few hours, thank you very much :)
