### ISSUE TITLE
It won't work at all

### ISSUE THREAD

**Issue by Alarmed1** [OmerTu/GoogleHomeKodi#215]
I can't seem to get it to work. I tried to pause kodi with a browser. I get this message:
```
{
  "error":{
    "code":-32099,
    "message":"Bad client permission."
  },
  "id":1,
  "jsonrpc":"2.0"
}
```
I've gone over step a multiple times. I'm sure it's set right.

**Comment by keydon** [comment]
sorry, this part of the documentation is out of date. the kodi devs changed some stuff.
"writing" kodi-requests are no longer accessible through this easy browser-test.
you can either ignore that this fails and move on with the next troubleshooting steps. Or use this test instead:
`http://KODI_HOST:PORT/jsonrpc?request={"jsonrpc": "2.0", "method": "Application.GetProperties", "params": {"properties": ["volume"]}, "id": 1}`
This should return the current volume set.

**Comment by Alarmed1** [comment]
Hello. That works. Step two and three works. Step four gives me "Executing request: /koditestconnection Forbidden {"message": "403 - Forbidden", "name":ResponseException", "status": 403, "statusText": "403 - Forbidden"}  I've checked and double checked. Everything seems fine. Any ideas?

**Comment by Alarmed1** [comment]
Also, when I install Docker, it breaks Samba. I can no longer access Kodi/Libreelec from the LAN. Any ideas on that?

**Comment by keydon** [comment]
is docker your hosting szenario then?
403 Forbidden sounds like an auth_token issue.
Is the token you put on the web UI the same you configured? how are you configuring? Environment or config-file? leave out special characters for the purpose of testing.

**Comment by Alarmed1** [comment]
Yes I'm using docker on libreelec.
Yes the token is the same.
I tried configuring it both ways.
Now I get an error on step two of troubleshooting. So I try to uninstall docker with docker rm --force omertu/googlehomekodi and it says Error: No such container: omertu/googlehomekodi.
Also, I used an online port checker and it says port 8099 is closed, even though I have it open on my router.

**Comment by keydon** [comment]
Step 2 is **not** for your hosting szenario! Does Step 3 work?
You are confusing removing a container and removing an image.
If you followed our instructions your image is named `omertu/googlehomekodi` and your container is named `googlehomekodi`.
You can remove the image with `docker rmi -f omertu/googlehomekodi`
You can remove the container with `docker rm -f googlehomekodi`

Maybe rebuild the image with my latest updates, if it is ineed a token mismatch it should say so now in the error message. Also I could offer taking a look at your setup via teamviewer, if thats comfortable with you.

**Comment by Alarmed1** [comment]
Hello. I'm almost there. I was able to remove and reinstall the image and container, I have both ports open, and have made it to step 6. 

When I try it out, Ifttt gives me: Unable to make web request: Error: connect ECONNREFUSED

I don't mind using Team Viewer.

Thanks for your help.

**Comment by keydon** [comment]
great you got it all up and running :)

> P.S. Are there already made applets on Ifttt or somewhere on the internet?
Nope there is not :(
