### ISSUE TITLE
Library Clean Up option (suggestion)

### ISSUE THREAD

**Issue by secret-liar** [OmerTu/GoogleHomeKodi#216]
Hi,

Thanks a lot for you work! I use is mostly to pause videos when I go in the kitchen and forget to press the button :P

I like the "Scan library" option but I wonder if you could add a "Clean library" option? I find this option too hiden in Kodi and be able to ask Google assistant to do it would be amazing!

**Comment by keydon** [comment]
sure, easy fix.
