### ISSUE TITLE
Cant get glitch working

### ISSUE THREAD

**Issue by boogieworld** [OmerTu/GoogleHomeKodi#217]
When i import the github in Glitch i dont get a env file and i get a error so i cant go live with the project..

**Comment by keydon** [comment]
did the project even get imported correctly? I am currently getting an error there, maybe it is a temporary issue.

**Comment by boogieworld** [comment]
Yeah I hope so!

**Comment by boogieworld** [comment]
I hope they will fix it soon!

**Comment by adelbentakouka** [comment]
I have the same error

**Comment by Clubeddie** [comment]
Don 't know if this is the same error, but when i follow the steps on glitch i have a first issue with this step

> Create a new Glitch project and under advance settings choose Import from GitHub
I can only choose new project and then ### clone from Git Repo.

It looks like me that this is not the same.  I cant get it working either
For example, share make private is no option.

**Comment by jaaxx** [comment]
There does seem to be missing .env and some type of syntax errors, but even if those are fixed the code will need to be modified for Kodi Leia API changes.  json requests no longer work with GET only POST
See -> https://github.com/xbmc/xbmc/pull/12281

**Comment by keydon** [comment]
confirmed, glitch changed some things how new projects can be imported.

But now just clicking this link should work, please give it a try:
https://glitch.com/edit/#!/remix/clone-from-repo?REPO_URL=https://github.com/OmerTu/GoogleHomeKodi.git

**Comment by boogieworld** [comment]
Hi man!

The link doenst work either! Because when i click the link a new project is being made but when it is done there are no files in the project

**Comment by awilcockson** [comment]
confirmed the glitch setup steps (tried the link above as well) is broken for me as well. End up with an empty project, with no files to edit.

**Comment by keydon** [comment]
No idea, works for me. Maybe provide some screenshots what it looks like, after clicking the link from April 3rd.

**Comment by pranshr** [comment]
The link works but there is no env file.

**Comment by pranshr** [comment]
The file isnt there in GitHub repo itself.

**Comment by keydon** [comment]
Well glitch usually adds this file. 
If it is missing in your case, just click `Add File` and type `.env` as the file name and be happy...

**Comment by keydon** [comment]
@awilcockson had that once to, did you try a couple more times?

**Comment by pranshr** [comment]
Thanks for the reply,
It works now
Appreciate the help.

*from PranShr  *
*:-)*
