### ISSUE TITLE
Apparently not passing correct http requests

### ISSUE THREAD

**Issue by jaaxx** [OmerTu/GoogleHomeKodi#220]
I haven't used this code in many, many revisions, but it no longer works for me on Glitch.  I get timeout errors with every command.

Setup on my end is working, verified by sending json requests via curl from outside the network.  The json part of the request in Glitch looks correct so I assume it is something with the kodi authentication/URL part of the request being sent.  Not sure how to see that.

When using curl the working URL part looks like http://USER:PASSWORD@IPADDY:PORT

**Comment by jaaxx** [comment]
Setup a local server and everything works correctly.  Seems like a Glitch issue, maybe Glitch is mangling the request?

**Comment by keydon** [comment]
post the console output from glitch from my newest master version.
the kodi-rpc url should now be found in the glitch logs when executing a request.

**Comment by jaaxx** [comment]
I cannot for the life of me get any output from console.  The log does show my correct IP and the json body appears as expected, but I don't see where it is passing the user and password for Kodi.

I have the code up and running great on my server at home, but I would like to use glitch to slim down the load here.

**Comment by keydon** [comment]
post the output of the log then, mask the last part of the ip if you prefer.
Its ok, that the kodi user and password are not logged, thats expected.

**Comment by jaaxx** [comment]
Sorry for the delay.  Here's the log after sending command which returns 504 Gateway Timeout.

Loaded config from .env (environment)

🍢🚜 Your app is listening on port 3000


Authentication succeeded

Sending command to kodi http://24.30.*.*:9091/jsonrpc:

{

  "jsonrpc": "2.0",

  "id": 1,

  "method": "GUI.ShowNotification",

  "params": {

    "title": "GoogleHomeKodi",

    "message": "Test Successful!",

    "image": "info"

  }

**Comment by jaaxx** [comment]
`request failed

route:  /koditestconnection

query:  {}

error:  { FetchError: request to http://24.30.*.*:9091/jsonrpc failed, reason: connect ETIMEDOUT 24.30.*.*::9091

    at ClientRequest.<anonymous> (/rbd/pnpm-volume/67f1aa16-dd22-4351-9301-8b8a199ee401/node_modules/.registry.npmjs.org/node-fetch/1.7.3/node_modules/node-fetch/index.js:133:11)

    at emitOne (events.js:96:13)

    at ClientRequest.emit (events.js:188:7)

    at Socket.socketErrorListener (_http_client.js:324:9)

    at emitOne (events.js:96:13)

    at Socket.emit (events.js:188:7)

    at emitErrorNT (net.js:1290:8)

    at _combinedTickCallback (internal/process/next_tick.js:80:11)

    at process._tickCallback (internal/process/next_tick.js:104:9)

  name: 'FetchError',

  message: 'request to http://24.30.*.*::9091/jsonrpc failed, reason: connect ETIMEDOUT 24.30.*.*::9091',

  type: 'system',

  errno: 'ETIMEDOUT',

  code: 'ETIMEDOUT' }

body:  { token: 'slayme01' }

Sending command to kodi http://24.30.20.182:9091/jsonrpc:

{

  "jsonrpc": "2.0",

  "id": 1,

  "method": "GUI.ShowNotification",

  "params": {

    "title": "GoogleHomeKodi",

    "message": "undefined: request to http://24.30.20.182:9091/jsonrpc failed, reason: connect ETIMEDOUT 24.30.20.182request failed

route:  /koditestconnection

query:  {}

error:  { FetchError: request to http://24.30.20.182:9091/jsonrpc failed, reason: connect ETIMEDOUT 24.30.20.182:9091

    at ClientRequest.<anonymous> (/rbd/pnpm-volume/67f1aa16-dd22-4351-9301-8b8a199ee401/node_modules/.registry.npmjs.org/node-fetch/1.7.3/node_modules/node-fetch/index.js:133:11)

    at emitOne (events.js:96:13)

    at ClientRequest.emit (events.js:188:7)

    at Socket.socketErrorListener (_http_client.js:324:9)

    at emitOne (events.js:96:13)

    at Socket.emit (events.js:188:7)

    at emitErrorNT (net.js:1290:8)

    at _combinedTickCallback (internal/process/next_tick.js:80:11)

    at process._tickCallback (internal/process/next_tick.js:104:9)

  name: 'FetchError',

  message: 'request to http://24.30..*.*::9091/jsonrpc failed, reason: connect ETIMEDOUT 24.30..*.*::9091',

  type: 'system',

  errno: 'ETIMEDOUT',

  code: 'ETIMEDOUT' }

body:  { token: '*******' }

Sending command to kodi http://24.30.*.*:9091/jsonrpc:

{

  "jsonrpc": "2.0",

  "id": 1,

  "method": "GUI.ShowNotification",

  "params": {

    "title": "GoogleHomeKodi",

    "message": "undefined: request to http://24.30.*.*:9091/jsonrpc failed, reason: connect ETIMEDOUT 24.30.*.*:9091",

    "image": "error"

  }

}

(node:588) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to http://24.30.*.*:9091/jsonrpc failed, reason: connect ETIMEDOUT 24.30.*.*:9091:9091",

    "image": "error"

  }

}

(node:588) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to http://24.30.*.*:9091/jsonrpc failed, reason: connect ETIMEDOUT 24.30.*.*:9091`

**Comment by keydon** [comment]
Logs look good to me.
IP looks like your actual external IP, thats good.
Port looks a little weird, you actually changed it 9091?
I would bet on a port-forwarding issue, but if you say you testet it successfully from outside of your network I have no idea.

**Comment by jaaxx** [comment]
9091 is the outside port assignment in the forwarding rule which translates to 8080 locally.  Maybe that's the issue?  Do I need to have the web facing port be the same as the internal kodi port?

For now I have the code running on my local server with zero problems.
