### ISSUE TITLE
Shutdown does not work

### ISSUE THREAD

**Issue by SeyedMahmoudian** [OmerTu/GoogleHomeKodi#223]
I have to been trying to use the standby but it will not work, I can turn on the tv but can not turn it off.  when I run the command on glitch I get his:
```
Executing request: /standbytv
OK
```
when running the following :
`http://192.168.0.10:8080/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22method%22:%22Application.GetProperties%22,%22params%22:{%22properties%22:[%22standby%22]},%22id%22:1}`

I get the following : 
```
{
	"error": {
		"code": -32602,
		"data": {
			"method": "Application.GetProperties",
			"stack": {
				"message": "array element at index 0 does not match",
				"name": "properties",
				"property": {
					"message": "Received value does not match any of the defined enum values",
					"name": "Application.Property.Name",
					"type": "string"
				},
				"type": "array"
			}
		},
		"message": "Invalid params."
	},
	"id": 1,
	"jsonrpc": "2.0"
}
```

**Comment by keydon** [comment]
Works for me.
Did you install the kodi-addon `script.json-cec` for this to work like described in the readme?

**Comment by keydon** [comment]
timeout -> closed.
