### ISSUE TITLE
possible youtube selection like chromecast?

### ISSUE THREAD

**Issue by Brad3rs** [OmerTu/GoogleHomeKodi#224]
Thanks for the excellent work done on this project, i have it implemented on 3 pi's with libreelec, with 2 google home minis. everything works flawlessly with docker with multiple instances.
my only request would be... if i ask google home for something on youtube ie "an old john wayne western" i get an old john wayne western (whatever it gives me), that's ok and really impressive but i'd like to have a menu like the chromecast gives me, where it shows me choices and lets me say..."show more" or say a number to select the one i want. 
it would be wonderful if that ever gets implemented.
Thanks again for the hard work, it really works well, even my five year old daughter uses this everyday to search and play off YouTube :)
here is a link to an image and article of the chromecast youtube selection menu....
https://9to5google.com/2018/02/22/google-home-youtube-chromecast-visualization/

**Comment by keydon** [comment]
added `/searchyoutube`
The best I can do :)

**Comment by Brad3rs** [comment]
Thanks 😀
