### ISSUE TITLE
youtube autoplay?

### ISSUE THREAD

**Issue by Brad3rs** [OmerTu/GoogleHomeKodi#228]
"Hey Google youtube [youtube title]" --> will search a youtube video, and play the first video.

works great but stops after the first video... so if i ask for danger mouse cartoons it gives me the same one and that's all and then stops, even if there are like 60 in the list. so unless i know the names of the others to ask for, i can't watch them.
we've been getting around it by asking for compilations but would be nice if it just played the next video.
i have set the youtube addon to autoplay but that doesn't help... is it possible to add an autoplay feature?
thanks again for the excellent work on this project :)

**Comment by keydon** [comment]
default behaviour if the `/playyoutube` endpoint adjusted.
it now plays the first 15 results as a playlist.
if you wish more than 15, just add i.e. `&max=100` to the url for 100 items.

**Comment by Brad3rs** [comment]
Thank you :)
