### ISSUE TITLE
Something's not working

### ISSUE THREAD

**Issue by pedroesdrubal** [OmerTu/GoogleHomeKodi#232]
Was trying to get this to my newly bought Google home mini. I've been able to do all the steps And I have been able to test this:
`http://YOUR_EXTERNAL_KODI_IP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}` and got to pause the video.
And this:
`http://YOUR_EXTERNAL_IP:PORT/jsonrpc?request={"jsonrpc":"2.0","method":"Application.GetProperties","params":{"properties":["volume"]},"id":1}` and got the volume result.
Both got prompt user and pass as well.

Somehow this works and the connection seems ok, Google home responds to my commands but nothing happens on kodi.

When I open my NODE on a browser, to test /koditestconnection, I got, Executing request: /koditestconnection, a loading circle, but nothing more happens, and after a while, only get 502 Bad Gateway, is that normal?

Checked applet on IFTTT and the settings match. now I'm checking glitch again, and the logs show this:
```
Authentication succeeded
Sending command to kodi http://192.168.MY IP AND PORT/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "GUI.ShowNotification",
  "params": {
    "title": "MY TITLE",
    "message": "Test Successful!",
    "image": "info"
  }
}
request failed

route:  /koditestconnection
query:  {}
error:  { FetchError: request to http://192.168.MY IP AND PORT/jsonrpc failed, reason: connect ETIMEDOUT 192.168.MY IP AND PORT
    at ClientRequest.<anonymous> (/rbd/pnpm-volume/c763e3e3-0a15-45ce-8d5a-466a1e2efee8/node_modules/.registry.npmjs.org/node-fetch/1.7.3/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to http://192.168.MY IP AND PORT/jsonrpc failed, reason: connect ETIMEDOUT 192.168.MY IP AND PORT',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
body:  { token: 'MY TOKEN NAME' }

Sending command to kodi http://192.168.MY IP AND PORT/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "GUI.ShowNotification",
  "params": {
    "title": "MY TITLE",
    "message": "undefined: request to http://192.168.MY IP AND PORT/jsonrpc failed, reason: connect ETIMEDOUT 192.168.MY IP AND PORT",
    "image": "error"
  }
}
```
Would really appreciate anyone's help!

**Comment by keydon** [comment]
Well, since you are masking the IP beginning with `192.168` I guess you honstely think that this is your external IP. But its not and thats what is the problem. Glitch needs your external IP in order to be able to reach your kodi. Check http://whatismyip.com to get your external IP

**Comment by pedroesdrubal** [comment]
I'm using Kodi on a Rasp Pi, OpenELEC, and I don't have other IP than the one mentioned. (as far as I know of course...)
Also, as I said, when I execute
http://YOUR_EXTERNAL_KODI_IP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}
I use that same IP and it works and executes on Kodi.

**Comment by keydon** [comment]
Check http://whatismyip.com to get your external IP

**Comment by pedroesdrubal** [comment]
I did.
Do I need just to put it on the .env file?

**Comment by keydon** [comment]
you could do that yes. but it is strongly recommended to setup a dynDNS service of your choice. (i.e. selfhost.me)
since usually public ips change every 24h hours.
but just to get things working, your could put the plain ip into the .env file

**Comment by keydon** [comment]
your next step would be to setup portforwarding at your router from the router and the port your put in glitch to the openelec/raspi internal ip and port.

**Comment by pedroesdrubal** [comment]
Thank you.
Now the problems seems to be with that since I'm not able to execute this command anymore: http://YOUR_EXTERNAL_KODI_IP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}

Not sure how I should set the router settings for this...

**Comment by pedroesdrubal** [comment]
Well. Now it's working again, that command on browser I mean.
although it is still not working, the voice commands.

**Comment by pedroesdrubal** [comment]
request failed

route:  /koditestconnection

query:  {}

error:  { FetchError: request to http://178.166.MY IP AND PORT/jsonrpc failed, reason: connect ETIMEDOUT 178.166.MY IP AND PORT

    at ClientRequest.<anonymous> (/rbd/pnpm-volume/d515be29-1a64-4586-a52e-30caa7953b74/node_modules/.registry.npmjs.org/node-fetch/1.7.3/node_modules/node-fetch/index.js:133:11)

    at ClientRequest.emit (events.js:189:13)

    at Socket.socketErrorListener (_http_client.js:392:9)

    at Socket.emit (events.js:189:13)

    at emitErrorNT (internal/streams/destroy.js:82:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)

    at process._tickCallback (internal/process/next_tick.js:63:19)

  name: 'FetchError',

  message:

   'request to http://178.166.MY IP AND PORT/jsonrpc failed, reason: connect ETIMEDOUT 178.166.MY IP AND PORT',

  type: 'system',

  errno: 'ETIMEDOUT',

  code: 'ETIMEDOUT' }

body:  { token: 'MY TOKEN' }

Sending command to kodi http://178.166.MY IP AND PORT/jsonrpc:

{

  "jsonrpc": "2.0",

  "id": 1,

  "method": "GUI.ShowNotification",

  "params": {

    "title": "MY TITLE",

    "message": "undefined: request to http://178.166.MY IP AND PORT/jsonrpc failed, reason: connect ETIMEDOUT 178.166.MY IP AND PORT",

    "image": "error"

  }

}

**Comment by pedroesdrubal** [comment]
This is now the error. I beleive it's the same as before, even with the external IP

**Comment by keydon** [comment]
yes, because the port forwaring on your router is not yet set up I assume^^

**Comment by BaroOn5** [comment]
What i see ist that you configured the ip "http://178.166.MY IP AND PORT"...

**Comment by pedroesdrubal** [comment]
probably. Huawei router and instructions on internet are not clear.
Also I'm not an expert in this, so it's good mix to things not working xD
Can you please tell me exatcly what I have to forward to?

**Comment by keydon** [comment]
there are many many different routers out there, you will have to figure that one out by yourself.
You just have somwhere to tell the router, that every incoming request on port X is going to be forwared to the inter ip of your raspberrypi ie. 192.168.Y to the port Z. X and Z can be that same, but dont have to be. protocol is TCP if your router asks that^^

**Comment by BaroOn5** [comment]
> there are many many different routers out there, you will have to figure that one out by yourself.
> You just have somwhere to tell the router, that every incoming request on port X is going to be forwared to the inter ip of your raspberrypi ie. 192.168.Y to the port Z. X and Z can be that same, but dont have to be. protocol is TCP if your router asks that^^

Dont you think his problems are much more basic? If you look at the error?

**Comment by keydon** [comment]
> Dont you think his problems are much more basic? If you look at the error?
the error is a connection timeout! dont get confused by him masking his IP and Port

**Comment by BaroOn5** [comment]
> > Dont you think his problems are much more basic? If you look at the error?
> 
> the error is a connection timeout! dont get confused by him masking his IP and Port

Damn im retarded.... thank you for pointing that out :-D

**Comment by pedroesdrubal** [comment]
Well, this is what I have. I tried almost everything by now...
![router config](https://user-images.githubusercontent.com/54210261/63215893-1910e880-c125-11e9-8b44-4d312effe5d7.JPG)

**Comment by keydon** [comment]
doesnst look that bad, leave "external source ip address" empty. they mean something else there.

**Comment by pedroesdrubal** [comment]
Yes I've tried that as well

**Comment by keydon** [comment]
my rounter needs ~30s to apply changes. maybe yours needs a moment too.

**Comment by keydon** [comment]
the error you get in the glitch logs is still exactly the same?

**Comment by pedroesdrubal** [comment]
omg, just now, seems to be working! tech is really amazing. xD
Did nothing different, but somehow it's working..

**Comment by keydon** [comment]
glad you got it working, good job!

**Comment by pedroesdrubal** [comment]
Yes, finally. One last question, I've done this over wi fi. Can I connect my my rasp pi via ethernet and do it as well?

**Comment by keydon** [comment]
Sure. Works the same way.
