### ISSUE TITLE
pause issue

### ISSUE THREAD

**Issue by Tyrian81** [OmerTu/GoogleHomeKodi#233]
when trying to pause , assistant is asking for a device ....
rest of actions work ?

**Comment by keydon** [comment]
google seems not to understand you properly.
check the voice logs what it understood and change your speech accordingly.

**Comment by keydon** [comment]
or the phrase you chose is too unspecific. Only `pause` is a reserved keyword for google and its partners. Or at least for devices which are integrated.
You need to chose something like `kodi pause`

**Comment by Tyrian81** [comment]
nope kodi pause not working in dutch language, seems reserved for devices in home app...

**Comment by Tyrian81** [comment]
keeps asking for a device to pause

**Comment by keydon** [comment]
did google really detect the phrase correctly?
check https://myactivity.google.com/item?restrict=vaa&utm_source=udc&utm_medium=r for that

**Comment by keydon** [comment]
alternatively choose something completely different, like: "the rabbit eats carrots" :P

**Comment by keydon** [comment]
timeout.
