### ISSUE TITLE
Need help adding dutch to the broker languages

### ISSUE THREAD

**Issue by Tyrian81** [OmerTu/GoogleHomeKodi#238]
I get an error in kodi when using broker

![broker](https://user-images.githubusercontent.com/31477524/64472374-97c5d800-d15d-11e9-872e-a2072cbeb365.jpg)

![ifttt](https://user-images.githubusercontent.com/31477524/64472376-9dbbb900-d15d-11e9-9d8b-500b45200329.jpg)

I translated the broker in dutch language .... so i give it dutch commands
what am I doing wrong

**Comment by keydon** [comment]
wel the error cannot get much more expressive than that.
It clearly says that it did not find a phrase matching "play the titanic" in `nl`.
Maybe post your `nl.json` aswell, so we can take a look.

**Comment by Tyrian81** [comment]
{
    "kodiPlayRandomMovie": "speel een willekeurige (?<genre>.+ )?movie( van het jaar (?<year>\\d+))?",
    "kodiPlayTvshow": "speel een aflevering van (?<q>.+)",
    "kodiPlayRecentEpisodeHandler": "speel een nieuwe aflevering",
    "kodiPlayEpisodeHandler": "speel (?<q>.+) aflevering (?<e>\\d+)",
    "kodiPlaySong": "play the song (?<q>.+)",
    "kodiPlayAlbum": "play the album (?<q>.+)",
    "kodiPlayArtist": "play the artist (?<q>.+)",
    "kodiPlayMusicByGenre": "play the music genre (?<q>.+)",
    "kodiPlayMovie:1": "play (?<q>.+) delay (?<delay>\\d+)",
    "kodiPlayMovie": "speel (?<q>.+)",
    "kodiResumeTvshow": "resume an episode of (?<q>.+)",
    "kodiResumeMovie": "resume (?<q>.+)",
    "kodiBingeWatchTvshow": "binge watch (?<q>.+)",
    "kodiPlayPause": "pauze",
    "kodiMuteToggle": "stil",
    "kodiStop": "stop",
    "kodiSetVolume": "volume (?<q>\\d+)",
    "kodiIncreaseVolume": "volume harder( by (?<q>\\d+))?",
    "kodiDecreaseVolume": "volume zachter( by (?<q>\\d+))?",
    "kodiPlayChannelByNumber": "switch to channel number (?<q>\\d+)",
    "kodiPlayChannelByName": "switch to (?<q>.+) channel",
    "kodiActivateTv": "activate",
    "kodiStandbyTv": "standby",
    "kodiShutdown": "afsluiten",
    "kodiHibernate": "hibernate",
    "kodiReboot": "reboot",
    "kodiSuspend": "suspend",
    "kodiShuffleEpisodeHandler": "shuffle (?<q>.+)",
    "kodiPlayYoutube": "youtube play (?<q>.+)",
    "kodiScanLibrary": "scan bibliotheek",
    "kodiCleanLibrary": "schoon bibliotheek",
    "kodiNavUp": "navigeer omhoog( (?<q>\\d+))?",
    "kodiNavDown": "navigeer omlaag( (?<q>\\d+))?",
    "kodiNavLeft": "navigeer links( (?<q>\\d+))?",
    "kodiNavRight": "navigeer rechts( (?<q>\\d+))?",
    "kodiNavSelect": "select",
    "kodiNavContextMenu": "show context menu",
    "kodiNavHome": "go home",
    "kodiDisplayInfo": "wat speelt er",
    "kodiShowMovieGenre": "bekijk movie genre (?<q>.+)",
    "kodiShowWindow": "show (?<q>.+)",
    "kodiExecuteAddon": "execute addon (?<q>.+)",
    "kodiSetSubs": "ondertitel (?<q>.+)",
    "kodiSetSubsDirect": "subtitles direct select (?<q>\\d+)",
    "kodiSetAudio": "audio stream (?<q>.+)",
    "kodiSetAudioDirect": "audio stream direct select (?<q>\\d+)",
    "kodiSeekForwardMinutes": "seek forward( (?<q>\\d+) minutes)?",
    "kodiSeekBackwardMinutes": "seek backward( (?<q>\\d+) minutes)?",
    "kodiSeektominutes": "seek to (?<q>\\d+) minutes",
    "playercontrol": "playlist (?<q>.+)",
    "kodiTogglePartymode": "toggle party mode",
    "kodiOpenFavourite": "open (?<q>.+) from my favourites",
    "kodiToggleFullscreen": "toggle fullscreen",
    "kodiLoadProfile": "load profile (?<q>.+)"
}


I did not do a full translate yet , only most used commands :)

**Comment by keydon** [comment]
so as far as I can see, you translated the phrase that usually would match `play the titanic`.
You changed it from originally `play (?<q>.+)` to `speel (?.+)` (I hope the `<q>` only got lost in copy&pasteing here)
So you should try saying `speel the titanic`

**Comment by bokkoman** [comment]
I have the same problem.
When using the english broker it works, but when using the translated one it doesn't. 
The command I give is correct and sends it to kodi, but it gives an error.
It says it's an unknown phrase. So apparently the translated command (dutch phrase) does not connect to the command or something.

**Comment by keydon** [comment]
oh wasnt aware of that IFTTT limitation. Sadly you are out of luck then :(

**Comment by keydon** [comment]
closing this, since we cannot fix that.
