### ISSUE TITLE
Playing a new episode : "of" is said twice in google response 

### ISSUE THREAD

**Issue by tchirou** [OmerTu/GoogleHomeKodi#24]
Hello
I have set up everything and launching a movie and an episode works. Many thanks for your work, this is awesome.
But the response from Google home for an episode is "ok, playing a new episode of of $" instead of "playing a new episode of $". So I had to write "playing a new episode $".
I don't know if this a problem on your end and it is not a big deal but if you can clean it, it would be great and heal my OCD 😅
Many thanks

**Comment by PrSinister** [comment]
Mine is setup like so and it works fine:

"OK. Playing unwatched episode of $ in the living room"
and
"OK. Playing $ episode # in the living room"

I have a Google Home in the bedroom and one in the Living room so that's why i specify where it's playing...

**Comment by tchirou** [comment]
Well I tried with 2 different tv shows and both times in French and English and both times I had "of of" and "de de".
Like I said, it is not a big deal as I have found the workaround but maybe others would pull their hair like me trying to understand what is happening (if someone else than me has the problem though)
Thanks for your feedback

**Comment by Q-efx** [comment]
I think the added of comes from Google or ifttt. If I ask for: play an episode of x. It will query the command as: play an episode of of x. 

Which will fail because there is  no series called "of x" :)
