### ISSUE TITLE
Cant get Google Home working

### ISSUE THREAD

**Issue by reinisr** [OmerTu/GoogleHomeKodi#240]
Hello, thanks for the great app. Im using self-hosted docker image. Google assistant on the iphone works just fine, but google home dont understand Kodi commands. Both devices use the same Google account. 
Could you please point me to right direction solving this?
Thanks much!

**Comment by keydon** [comment]
check out https://myactivity.google.com/item?restrict=vaa&utm_source=udc&utm_medium=r
to verifiy google home understood what you expect it to understand.
same language settings on iphone and google home?

**Comment by reinisr** [comment]
thanks for replay. Indeed, google home did not understand the kodi context and was trying to play movie on Netflix instead. Thanks, issue resolved.
