### ISSUE TITLE
Installing on Synology Docker

### ISSUE THREAD

**Issue by bokkoman** [OmerTu/GoogleHomeKodi#241]
I'm trying to install the docker image on my synology.
But it keeps restarting the image.
When I launch the image I set the folder /config to my local /docker/googlehomekodi folder, which contains all the files (from github).

But whatever I try, it keeps restarting. So what am I doing wrong?

**Comment by reinisr** [comment]
Hello, you should:
1. Stop the container.
2. Delete folder /docker/googlehomekodi, you dont need it
3. Right click and Edit settings.
4. Remove /config folder from tab "Volumes"
----
Go to your Kodi app, go to Settings > Services > Web server
Set Allow remote contorl via HTTP to On
Choose a port number (e.g. 8080). We will refer to that port as YOUR_KODI_PORT
Choose a username and password (Important!). We will refer to those values as YOUR_KODI_USER_NAME and YOUR_KODI_PASSWORD

b) In a tab "Environment" create following variables:
KODI_USER with value of previously set kodi username
KODI_PASSWORD with value of previously set kodi username
KODI_PORT with value of previously set kodi port (e.g. 8080 in example)
KODI_IP with value of your kodi instance IP address (e.g. somethling like 192.168.0.xxx)
KODI_PROTOCOL with value of http
AUTH_TOKEN:
use https://passwordsgenerator.net/ to generate long (e.g. 32 symbols) password and paste it in the value of AUTH_TOKEN. This is going to be your API key.

Start container and follow instructions on setting https://ifttt.com

**Comment by bokkoman** [comment]
Thanks. I just got it working. 
But I did use the volume assignment. So now it uses the kodi-hosts config file. 

Now im trying to setup the broker. Haven't figured that out yet.

**Comment by bokkoman** [comment]
I have problems with the broker. It cannot find the nl.json. Though I uploaded it to the /broker folder in my mounted folder (/docker/googlehomekodi set to /config). I know that the mounted folder works, cause it is using my kodi-hosts file with the correct settings and token.

What am I doing wrong here?

**Comment by keydon** [comment]
our curent docker image is not designed to allow adding own broker languages.
but you could try adding a second mount to `/home/node/app/broker/` containing your `nl.json`

**Comment by bokkoman** [comment]
> our current docker image is not designed to allow adding own broker languages.
> but you could try adding a second mount to `/home/node/app/broker/` containing your `nl.json`

Thanks! that seems to work. But now I have problems that it gives errors: unknown phrases. 
I posted that in the other issue topic with the exact same problem.

**Comment by keydon** [comment]
Closing this issue, since the original issue is solved.
