### ISSUE TITLE
All Tests Working But Kodi Not Controlled Yet

### ISSUE THREAD

**Issue by captainfearless** [OmerTu/GoogleHomeKodi#242]
Hi, chosen hosting scenario B.1, set up with Cortana.

[console.txt](https://github.com/OmerTu/GoogleHomeKodi/files/3642221/console.txt)

https://xxxxxxxxxxxxx.glitch.me/playmovie?q={{TextField}}

{"token":"xxxxxxxx"}

Feels like i‘m close to success having passed all tests!

Is it to do with my json body and url boxes not having <<?, got confused by this.

Paul

**Comment by keydon** [comment]
what is the error?

**Comment by captainfearless** [comment]
When I ask Cortana to play movie or pause, it just opens a browser search with those words.

**Comment by captainfearless** [comment]
It seems that ifttt is not communicating with glitch as the applets show as never run.

**Comment by keydon** [comment]
if the applet has never run, then cortana does not talk to your IFTTT!

**Comment by captainfearless** [comment]
i realise that !, what i need to know is how to find out why!

**Comment by keydon** [comment]
no idea. maybe @crimean7 can help you out.

**Comment by captainfearless** [comment]
thanks keydon, i think i’ve cracked it now! my vpn had prevented cortana being linked with ifttt.

i’ll test and let you know.

**Comment by captainfearless** [comment]
it works!!! right i’m off to create some applets!

**Comment by keydon** [comment]
glad you got it working^^
