### ISSUE TITLE
Kodi returns: undefined, broker unknown phrase, kodi navigate back

### ISSUE THREAD

**Issue by ragmannnl** [OmerTu/GoogleHomeKodi#243]
i'm new to this and just wanted to know if i need to set up all ITTT actions or does the basic ones work out of the box?

NM found the Phrase broker bit... was on the wrong readme. 

so i setup every thing and made a phrase broker IFTTT but it only return as a error "undefined, broker unknown phrase, kodi navigate back" on my kodi system

when i put in the navback at glitch it works fine.

**Comment by keydon** [comment]
@ragmannnl seems navback is not supported yet by the broker.

@WallyCZ would you mind? :D

**Comment by WallyCZ** [comment]
Ups, I have somehow overlooked it :/ This PR should solve it: https://github.com/OmerTu/GoogleHomeKodi/pull/248

**Comment by keydon** [comment]
merged. thank you!
