### ISSUE TITLE
FetchError: request to http://http://

### ISSUE THREAD

**Issue by LargeTalons** [OmerTu/GoogleHomeKodi#244]
Hi guys,

I setup a docker and have all my settings entered. I can access the docker from outside of my network with my dynamic DNS name.

However, when I run the connection test, the request keeps inserting an extra "http://" into the request to kodi and it fails every time. I dont know why this is happening and Ive tried changing the dynamic host name to not include http:// but then I just get a 404 error. Please help.

I setup the docker in unraid with the image from your docker hub. The only things that are defined on the docker is the /config location and the 8099 port. Everything else is coming from the kodi-hosts.config.js file. Am I doing something wrong?

```
Loaded 1 Kodi hosts.
Loaded config from kodi-hosts.config.js, {
"authToken": "*********",
"listenerPort": "8099",
"youtubeKey": "**********"
}
Your app is listening on port 8099
Authentication succeeded
Sending command to kodi http://http://kodi-control.******:8080/jsonrpc:
{
"jsonrpc": "2.0",
"id": 1,
"method": "GUI.ShowNotification",
"params": {
"title": "GoogleHomeKodi",
"message": "Test Successful!",
"image": "info"
}
}
request failed

route: /koditestconnection
query: {}
error: FetchError: request to http://http://kodi-control.********:8080/jsonrpc failed, reason: getaddrinfo ENOTFOUND http

at ClientRequest.<anonymous> (/home/node/app/node_modules/node-fetch/index.js:133:11)
at ClientRequest.emit (events.js:209:13)
at Socket.socketErrorListener (_http_client.js:406:9)
at Socket.emit (events.js:209:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11) {
name: 'FetchError',

```

**Comment by LargeTalons** [comment]
Nevermind. I scrapped the kodi-hosts.config.js file and the /config directory and just set it up with Method 3 step 1 by just defining everything in the docker config on Unraid. 

Not sure why it doesnt work with the .config.js file though.

**Comment by keydon** [comment]
its seems you configured a `http://` where there should not be a `http://`

**Comment by LargeTalons** [comment]
....and where would I have done that? I filled out the file template
exactly as demonstrated.

**Comment by keydon** [comment]
riiiight

**Comment by LargeTalons** [comment]
Okay? Not sure why you acting like this after I asked for help. I posted a log and asked you specifically where I could have messed up and put another http:// and you seem to have an attitude, why?

**Comment by keydon** [comment]
> Not sure why you acting like this after I asked for help.

well yes, you posted the logs and I told you what was wrong. I could not be more specific, since you did not provide your configuration at this point.

>  I filled out the file template exactly as demonstrated

For statements like those I simply have no understanding. people almost never do something exactly as they should. Especially when they setup somthing for the first time and encounter weired errors.  And its not important whos fault it is, its just the way it is.
Where is it demonstrated to contain an extra `http://`? An IP-Address never ever containts the protocol. Thats what the setting `kodiProtocol` (just on line above) is for.

**Comment by LargeTalons** [comment]
I used a dynamic dns address for kodiIP because didnt want to put my external address in the configuration file. There was no information suggesting that the app wouldn't work that way considering your suggestion in the webserver setup to use a dynamic dns address instead of the IP. I figured I would have been OK with that. 

In the log I submited, it shows that I am not using an IP address in my config file and that I was using the dns address, that's why I responded asking you where I could have possibly made a mistake. I wasn't being snarky, I was simply asking for clarification. It seems we misunderstood each other, but I do not understand why you chose to respond to sarcastically when I asked you where I could have made a mistake.

In the course of trying to figure out the problem, I did discover that your kodi-hosts.config.js in your repo uses different language than the example kodi-hosts.config.js you put in step C.2 (for multiple Kodi hosts), had I known that the configuration in kodi-hosts.config.js actually called for the local Kodi IP and not my external IP as the kodi-hosts.config.js in your repo says, I would have configured it properly...so I dont believe I was incorrect in stating that I filled out the template as demonstrated. 

I appreciate the work you put into your project and I genuinely was trying to communicate with you to get help.  I figured out how to get the docker set up using another method from your readme, so I wont pursue this ticket further.  Thank you.

**Comment by keydon** [comment]
you are still missing the point.
Using your external, internal, dynamic or static IP is fine. All can be correct depending on the szenario.
But please, just leave out the `http://` its not part of any IP, dynamic or otherwise. Just put `kodi-control.******.com` down as `kodiIp` and it should work if configured correctly.
