### ISSUE TITLE
Navigate down [number]

### ISSUE THREAD

**Issue by fred959** [OmerTu/GoogleHomeKodi#245]
I seem to have an issue when requesting more than just navigate up or down. For instance when I say ''kodi navigate down 3'' I only get one movement. I'm using phrase broker [too lazy], here's the log from glitch. So what am I missing here. Thanks. 

```
Authentication succeeded
Broker processing phrase: 'navigate down three' (en)
Navigate down request received
could not parse input 'undefined' as number
Sending command to kodi http://108.16.xxxxxxxxxx/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "Input.Down"
```

**Comment by keydon** [comment]
yeah, IFTTT sends us `three` we expect/need the actual number `3`.
even when you use the more tidious applet/action approach with the ability to tell IFTTT that we expect a number there `#` it still sometimes send us words.

I guess we will have to add some kind of spoken numbers parsing.
Would also solve #193

**Comment by fred959** [comment]
Awesome.. thanks for the direction
           Have Gnu...
                             Will travel......
