### ISSUE TITLE
Phrase Broker Invocation

### ISSUE THREAD

**Issue by captainfearless** [OmerTu/GoogleHomeKodi#249]
Cortana struggles with the word Kodi, i have to spell it out, so i've changed it to monkey with one IFTTT applet.

Can i change this for Phrase Broker too , to save doing with individual applets.

**Comment by keydon** [comment]
yes you can.

**Comment by captainfearless** [comment]
### Thanks for that, i tried it last night and it wasn't working, but all good now.

Was having a bad night, as i was struggling to figure out the question label!,lol.

**Comment by keydon** [comment]
great :)
