### ISSUE TITLE
Sorry No experience in all this.  errors in Glitch

### ISSUE THREAD

**Issue by outdoor720** [OmerTu/GoogleHomeKodi#250]
I went through all the instructions to get Kodi to work with google assistant.  So now i say to google assistant

Kodi play Movie 'Skyscrapper' 
and it responds ok Playing Skyscraper Movie

But nothing happens .  What is supposed to happen?  Is it supposed to open up kodi on my computer (where i setup all ip addresses etc...)

I Tried first opening kodi then sending command,... nothing

If i get this working, what is the next step to send commands to any tv i have connected to Google Assistant...  Do they have to have Kodi installed?  Is that even possible?

Sorry again if i'm missing something obvious.

I believe there are more places or files in the Glitch project where i need to update info? Where do i create a access token and token password?  Do i not need to change some file from the defaule Kodi IP to my internal ip?

**Comment by keydon** [comment]
please see the troubshoot section in the readme and then come back with a more specific issue other than "nothing works".

**Comment by keydon** [comment]
and yes you have to have kodi already up and running and hooked up to a tv for this to work.

**Comment by fred959** [comment]
Well, I'm going to jump in here offering to help. I don't believe this is the platform to provide support, but I am more than willing to do some ''hand holding'' and help outdoor720 diagnose his issue [something I am more than capable of doing and to carry on the collaborative mindset]. I believe a direct route of communication would be more appropriate. There's a signifigance amount of well versed forums for this but if you would like to directly contact me please do. [I don't know the edicate here, correct me if I've errored] Surely most reading this have skills better used than this type of query.

**Comment by outdoor720** [comment]
> Well, I'm going to jump in here offering to help. I don't believe this is the platform to provide support, but I am more than willing to do some ''hand holding'' and help outdoor720 diagnose his issue [something I am more than capable of doing and to carry on the collaborative mindset]. I believe a direct route of communication would be more appropriate. There's a signifigance amount of well versed forums for this but if you would like to directly contact me please do. [I don't know the edicate here, correct me if I've errored] Surely most reading this have skills better used than this type of query.

I'm So sorry if I'm not following any protocol or if i'm not supposed to ask for 'Hand Holding'  I've never used this nor do i understand it.  I'm just a measly customer of Sonos, Google and want to automate and happened across this process.  I thought I got pretty far considering i don't know what i'm doing.

my contact is outdoor720@gmail.com

Thanks

**Comment by fred959** [comment]
I highly doubt this is a development issue and recommend it be closed.

**Comment by keydon** [comment]
I hope you guys sorted things out.
thx @fred959 for helping out.
