### ISSUE TITLE
Applet skipped "Unable to make web request: Error: ETIMEDOUT"

### ISSUE THREAD

**Issue by mLgz0rn** [OmerTu/GoogleHomeKodi#257]
So I've checked everything now, and all seems to work except for ifttt.
I have chosen to host it myself.
The relay is accessible from the internet, the /koditestconnection works

> Authentication succeeded
> Sending command to kodi http://mikl.spdns.eu:8085/jsonrpc:
> {
>   "jsonrpc": "2.0",
>   "id": 1,
>   "method": "GUI.ShowNotification",
>   "params": {
>     "title": "GoogleHomeKodi",
>     "message": "Test Successful!",
>     "image": "info"
>   }
> }
> Check your kodi screen for the notification!

notification shows up

> http://192.168.0.35:8085/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22method%22:%22Application.GetProperties%22,%22params%22:{%22properties%22:[%22volume%22]},%22id%22:1}

works and returns 

> {"id":1,"jsonrpc":"2.0","result":{"volume":100}}

Otherwise i've gone through all steps in the troubleshooting and all works.
the webhook looks like this 
![3211332](https://user-images.githubusercontent.com/6141439/70357516-62717900-1877-11ea-80f5-c7c4d348da6f.PNG)

Ifttt always returns Applet skipped - Unable to make web request: Error: ETIMEDOUT.
and nothing happens

best regards

**Comment by keydon** [comment]
it seems you dont have opened up/forwarded the port 8099. You need that in order to IFTTT beeing able to reach you.
Instead you seem to opened up/forwarded the port 8085. Which is not need in your self-hosting szenario, since this app can reach you kodi within your lokal network

**Comment by mLgz0rn** [comment]
8099 is forwared.
And I can access it from outside my home, you can try yourself  http://mikl.spdns.eu:8099 you should be able to access it.
I also forwarded kodi's port since I got frustrated of it not working, so tried everything

**Comment by keydon** [comment]
Well I did try 8099 and I am not getting a response back. 8085 works fine.

**Comment by mLgz0rn** [comment]
Did you try after I asked you to?
Because I had the node server shut down before that, its running now

**Comment by keydon** [comment]
hmm well indeed, works now. And IFTTT still fails with a timeout error?

**Comment by mLgz0rn** [comment]
I got no idea, but for some reason it works now

**Comment by keydon** [comment]
hehe

**Comment by mLgz0rn** [comment]
Tech stuff man xD living it's own life sometimes

**Comment by keydon** [comment]
true that!

**Comment by mLgz0rn** [comment]
Oh wait, It might actually be my firewall on my NAS that blocked the connection.
I disabled it and it worked after that

**Comment by mLgz0rn** [comment]
yuuup doh, that was it!.

Thanks for the quick replies though!

**Comment by fred959** [comment]
Damn.. I wanted to ask for your token and see where that
went. [smile it's a joke].

Missing access token..


           Have Gnu...
                             Will travel......
