### ISSUE TITLE
Env file

### ISSUE THREAD

**Issue by RonnieBoy82** [OmerTu/GoogleHomeKodi#259]
What file do I add my Kodi info (ip address,etc) into?  Do I create the env file or which file is the correct one to add the info to. Sorry, new to this and not sure

**Comment by RonnieBoy82** [comment]
Sorry, that’s when setting up on glitch

**Comment by keydon** [comment]
Should be there from the start, if not than create one :o

**Comment by RonnieBoy82** [comment]
Do I fill it in under the app.json file?

**Comment by keydon** [comment]
yeah
