### ISSUE TITLE
401 Unauthorized through glitch

### ISSUE THREAD

**Issue by deyarmond** [OmerTu/GoogleHomeKodi#264]
Not sure what setting I've gotten wrong so far. I can access Kodi outside my network and in by typing internalip:port, externalip:port, glitchproject.glitch.me doesn't seem to accept my credentials. 

```
Error in response, Unauthorized with status code: 401 (401)

Sending command to kodi http://externalip:port/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "GUI.ShowNotification",
  "params": {
    "title": "GoogleHomeKodi",
    "message": "undefined: undefined",
    "image": "error"
  }
}
(node:5591) UnhandledPromiseRejectionWarning: [object Object]
```

I can provide more details when asked, I just can't think of anything off the top of my head for extra info. I'm sure it's something simple but I've gone through all steps of FAQ.

**Comment by keydon** [comment]
You dont need to go through all points of the troubleshooting guide, just to tell me here that you tried everything. Thats not the point!
With your symptoms of the problem its impossible that you actually completed all the steps SUCCESSFULLY. So for gods sake do whats written in the readme-troubleshoot section:

> ... try to narrow down the problem. Execute the following tests in their listed order! Since early errors can make all following tests fail.

Meaning you should STOP doing all the steps as soon as you encountered a problem. If you can pinpoint the failing step, we could go from there...

And I call bullshit on 
> I can access Kodi outside my network and in by typing internalip:port
The whole point of an internal IP is that it is not accessible form the outside. So either you mixed up some ips or you did not leave your home network... might be related to your problem^^

**Comment by deyarmond** [comment]
Wow dude, that's kind of an angsty response don't you think? There was an issue getting glitch authorized, I couldn't get it to work so I tried coming here for advice. Didn't think anyone would get as irritated as you did. I'd apologize but I don't think I did anything wrong. 

At any rate I got it working so this can be closed, lest anyone else lose their temper.
