### ISSUE TITLE
Play episode in another language

### ISSUE THREAD

**Issue by Yxer13** [OmerTu/GoogleHomeKodi#266]
When you're asking to play an episode from a season, you can't change the word "season" on es.json

I finded out that in helpers.js there's a line where it says: 
    let splittedQuery = fullQuery.split('season');

so you must change the word "season" for the one on your language to work.
e.g.
    let splittedQuery = fullQuery.split('temporada'); (for Spanish)

I guess that must be something to add on the language json in order to use the same app for different languages if needed.

Cheers!! (sorry for my English)

**Comment by keydon** [comment]
the hardcoded seperator-string can now be defined in the `es.json`. 
Checkout the updated `en.json` as an example: https://github.com/OmerTu/GoogleHomeKodi/blob/master/broker/en.json#L35
