### ISSUE TITLE
Help with phrase broker setup

### ISSUE THREAD

**Issue by RonnieBoy82** [OmerTu/GoogleHomeKodi#268]
Could you please show some more detailed instructions for setting up phrase broker on ifttt?

**Comment by keydon** [comment]
Thats not how you ask for help. Be more specific.

**Comment by RonnieBoy82** [comment]
Sorry was really frustrated at that point. Port forwarding mistake in the end. Got it figured out. While I’m at it though, how do I set a command to show the pvr guide?

**Comment by keydon** [comment]
you could try saying `show tv channels` but not sure if it works. I dont have PVR and therefore cannot test/develop it.

**Comment by keydon** [comment]
timeout
