### ISSUE TITLE
[Request] Shuffle play TV Show

### ISSUE THREAD

**Issue by mtompkins** [OmerTu/GoogleHomeKodi#27]
Please consider a shuffle instruction for a TV Show series if reasonable to implement.

**Comment by p0psicles** [comment]
Implemented in the new develop branch. Please test using develop and let us know if it's working as expected.

**Comment by mtompkins** [comment]
Will do - it does appear this only plays one episode (unless I misunderstood). I was thinking more of continuous shuffling but will certainly play and revert.

**Comment by p0psicles** [comment]
Wouldnt' be impossible to add. We would need to create a playlist, shuffle allot of episodes and add them to it, and start of the playlist. Maybe for later. Let's first see if we can get this project a little active again.

**Comment by mtompkins** [comment]
Understood. ATM I am able to have this happen by setting the player to shuffle and then hit the P on the keyboard and it shuffle plays the series. I don't know if such a user keypress emulation may be an approach when the time is right to simplify ... In any event - thank you again and yes here's hoping the new Google hardware announcement in a couple days drives some interest back to this project!!
