### ISSUE TITLE
Play Playlist dont work

### ISSUE THREAD

**Issue by BaroOn5** [OmerTu/GoogleHomeKodi#272]
Im not able to start a playlist via command. Everything else working fine.
Feedback from server is "action is not a function".

**Comment by keydon** [comment]
provide full logs plz, works for me

**Comment by BaroOn5** [comment]
> provide full logs plz, works for me

Can you explain to me what log you exactly need and where i find it/how i create it? Im a more experienced user i would say so its dont need to be too detailed 😂

**Comment by keydon** [comment]
well a more experienced user wouldn have to ask where to find the logs, would he? he would just click around in the highly confusing UI of glitch and look for keywords like logs or console.
I cannot help you, I use the docker hosting approach, I am always need looking for it in glitch myself too.

**Comment by keydon** [comment]
timeout
