### ISSUE TITLE
fuzzy (miss)match?

### ISSUE THREAD

**Issue by twochannel** [OmerTu/GoogleHomeKodi#274]
Thought this was interesting

```
app_1  | Movie request received to play "Cloudy with a Chance of Meatballs"
app_1  | Sending command to kodi http://kodibox/jsonrpc:
app_1  | {
app_1  |   "jsonrpc": "2.0",
app_1  |   "id": 1,
app_1  |   "method": "VideoLibrary.GetMovies",
app_1  |   "params": {
app_1  |     "properties": [
app_1  |       "originaltitle",
app_1  |       "file"
app_1  |     ]
app_1  |   }
app_1  | }
app_1  | best fuzzy match for 'Cloudy with a Chance of Meatballs' is: {
app_1  |   file: 'smb://path/to/hancockfile',
app_1  |   label: 'Hancock',
app_1  |   movieid: 223,
app_1  |   originaltitle: 'Hancock'
app_1  | }
```

but if i do just the start of the title
```
app_1  | Movie request received to play "Cloudy with a"
app_1  | Sending command to kodi http://kodibox/jsonrpc:
app_1  | {
app_1  |   "jsonrpc": "2.0",
app_1  |   "id": 1,
app_1  |   "method": "VideoLibrary.GetMovies",
app_1  |   "params": {
app_1  |     "properties": [
app_1  |       "originaltitle",
app_1  |       "file"
app_1  |     ]
app_1  |   }
app_1  | }
app_1  | best fuzzy match for 'Cloudy with a' is: {
app_1  |   file: 'smb://path/to/cloudyfile',
app_1  |   label: 'Cloudy with a Chance of Meatballs',
app_1  |   movieid: 93,
app_1  |   originaltitle: 'Cloudy with a Chance of Meatballs'
app_1  | }
app_1  | Sending command to kodi http://cloudyfile/jsonrpc:
app_1  | {
app_1  |   "jsonrpc": "2.0",
app_1  |   "id": 1,
app_1  |   "method": "Player.Open",
app_1  |   "params": {
app_1  |     "item": {
app_1  |       "movieid": 93
app_1  |     }
app_1  |   }
app_1  | }
```

other variations work as i would expect. If i just say 'play cloudy' it picks up show called 'partly cloudy'. If i say "play chance of meatballs' it picks the correct movie.

originaltitle of each is correct. File names are reasonably different as well.

using latest docker image from https://hub.docker.com/r/sinedied/googlehomekodi/

**Comment by keydon** [comment]
yeah this library for fuzzy matching we use is sometimes very mysterious^^
I am planning to replace it, but si far havent found a good alternative.
but in you case even an exact match would have worked better, maybe I add exact match beforhand.. mmhhh

**Comment by outdoor720** [comment]
I have similar issues.

I ask kodi to play episode Magnum P.I.  and it tries to play movie on the basis of sex ??? Not sure how it translates that.

not sure if this additional issue is related to fuzzy match or recognize numbers???

Navigate right 2

google/kodi hears to and does not translate to the number 2??

**Comment by keydon** [comment]
@twochannel I upgraded the fuzzy-search library. personally I get better results now. What about u?

@outdoor720 logs or I cannot do anything

**Comment by twochannel** [comment]
looking good so far!  thank you!

does the fuzzy-search library also provide the phrase broker service? I've consider moving to it but I'm not quite sure how I would configure it for a multi kodi, local docker server setup.

**Comment by keydon** [comment]
well, the phrase parsing is a custom regex-implementation (no fuzzy support here). but after parsing the sentence it goes the same route with fuzzy-searching the movie, the same way a dedicated applet would do.
You dont need to a hard "move". 
Assuming you already have a multiple kodi-setup working, you can just add the broker and configure it the same way as the other applets you already configured. Meaning for each of your kodi instances a new broker-applet with its own triggering hotword.
