### ISSUE TITLE
"Cannot read property 'toLowerCase' of undefined" when using the broker

### ISSUE THREAD

**Issue by thecosmicslug** [OmerTu/GoogleHomeKodi#276]
Ive successfully setup and tested the individual commands on IFTTT and a local nodejs server. All working correctly, when I went on to try the broker it did not work as the nodejs included in ubuntu repositories was too old. I setup v10 as needed, but now when IFTTT contacts my nodejs server, it only responds with error 500. Looking at wireshark log of the http produced this message.

> HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 49
ETag: W/"31-CLtAcIVWgqAsTbWaADNAx21DLs4"
Date: Thu, 12 Mar 2020 15:57:47 GMT
Connection: close

> "Cannot read property 'toLowerCase' of undefined"

I followed the instructions provided, and settting each command  individually works fine, do you know what could be the problem with the broker?

**Comment by keydon** [comment]
the broker app is slightly differrent in the IFTTT configuration.
it needs a `phrase=` parameter. I susspect this is empty in your case. (maye you put `q=` in there by mistake?)

if the problem persists please provide the console output of your nodeserver

**Comment by thecosmicslug** [comment]
that was it! thankyou so much, it seems so obvious now but i've been scrating my head all day over it!
