### ISSUE TITLE
Internal server error when play episode

### ISSUE THREAD

**Issue by fana13** [OmerTu/GoogleHomeKodi#282]
Hi,
When I want to use : YOUR_NODE_SERVER/playepisode?q={{TextField}}&e= {{NumberField}}
I've got : Internal Server Error "specific episode not found in your kodi library"
Tested with many tv shows and many episodes, same issue.

Only this command doesn't work for me, all others works like a charm !
Thanks.

**Comment by keydon** [comment]
please provide the console logs of the time you tried to execute this command

**Comment by fana13** [comment]
Commands are combined with IFTTT.
On IFTTT got `
Unable to make web request. Your server returned a 500
`
Just see on kodi's interface this message : "Could not split season from episode info" when I tried to launch the command.
I can't find anything on kodi's log. How can I find it ?
Thanks.

**Comment by fana13** [comment]
Ok I found the problem.
Cause I'm french and in french I say : "Ok google, lance l'épisode 1 de la série blabla **SAISON** 1"
But the app wait SEASON and not SAISON, that's why I've got this message "could not split season".
If I say "Ok google, lance l'épisode 1 de la série blabla **SEASON** 1", it works !

**Comment by keydon** [comment]
actually I made that customizable couple weeks back (8de21d4ca77c786eb7eeeed14547b9470f3f14ef), so you can make it work with **SAISON** by adding a parameter `splitter=saison` to the request-URL like so:

`YOUR_NODE_SERVER/playepisode?splitter=saison&q={{TextField}}&e={{NumberField}}`

**Comment by fana13** [comment]
It's great !!
Many many thanks !
