### ISSUE TITLE
Navigation Custom Commands

### ISSUE THREAD

**Issue by outdoor720** [OmerTu/GoogleHomeKodi#285]
Anyone know why one of these commands works while the other does not?

Works

in Glitch enter /navright?q=3
```
exports.kodiNavRight = (request, response) => { // eslint-disable-line no-unused-vars
    console.log('Navigation Right request received');
    let Kodi = request.kodi;
  
    const times = getRequestedNumberOrDefaulValue(request, 1);

    return kodiExecuteMultipleTimes(Kodi.Input.Right, times);
}
```
**Does not work**

in Glitch enter /navup?q=3
```
exports.kodiNavUp = (request, response) => { // eslint-disable-line no-unused-vars
    console.log('Navigation Right request received');
    let Kodi = request.kodi;

    const times = getRequestedNumberOrDefaulValue(request, 1);

    return kodiExecuteMultipleTimes(Kodi.Input.up(), times);
};
```

**Comment by keydon** [comment]
not sure what you are up to, but it should say `Kodi.Input.Up` and not `Kodi.Input.up()`

**Comment by outdoor720** [comment]
Sorry, i was trying that since the following works, just does not work with 

/navup?q=3

Has there been any progress with broker accepting #'s?

xports.kodiNavUp = (request, response) => { // eslint-disable-line no-unused-vars
    console.log('Navigation up request received');
    let Kodi = request.kodi;

    return Kodi.Input.up(); // eslint-disable-line new-cap

**Comment by keydon** [comment]
as referenced in #260 the broker supports # as numbers for a month now.

**Comment by outdoor720** [comment]
Awesome, i will try it out.

Was there any additional insight as to why nav right 3 works via Glitch send command while nav up 3 does not?

As i mentioned the () was in error the code does not contain that

**Comment by outdoor720** [comment]
Great, appears to be working.

I have Navigate Up and Navigate down commands, but they don't appear to work with #'s?  Any ideas as to why?

commands appear to be consistent in broker and helper with Navigate left/right
