### ISSUE TITLE
KODI_IP - problem with dynamic IP 

### ISSUE THREAD

**Issue by Mike7400** [OmerTu/GoogleHomeKodi#286]
Hello. Any idea how to solve problem with dynamic IP address? In .env file its hardcoded, but I need to change it every time.

**Comment by keydon** [comment]
Well the readme already tells you how to solve this. And calling a configuration file hardcoded is pretty bold.

> Hint: It is strongly recommended to setup a dynDNS service of your choice. (i.e. selfhost.me)
