### ISSUE TITLE
/standbytv not working (LG)

### ISSUE THREAD

**Issue by pho084** [OmerTu/GoogleHomeKodi#287]
on my LG TV while activatetv is working flawlessly, turning off the tv just won't work.

i have configured Ifttt correctly and appended the config file as per instructions.
ifttt recognizes the command and passes it on.
i even tested adding a process.env['STANDBY_TV'] = 'true'; at the end of the file but that didn't work either.

any ideas would be much appreciated. and thanks for this wonderful app

**Comment by keydon** [comment]
not something I can help you with.
In Kodi under System -> Logging:
enable debug mode and component specific logging for libCEC.
Then reproduce the issue and report it with the logs at https://github.com/Pulse-Eight/libcec
