### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by pacocf** [OmerTu/GoogleHomeKodi#289]
Hello guys!
I have a connection problem that I don't know if it can be solved.
First indicate that I am using the Coreelec system that I do not know if it is totally compatible with this project.
My problem is when executing point 5 of the connection test, from the same network as my box. The browser keeps thinking and puts in the "Chorus 2- Coreelec web interface" tab, but it never finishes connecting nor does it ask for credentials. Afrer a while it indicates "Loading application"

The point 5 says: Open the YOUR_NODE_SERVER Url in a browser and provide the token (aka YOUR_CONNECTION_PASSWORD).
i.e. http://omertu.selfhost.me:8099/
Ensure /koditestconnection is set as the route to test.
Click Execute!

However form outside of my home network the test run fine.
Could someone help me? or just Coreelec is not supported. At the other hand IFTTT present ETIMEDOUT error

Thanks a lot!

**Comment by keydon** [comment]
What "Chorus 2- Coreelec web interface" tab?
Step 4 & 5 are about the node-app, not about kodi.

I guess you mixed up `YOUR_NODE_SERVER` with `YOUR_EXTERNAL_IP:PORT` or something. Recheck where you used what!
The Chorus 2 Webinterface is not involved in any of the steps.

And if it works from outside, whats the problem? thats all we need, dont we?

**Comment by pacocf** [comment]
Thanks for your quick response. As you may have noticed I am a novice in this matter.

"Chorus 2- Coreelec web interface" appears in the tab of my browser when I put the address http://my node server:8099/ with my dynDNS (duckdns). After this, the browser request credentials and after a few minutes appears "loading application". If I use my External-Ip directly no appear this phrase in the tab, but the result it´s the same. All of this, from my own local net.

However from outside of my home network the test run fine.

Now, I try a simple applet in IFTTT to pause a film, but it not work. I have a 401 error.

My log I think that is this, but I´m not sure: 

CoreELEC:~ # docker logs -f 759af90ffa5e
Loaded config from .env (environment)
Your app is listening on port 8099

I would appreciate you help me again.


![Error](https://user-images.githubusercontent.com/63919054/79908217-1d5f7500-841b-11ea-9a6a-097af245059d.PNG)

![Applet1](https://user-images.githubusercontent.com/63919054/79908280-3d8f3400-841b-11ea-83a2-74ba0e381e57.PNG)

![Applet2](https://user-images.githubusercontent.com/63919054/79908262-336d3580-841b-11ea-8053-b8262c117df3.png)

**Comment by pacocf** [comment]
Hi again!
I´m nor sure if my test number 5 is correct.
When I write in my web-browser within my Home net, http://mynodeserver:8099/koditestconnection, the browser doesn´t ask me for my credentials and the browser answer "file not found"

Thanks a lot

**Comment by pacocf** [comment]
I'd try another test but I don't if it's usefull. I write in my browser,
http://user:pass@mynodeserver:8099/playpause
The answer is: file not found

**Comment by pacocf** [comment]
I´m not sure the difference between test 4 and 5. The 4 test ask by my  kodi credentials, no my_connection_password, but it access to app.

**Comment by pacocf** [comment]
I can´t run B3 method, so I have tried B1 method (Glitch).
All test are fine except number 5. When I execute /koditestconnection, appears a red warning:

"Site didn´t respond.  Something in the code caused it to close the connection before providing a response".

The log file is:

request failed
route:  /koditestconnection
query:  {}
error:  { FetchError: request to http://192.168.x.xxx:8080/jsonrpc failed, reason: connect ETIMEDOUT 192.168.x.xxx:8080
    at ClientRequest.<anonymous> (/rbd/pnpm-volume/3b90a11a-bca3-405a-911c-9e95f55b58b3/node_modules/.registry.npmjs.org/node-fetch/2.6.0/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:189:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to http://192.168.x.xxx:8080/jsonrpc failed, reason: connect ETIMEDOUT 192.168.x.xxx:8080',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
body:  { token: 'xxxxxxx' }
versions:  { http_parser: '2.8.0',
  node: '10.15.3',
  v8: '6.8.275.32-node.51',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0j',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }

it is possible that the coreelec system is not compatible with your project?

Thank for you attention.

**Comment by pacocf** [comment]
The error has been solved. It was a router port configuration problem.
