### ISSUE TITLE
Not playing movie

### ISSUE THREAD

**Issue by Dohnerd** [OmerTu/GoogleHomeKodi#290]
Hi .. heres my setup.. I have installed node.js on my QNAP NAS, and followed the instructions as much as i could, even created same token and kodi password just to make sure that wasnt the issue.

When i test the external ip with port i get success and the message appears on my Kodi screen.

My google home says "playing 'movietitel'" but nothing happens on the Kodi after that.

Where have i gone wrong... what kind of logs do you need ?

**Comment by Dohnerd** [comment]
Ok so i found out if I send it like this in webhooks it works:

http://username:password@internal_ip:port/playmovie?q={{TextField}}

 how can i use it without sending username and password in clear text ?

**Comment by keydon** [comment]
which username/password are you putting in? this has nothing to do with our node application. maybe this is something your QNAP NAS is enforcing?

**Comment by keydon** [comment]
timeout
