### ISSUE TITLE
[HELP] Glitch setup : can't get the server response

### ISSUE THREAD

**Issue by JacopoV** [OmerTu/GoogleHomeKodi#294]
Hi! 

I was trying this superb project on my Kodi and Google Home setup.
I followed all the setup, and on the B) step i went for Glitch setup. 
However i can't get it working. So i started following the troubleshooting:
Step 1 ) WORKING
Step 2. B1 only ) WORKING
Step 4 ) FAILING 

When i try the point 4, i use the YOUR_NODE_SERVER created from Glitch ( i take it from Glitch UI, click on SHOW > "In a new window" and i guess is right) but it just loads forever and then timeout. 
This is done via 4G, so a different network. 
Why in the port 8099 in that troubleshooting? 
I m not sure point 4 is ok in my case.. if it's not working it seems related to open up that port for the localhost, which i dont.

Please, can i get some help? 
Thanks a lot!

**Comment by keydon** [comment]
Check the glitch logs, most likely missing a configuration property in the `.env` file.

**Comment by JacopoV** [comment]
I fixed! I m running the test now. But is it normal that the page for the server takes up to 2/3 minutes to load, and then when i press "Execute" i 've to wait 2/3 mins to see the popup on Kodi ? 

I mean the connection seems working, but it seems super slow..

**Comment by keydon** [comment]
nope not normal. a couple seconds at most. But seems to load forever at the moment for me too.
Faster speeds can be achieved with hosting it locally at your home (B2/B3).

**Comment by JacopoV** [comment]
In their server status they say : Project Hosting  Partial Outage
https://status.glitch.com/

might be that ?

**Comment by JacopoV** [comment]
Just another question, now that's "working" . If you say "play movie $" is only working for the library? Or can it send the command also to an addon? If so.. do you know how ? thanks

**Comment by keydon** [comment]
playing movies from addons is not supported. only youtube is supported.

**Comment by JacopoV** [comment]
Perfect thanks a lot for the reply :) . well it's working, just slow but due Glitch. So this ticket can be closed. :)
