### ISSUE TITLE
Feature request: allow hours and minutes in broker

### ISSUE THREAD

**Issue by Alfiegerner** [OmerTu/GoogleHomeKodi#295]
Hi, been using this for ages and the whole family loves it, thanks for your work.

One thing that is a bit of a pain is using minutes for seek to, skip forwards etc, any chance you could look for hours and minutes passed from Google assistant? E.g Kodi seek to 1 hour and 55 minutes.

Thanks.

**Comment by keydon** [comment]
Featur added. it can be configured like so:
![image](https://user-images.githubusercontent.com/2421541/85180786-96951000-b284-11ea-9d95-c9c891121f4f.png)
