### ISSUE TITLE
Phrase broker

### ISSUE THREAD

**Issue by fubie3** [OmerTu/GoogleHomeKodi#297]
I'm new to this and got things like Mute, volume up by 5, pause, play,ect working without an issue.

But I'm not able to get things like Kodi play movie or I also tried Phrase broker.  But have been unable to get them to work.

Can you assist please?

![Kodi Play move 1](https://user-images.githubusercontent.com/17099063/81628836-527e3800-93c7-11ea-993f-9d83a6830991.png)
![Kodi Play move 2](https://user-images.githubusercontent.com/17099063/81628837-5316ce80-93c7-11ea-9dd0-1203837fd34f.png)
![Kodi Play 1](https://user-images.githubusercontent.com/17099063/81628856-5f9b2700-93c7-11ea-892c-a82fa3dafd2c.png)
![Kodi Play 2](https://user-images.githubusercontent.com/17099063/81628857-6033bd80-93c7-11ea-8aab-879820a3d92a.png)

**Comment by uNbAs** [comment]
Good morning, for use the broker, you can need kodi $ where $ is a phrase you say.

And for use IFTTT you need generate API token for comunication. You can obtain the api in the next URL https://platform.ifttt.com/services/hello_world_ebb1630908/api Then you can make this in ifttt ![](https://fotos.subefotos.com/ba78aa6c7717f4953b4025962e8c9425o.png)
![](https://subefotos.com/ver/?96a4e92255e943da1eac94a54dbef557o.png)

**Comment by keydon** [comment]
I took the liberty of correcting @uNbAs comment, his screens are ok.

**Comment by fubie3** [comment]
Thanks guys.

This is very much appreciated!

**Comment by uNbAs** [comment]
Sorry @keydon I think is needed, is good work without IFTTT token! Thanks for your correction!
