### ISSUE TITLE
Requests to the server should be sent over POST and not GET as there is body content being sent

### ISSUE THREAD

**Issue by whitter** [OmerTu/GoogleHomeKodi#30]
Not an overly burning issue, but should requests not be coming over a POST request as they contain body content?  Only noticed it when trying to check if I had setup a locally running copy of the server correctly as Postman will not let you send body content on a GET request.

**Comment by OmerTu** [comment]
Thanks, changed the instructions to use "POST". Now the server supports both Get and Post.
