### ISSUE TITLE
How to shuffle all my songs and start radio?

### ISSUE THREAD

**Issue by seventhsite** [OmerTu/GoogleHomeKodi#301]
Hi!
Thank you for great possibilites! 

1. I want to play randomly all my audio files on kodi. Is there any voice command for it?
2. I have a lot of radio channels, how I can start it?

(sorry for my English)

**Comment by keydon** [comment]
1. you can create a smart playlist in kodi with all desired music in it, then use /playplaylist to play it.
2. kodi can play FM Radio? Like PVR? Didnt know about that, cannot develop against something I dont have sorry.

**Comment by seventhsite** [comment]
1. I will try
2. Yes, I am about PVR. My PVR playlist have two types of lines - TV and radio. And I have a radio in menu.

```
#EXTINF:-1,5 канал (Украина)
http://ott.watch/stream/xxxxx/189.m3u8

#EXTINF:-1,tvg-logo="http://comedy-radio.ru/design/images/header_logo_b.png" group-title="radio" radio="true",Comedy Radio
http://ic7.101.ru:8000/a202
```

**Comment by keydon** [comment]
which PVR Client-Addon are you using?

**Comment by seventhsite** [comment]
> which PVR Client-Addon are you using?

PVR IPTV Simple Client

**Comment by keydon** [comment]
I will take a look at it, already found a suspicious line of code.

**Comment by seventhsite** [comment]
If it will help:

```
Authentication succeeded
==== BEGIN === route:  /broker
Broker processing phrase: 'switch to channel number 140' (en)
redirecting request to: 'kodiPlayChannelByNumber
PVR channel request received to play "140"
Sending command to kodi http://192.168.7.2:8087/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "PVR.GetChannels",
  "params": {
    "channelgroupid": "alltv",
    "properties": [
      "uniqueid",
      "channelnumber"
    ]
  }
}
Found PVR channel Звезда - 10 (66)
Sending command to kodi http://192.168.7.2:8087/jsonrpc:
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "Player.Open",
  "params": {
    "item": {
      "channelid": 66
    }
  }
}
==== END === route:  /broker

```

**Comment by seventhsite** [comment]
And how my playlist look like. It have 139 TV channels and radio start from 140.

[playlist.txt](https://github.com/OmerTu/GoogleHomeKodi/files/4678686/playlist.txt)

**Comment by seventhsite** [comment]
About first question.
1. I created smart playlist "music" but it don't work. 

![IMG_20200525_235844](https://user-images.githubusercontent.com/19604503/82842986-39f04080-9ee4-11ea-8ed0-87d569b64491.jpg)

```
:~/.kodi/userdata/playlists# ls -l mixed/
итого 4
-rw-r--r-- 1 seventh mygroup 278 мая 25 23:56 music.xsp
```


```
request failed
route:  /broker
query:  { phrase: 'play playlist music', q: 'playlist music' }
error:  Error: No fuzzy match for 'playlist music'
    at fuzzySearchBestMatch (/home/node/app/helpers.js:156:15)
    at /home/node/app/helpers.js:241:20
```

**Comment by keydon** [comment]
the /playplaylist command is not supported by the broker yet. either create a dedicated IFTTT-Applet for /playplaylist or wait for me to add it to the broker ;O

**Comment by keydon** [comment]
kodi distinguishes between tv and radio channels. up until now we only supported tv-channels.
you now have to explicitly state in case of radio: `switch to radio channel 1` (counting starts from 1 again, not 140)
if you say `switch to tv channel` or just `switch to channel`, then kodi looks for TV-Channels.

Also added playlistsupport to the broker.
