### ISSUE TITLE
Kodi keeps playing the same movie no matter which title I choose

### ISSUE THREAD

**Issue by dansavoie** [OmerTu/GoogleHomeKodi#304]
As the title implies, Kodi will keep playing the same movie no matter what title I ask for and Google answers with the movie title I asked for - it still plays the same movie.

All the instructions are fabulous and I have no idea what is wrong. It will pause and stop correctly.

Any ideas?

**Comment by dansavoie** [comment]
Also, curious if there is a way to change it from Kodi to a custom name.

**Comment by dansavoie** [comment]
OK. Figured it out. My cell phone kept changing the TextField. It's easier to edit on a laptop than a phone. Thanks for this awesome work. If it can be changed to a custom name instead of Kodi, let me know. Cheers.

**Comment by keydon** [comment]
_kodi_ is just a suggestion, you can put in your IFTTT-applet whatever you like.
