### ISSUE TITLE
Error while running node.js

### ISSUE THREAD

**Issue by cmi5037** [OmerTu/GoogleHomeKodi#306]
Hi all,

I'm tying to run the application from my Ubuntu media server to connect to all of my kodi instances. 
 I am chose to use option B to set up a nodejs-webserver. I believe I followed the install, But I am getting this error whenever I try to run node.js:

```
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/XXXX/XXXXXXX/GoogleHomeKodi/server.js:6:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

any help would be greatly appreciated

Thanks

**Comment by keydon** [comment]
Als Hosting Options start with B, which one did you choose? From your issue I guess 2 or 3?
if B2, post your output of the following commands:
```
node --version
npm --version
npm install
```

**Comment by cmi5037** [comment]
Sorry about that, I did use option B 

node version
v8.10.0

npm --version
3.5.2

npm install
npm WARN enoent ENOENT: no such file or directory, open '/home/xxxxxxx/package.json'
npm WARN cmi5037 No description
npm WARN cmi5037 No repository field.
npm WARN cmi5037 No README data
npm WARN cmi5037 No license field.

**Comment by cmi5037** [comment]
Sorry about that, I did use option B

node version
v8.10.0

npm --version
3.5.2

npm install
npm WARN enoent ENOENT: no such file or directory, open '/home/xxxxxxxx/package.json'
npm WARN xxxxxxxx No description
npm WARN xxxxxxxx No repository field.
npm WARN xxxxxxxx No README data
npm WARN xxxxxxxx No license field.

Thanks!

**Comment by keydon** [comment]
You are doing it again, B ist not a option. B1, B2, B3 or B4
oh and sorry, you need to execute `npm install`
in the same directory the code is. like `/XXXX/XXXXXXX/GoogleHomeKodi/`

**Comment by cmi5037** [comment]
lol B2

**Comment by keydon** [comment]
timeout. closing.
