### ISSUE TITLE
Toubleshooting.  Does not load a page asking for my token when accessing via an external IP.  Instead asks for username and  password.

### ISSUE THREAD

**Issue by BonzoFerret** [OmerTu/GoogleHomeKodi#309]
My Kodi is installed under Coreelec (a clone of libreelec for s905 devices).   I have followed the instructions in B3 to set up a local webserver using Docker, and I have run the troubleshooting test 3 successfully on http://192.168.0.10:8099/ and I get the page asking for a token, and I get the message on the KODI screen telling me that the test was successful.

Troubleshooting test 4, however, fails because it doesn't present the page asking for my token, instead it presents the Authentication Required window with the following message:

http://86.27.xxx.xx:8099 is requesting your username and password. The site says: “XBMC”

I am pretty sure I've done my port forwarding correctly.  

Local IP address  192.168.0.10 
Local Port range  8080-8080
External Port range   8099-8099
Protocol  BOTH  (TCP and UDP)

My router is a Virgin Media Hub 3.0 if that makes a difference.  

If I enter my username and password that I set up under the Services setup in Kodi then I get a control page for controlling KODI from the web.

FIXED!  The problem was my forwarding.  I needed the following:

Local IP address  192.168.0.10 
Local Port range  8099-8099
External Port range   8099-8099
Protocol  BOTH  (TCP and UDP)

**Comment by keydon** [comment]
Glad you figured it out by yourself :)
