### ISSUE TITLE
Suggestion: Simplify code using body-parser

### ISSUE THREAD

**Issue by WoLpH** [OmerTu/GoogleHomeKodi#31]
Instead of manually taking care of the body parsing it might be more convenient to let [body-parser](https://github.com/expressjs/body-parser) take care of it.

Instead of:
```javascript
var validateRequest = function(req, res, processRequest){
  var jsonString = '';
  var requestToken = '';
  var jsonBody;

  if (req == null || req.query == req) {
    console.log("403 - Unauthorized request");
    res.sendStatus(403);
    return;
  }
  
  req.on('data', function (data) {
      jsonString += data;
  });
  req.on('end', function () {
    if (jsonString != '') {
      jsonBody = JSON.parse(jsonString);
      if (jsonBody != null) {
        requestToken = jsonBody['token'];
        console.log("Request token = " + requestToken);
        if (requestToken == process.env.AUTH_TOKEN) {
          console.log("Authentication succeeded");
          processRequest(req, res);
          return;
        }
      }
    }
    console.log("401 - Authentication failed");
    res.sendStatus(401);
  });
};
```

You could probably just use:
```javascript
var validateRequest = function(req, res, processRequest){
    if(req == null || req.query == req || !req.body.token){
        console.log("403 - Unauthorized request");
        res.sendStatus(403);
        return;
    }else if(req.body.token == process.env.AUTH_TOKEN){
        console.log("Authentication succeeded");
        processRequest(req, res);
        return;
    }else{
        console.log("401 - Authentication failed");
        res.sendStatus(401);
    }
};
```

I can create a pull request if you're interested :)

**Comment by p0psicles** [comment]
Already being taken care off. Expect some big changes coming in today.

**Comment by WoLpH** [comment]
Great! I'm looking forward to it :)

PS: I've tried to set up something similar using api.ai but for some reason that requires a two-word name minimum whereas IFTTT only requires a single word so for the time being I'll keep the IFTTT route.

**Comment by p0psicles** [comment]
What do you mean with `requires two-word name` minimum? The command to initiate a conversation? Or the commands them selves?

The thing that's kinda keeping me from using it is that you need to start up a conversation before you can really start throwing commands at it. At least that's when it's running in "test" mode. Maybe that's different when you've published the app. But that's not possible, as 1. each user needs to be able to configure his endpoint somehow and two it's not going to be approved.

There are some advantages to using api.ai, like:
* Real conversations. When it's missing something, it will ask for it. Like `play show game of thrones season 1`. It still needs to know the episode.
* Machine learning. More then one way to ask for the same intent.
* One route, using parameters.
* Exportable/Importable configuration (opposed to IFTTT needing to set up an applet for each intent.)

Disadvantages:
* Little bit hard to set up the non-expiring 'test' api.ai app.
* It requires an endpoint with valid SSL certificate (no self-signed)
* The conversation before you can start throwing commands
* If you want to control multiple kodi installations, you are kinda forced to set up it locally, using something like letsencrypt. Or you need to port forward every kodi api.

**Comment by WoLpH** [comment]
> What do you mean with requires two-word name minimum? The command to initiate a conversation? Or the commands them selves?

The command to initiate a conversation, I wouldn't be able to do "hey google kodi play" because it would need to be something like "hey google kodi player play" which is a tad annoying :P

> The thing that's kinda keeping me from using it is that you need to start up a conversation before you can really start throwing commands at it. At least that's when it's running in "test" mode. Maybe that's different when you've published the app. But that's not possible, as 1. each user needs to be able to configure his endpoint somehow and two it's not going to be approved.

The conversation part is easily fixable though, instead of setting up the conversation you can do something like "hey google tell <name> to <command>". I was kind of hoping to be able to set up a universal action service that everyone could easily use after publishing it once. But I'm not sure if that's easily possible without setting up your own service to handle the requests. For what it's worth, I have been able to get it to communicate with Glitch without any issues so it wouldn't be impossible to do that.

But... it would need some authentication and would need to allow for users to specify their own kodi endpoint. For ease of use I'd think a kodi plugin which uses a websocket client might be best, but I'm getting ahead of myself here.

**Comment by p0psicles** [comment]
I also started on a project that adds the routes usable with api.ai in one of my gh projects. But that's still WIP.

**Comment by p0psicles** [comment]
Implemented in the new develop branch.
