### ISSUE TITLE
google cloud run activate and standby connect ECONNREFUSED

### ISSUE THREAD

**Issue by nickelnine** [OmerTu/GoogleHomeKodi#310]
Hi,

Thanks for your work on this.

I installed the project via Google Cloud Run with the intent of turning my tv on and off.
I installed the json-cec.zip and enabled everything in Kodi's service settings.

When I execute the `koditestconnection`, I receive the notification in Kodi, but when I execute the `activatetv` or `standbytv` my external IP is not reachable and I'm not sure why --` request to http://198.48.xxx.yyy:8080/jsonrpc failed, reason: connect ECONNREFUSED 198.48.xxx.yyy:8080`

**Comment by keydon** [comment]
Sorry for getting back to you that late. I was busy with life and stuff.

Your issue sound very weird. The error seems to be a low level network problem.
So you can execute `/koditestconnection` which works, then execute `/activatetv` which errors out and then `/koditestconnection` again, which then works? that sounds impossible :O Would you mind to post here the logs of all three executions?

**Comment by keydon** [comment]
timeout
