### ISSUE TITLE
Hey Google, kodi resume [movie] or resume an episode of [tv show] failed

### ISSUE THREAD

**Issue by madmax2** [OmerTu/GoogleHomeKodi#318]
I can't resume a [movie] or resume an episode of [tv show].
I am using phrase broker, 

i tried these commands and it is not working for me

e.g.
"Hey Google, kodi resume boss baby"

"Hey Google, kodi resume an episode of jack ryan"

What is wrong and why it is not working?
I followed the commands as shown in the readme

It has picked up the phrase in terminal window but does not resume the movie or most recent TV show episode (that I was watching)

**Comment by keydon** [comment]
please paste the full output of your terminal window. helps to see whats happening^^

**Comment by keydon** [comment]
nevermind, found the error in the broker. fix is coming right up

**Comment by madmax2** [comment]
thanks..good to know you replicated the bug

how do we get latest updates when running local server?
do we do git pull

and how do we know when the fix has been released?

Also in the notes
you should add some note about updating to latest version for other methods like local server, docker etc..

Currently it just mention glitch which is not longer a valid option

[readme]
**How to update to the latest version
Go to Glitch.com and sign in with your github user
Select your Glitch project and under advance settings choose Import from GitHub
Enter this project OmerTu/GoogleHomeKodi**

**Comment by keydon** [comment]
Well I added some update-instructions to the readme, hope this helps.
As soon as a commit is pushed to [master](https://github.com/OmerTu/GoogleHomeKodi/commits/master), it is released.
