### ISSUE TITLE
Starting Playback on Android TV Plays Videos in Background

### ISSUE THREAD

**Issue by coopermf** [OmerTu/GoogleHomeKodi#326]
Hey, I set this up and love the functionality but when I try to play content on my nvidia shield tv while kodi isn't already open it just plays videos in the background and I have to open up the kodi app to actually view it. Is there any way to launch the kodi app when starting playback or any other workaround? It's not very convenient to start a video with voice control and then have to grab the remote and open the app.

**Comment by jptuomi** [comment]
I first tell google home to “Start the app kodi on TV”, then all is peachy...

**Comment by keydon** [comment]
seems to be an issue on the OS level, cannot do much on Kodi-API level.

The solution of @jptuomi seems reasonably ok :)

**Comment by coopermf** [comment]
Ok, I was afraid this would be the recommendation. Unfortunately I don't actually use the google assistant on the shield TV which is the only one capable of opening the app on the TV to my knowledge. It would be ideal if Kodi had a feature that might launch the app upon starting video playback but upon asking for this I was directed here for a workaround.

**Comment by keydon** [comment]
you could try if sending this command brings the kodi app to the foreground, but i doubt it^^

```
#!/bin/bash

LOGIN=keydon:1234
KODI_URL=http://localhost:8080/jsonrpc
curl -v \
	--no-keepalive \
	--basic -u $LOGIN \
	--url $KODI_URL \
	--header "Accept: application/json" \
	--header "Content-type: application/json" \
	--data '
[
  {
    "jsonrpc": "2.0",
    "method": "GUI.SetFullscreen",
    "params": {
      "fullscreen": true
    },
    "id": 1
  }
]
'
````

**Comment by coopermf** [comment]
Ok, thanks. I'll give this a shot when I can do some testing.

**Comment by jptuomi** [comment]
I use google home mini for all these commands would work from the assistant
on my phone as well.

Den ons 4 nov. 2020 00:40coopermf <notifications@github.com> skrev:
