### ISSUE TITLE
Issue with IFTTT

### ISSUE THREAD

**Issue by Brunathaur** [OmerTu/GoogleHomeKodi#327]
Hello. I have an issue with IFTTT. I have succeeded with the test connection to kodi (there is the message on my tv screen) but when I speak to my Google Google home, nothing happens so I'm going to take a look to my app IFTTT and there is a message :
![Screenshot_20201114_112121_com ifttt ifttt](https://user-images.githubusercontent.com/46498738/99145136-60f62680-266c-11eb-84a2-4150c02ce245.jpg)
Any idea? 
Kind Regards

**Comment by keydon** [comment]
seems you have some error in the applet configuration, where you configure the url to your google-home-kodi-instance

**Comment by keydon** [comment]
timeout
