### ISSUE TITLE
Pl.json broker

### ISSUE THREAD

**Issue by EuHadii1** [OmerTu/GoogleHomeKodi#334]
Please add pl.json to broker list

`{ 
     "kodiActivateTv": "włącz telewizor", 
     "kodiBingeWatchTvshow": "odtwarzaj wszystkie odcinki (?<q>.+)", 
     "kodiCleanLibrary": "wyczyść bibliotekę", 
     "kodiDecreaseVolume": "ścisz( o (?<q>.+))?", 
     "kodiDecreaseVolume:1": "zmniejsz głośność( o (?<q>.+))?", 
     "kodiDisplayInfo": "co oglądam", 
     "kodiExecuteAddon": "uruchom wtyczkę (?<q>.+)", 
     "kodiHibernate": "hibernuj", 
     "kodiIncreaseVolume": "podgłoś( o (?<q>.+))?", 
     "kodiIncreaseVolume": "zwiększ głośność( o (?<q>.+))?", 
     "kodiLoadProfile": "uruchom profil (?<q>.+)", 
     "kodiMuteToggle": "(wycisz|włącz dźwięk)", 
     "kodiNavBack": "cofnij( (?<q>.+))?", 
     "kodiNavContextMenu": "pokaż menu kontekstowe", 
     "kodiNavDown": "w dół( (?<q>.+))?", 
     "kodiNavHome": "ekran startowy", 
     "kodiNavLeft": "w lewo( (?<q>.+))?", 
     "kodiNavRight": "w prawo( (?<q>.+))?", 
     "kodiNavSelect": "wybierz", 
     "kodiNavUp": "w górę( (?<q>.+))?", 
     "kodiOpenFavourite": "(odtwórz|odtwarzaj) (?<q>.+) (z) moich ulubionych", 
     "kodiOpenMovie": "(odtwórz|odtwarzaj) (?<q>.+) (z) moich filmów", 
     "kodiOpenMovie:1": ".*szczegóły (z|o) (?<q>.+) (z) moich filmów", 
     "kodiOpenMovie:2": ".*szczegóły (z|o) filmie (?<q>.+)", 
     "kodiOpenMovie:3": ".*info(rmacje)? (z|o) (?<q>.+) (z) moich filmów", 
     "kodiOpenMovie:4": ".*info(rmacje)? (z|o) filmie (?<q>.+)", 
     "kodiOpenTvshow": "(odtwórz|odtwarzaj) (?<q>.+) z moich seriali", 
     "kodiOpenTvshow:1": ".*szczegóły (z|o) (?<q>.+) (z) moich seriali", 
     "kodiOpenTvshow:2": ".*szczegóły (z|o) serialu (?<q>.+)", 
     "kodiOpenTvshow:3": ".*info(rmacje)? (z|o) (?<q>.+) (z) moich seriali", 
     "kodiOpenTvshow:4": ".*info(rmacje)? (z|o) serialu (?<q>.+)", 
     "kodiPlayAlbum": "(odtwórz|odtwarzaj) album (?<q>.+)", 
     "kodiPlayArtist": "(odtwórz|odtwarzaj) piosenki wykonawcy (?<q>.+)", 
     "kodiPlayRadioChannelByNumber:explicit": "przełącz na? stację radiową numer (?<q>.+)", 
     "kodiPlayRadioChannelByName:explicit": "przełącz na? radio (?<q>.+)", 
     "kodiPlayRadioChannelByNumber:int": "przełącz na? radio (?<q>\\d+)$", 
     "kodiPlayRadioChannelByNumber:felling-lucky": "przełącz na? radio (?<q>.+)", 
     "kodiPlayRadioChannelByName": "przełącz na (?<q>.+) radio", 
     "kodiPlayRadioChannelByNumber:just": "radio (?<q>.+)", 
     "kodiPlayTvChannelByNumber:explicit": "przełącz na? (program|kanał) numer (?<q>.+)", 
     "kodiPlayTvChannelByName:explicit": "przełącz na? (program|kanał) (?<q>.+)", 
     "kodiPlayTvChannelByNumber:int": "przełącz na? (program|kanał) (?<q>\\d+)$", 
     "kodiPlayTvChannelByNumber:felling-lucky": "przełącz na? (program|kanał) (?<q>.+)$", 
     "kodiPlayTvChannelByName": "przełącz na (?<q>.+)? (program|kanał)", 
     "kodiPlayTvChannelByNumber:just": "(program|kanał) (?<q>.+)", 
     "kodiPlayEpisodeHandler": "(odtwórz|odtwarzaj) (?<q>.+(?<splitter>sezon).+) odcinek (?<e>\\d+)", 
     "kodiPlayMusicByGenre": "(odtwórz|odtwarzaj) gatunek muzyki (?<q>.+)", 
     "kodiPlayRandomMovie": "(odtwórz|odtwarzaj) losowy (?<genre>.+ )?(film)( z roku (?<year>\\d+))?", 
     "kodiPlayRecentEpisodeHandler": "(odtwórz|odtwarzaj) nowy odcinek", 
     "kodiPlaySong": "(odtwórz|odtwarzaj) piosenkę (?<q>.+)", 
     "kodiPlayTvshow": "(odtwórz|odtwarzaj) odcinek serialu (?<q>.+)", 
     "kodiPlayTvshow:1": "(odtwórz|odtwarzaj) odcinek serialu (?<q>.+)", 
     "kodiPlayTvshow:2": "(odtwórz|odtwarzaj)? serial (?<q>.+)", 
     "kodiPlayYoutube:1": "youtube (odtwórz|odtwarzaj) (?<q>.+)", 
     "kodiPlayYoutube:2": "(odtwórz|odtwarzaj) na youtube (?<q>.+)", 
     "kodiPlayYoutube:3": "(odtwórz|odtwarzaj) (?<q>.+) (na|z) youtube$", 
     "kodiReboot": "uruchom ponownie", 
     "kodiResumeTvshow": "wznów? odcinek? serialu (?<q>.+)", 
     "kodiResumeTvshow:1": "wznów? odcinek serialu (?<q>.+)", 
     "kodiResumeTvshow:2": "wznów? serial (?<q>.+)", 
     "kodiResumeMovie": "wznów( film)? (?<q>.+)", 
     "kodiPlayPause": "(wznów|pauza)", 
     "kodiScanLibrary": "aktualizuj bibliotekę", 
     "kodiSearchYoutube": ".*(odtwórz|odtwarzaj) na youtube (?<q>.+)", 
     "kodiSearchYoutube:1": ".*(odtwórz|odtwarzaj) (?<q>.+) na youtube", 
     "kodiSeekBackwardMinutes:with-hours": "przesuń do tyłu o? (?<hours>.+) (godzin|godzinę|godziny)?( and)? (?<q>.+) minutes?", 
     "kodiSeekBackwardMinutes:just-minutes": "przesuń do tyłu do? (?<q>.+) (minut|minuty)", 
     "kodiSeekBackwardMinutes:just-hours": "przesuń do tyłu do? (?<hours>.+) (godzin|godzinę|godziny)?", 
     "kodiSeekBackwardMinutes:default-one-minute-backward": "seek backwards?$", 
     "kodiSeekForwardMinutes:with-hours": "przesuń( do przodu o?)? (?<hours>.+) (godzin|godzinę|godziny)?( i)? (?<q>.+) (minut|minuty)?", 
     "kodiSeekForwardMinutes:just-hours": "przesuń( do przodu do?)? (?<hours>.+) (godzin|godzinę|godziny)?", 
     "kodiSeekForwardMinutes:just-minutes": "przesuń( do przodu do?)? (?<q>.+) (minut|minuty)", 
     "kodiSeekForwardMinutes:default-one-minute-forward": "przesuń( do przodu o?)?$", 
     "kodiSeektominutes": "przesuń do (?<q>.+) (minut|minuty)", 
     "kodiSetAudio": "ścieżka audio (?<q>.+)", 
     "kodiSetAudioDirect": "wybierz ścieżkę audio (?<q>.+)", 
     "kodiSetSubs": "napisy (?<q>.+)", 
     "kodiSetSubsDirect": "wybierz napisy (?<q>.+)", 
     "kodiSetVolume": "ustaw głośność na (?<q>.+)", 
     "kodiShowMovieGenre": "pokaż gatunek filmowy (?<q>.+)", 
     "kodiShowWindow": "show (?<q>.+)", 
     "kodiShuffleEpisodeHandler": "shuffle (?<q>.+)", 
     "kodiShutdown": "wyłącz", 
     "kodiStandbyTv": "uśpij", 
     "kodiStop": "zatrzymaj", 
     "kodiSuspend": "wstrzymaj", 
     "kodiToggleFullscreen": "pełen ekran", 
     "kodiTogglePartymode": "tryb imprezy", 
     "playercontrol:words": "(playlista? )?(?<q>poprzednia|następna).*?( playlista)?$", 
     "playercontrol:index": "playlista( indeks| numer)? (?<q>\\d+)", 
     "kodiPlayPlaylist": "((odtwórz|odtwarzaj) )?playlistę (?<q>.+)", 
     "kodiPlayMovie": "(odtwórz|odtwarzaj) (film )?(?<q>.+)", 
     "kodiPlayMovie:1": "(odtwórz|odtwarzaj) (film )?(?<q>.+) z opóźnieniem (?<delay>\\d+) sekund" 
 } `

**Comment by keydon** [comment]
sorry it took me so long.
added pl.json, thank you
