### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by pinn73** [OmerTu/GoogleHomeKodi#335]
Hi,

Had this all working fine but have moved house and run into errors. The port has been forwarded and I have edited kodi-hosts.config.js in my local webserver. When I go to test, I get the message "Your relay from IFTTT to your Kodi at home is up and running." but when I execute a command I am getting this:
Internal Server Error
"request to http://xxxxxxxx/jsonrpc failed, reason: connect ETIMEDOUT xxxxxxxxx"
The IP it is pointing to is the old one not the one in my new house. Not sure where else I need to update besides  kodi-hosts.config.js. 

Thanks

**Comment by keydon** [comment]
well if changing the `hosts.config.js` did not help (and afterwards restarting the local node instance of course).
then I would check the environment variables `GOOGLE_HOME_KODI_CONFIG` and/or `KODI_IP` etc.

**Comment by pinn73** [comment]
> well if changing the `hosts.config.js` did not help (and afterwards restarting the local node instance of course).
> then I would check the environment variables `GOOGLE_HOME_KODI_CONFIG` and/or `KODI_IP` etc.

Sorry, if I'm mistaken, but I'm running a local webserver - isn't that for docker?

**Comment by keydon** [comment]
Not necessarily. It all can be mixed.
I mean it has to be wrongly configured _somewhere_ right? (I hope your restarted the app after the config-change)

**Comment by pinn73** [comment]
Got it sorted. Rather than using the actual ip, I used the redirect from my dynamic dns provider and all worked.
