### ISSUE TITLE
Show favorites don't work

### ISSUE THREAD

**Issue by Brunathaur** [OmerTu/GoogleHomeKodi#338]
Hello. Since we can't use IFTTT with glitch, I try with repl.it but when I say "Kodi open $ from my favourites", it doesn't work. Any idea? Regards

**Comment by keydon** [comment]
hi,
you dont give me much to work with.
Please follow the troubleshooting and tell me what step fails with what issue.
https://github.com/OmerTu/GoogleHomeKodi#troubleshooting

**Comment by Brunathaur** [comment]
Hello Keydon. I've given a few explanations. I have kodi on an android box connected to my box with ethernet cable. The movies are stored on an external hard drive connected to my windows PC. The node server is on this PC. Before, with glitch and IFTTT, all my commands were OK. My listening port was 8080 (like the kodi port). Now, I have configured the listening port on 8099.i run server.js and I go to internet and when I type the ip android box with 8099, there is a window with koditestconnection which appears, i type my token and I have an error message about my external ip:8080. Internal server error "request to http://external ip:8080/jsonrpc failed, reason : ETIMEDOUT external ip:8080". Can you help me?

**Comment by Brunathaur** [comment]
I have forgotten, I have opened port 8080 and 8099 on my router

**Comment by keydon** [comment]
1. reconfigure KODI_PORT to use your internal IP of the android box,.
2. you can also close the 8080 port on your router, its not needed, if the node server is at your home.

IFTTT connects to your EXTERNAL-IP at Port 8099 to your node server on the PC.
From there, within your local home network, it connects to your android box via the internal IP an port 8080.

**Comment by Brunathaur** [comment]
The test is succesfull with kodi test connection. I have the message on tv screen but nothing happens when I speak to Google home. There is an issue with IFTTT (when it must go to internet). When I use the real external ip (whatsmyip.org), the message is :"connect ECONNREFUSED externalIP:8099 unable to make web request to externalIP:8099/playmovie? q=xxxx" and when I use INTERNALIP of my android box, the message is "timed out waiting for response from https://internalIP

**Comment by Brunathaur** [comment]
Hi Keydon, I type on closed by error
I type on windows the IP adress of the PC and 8099 and the test is succesfull with kodi test connection. I have the message on tv screen but nothing happens when I speak to Google home. There is an issue with IFTTT (when it must go to internet). When I use the real external ip (whatsmyip.org), the message is :"connect ECONNREFUSED externalIP:8099 unable to make web request to externalIP:8099/playmovie? q=xxxx" and when I use INTERNALIP of my android box, the message is "timed out waiting for response from https://internalIP:8080/playmovie?q=xxxx. Can you help me please? Best regards

**Comment by keydon** [comment]
> I type on windows the IP adress of the PC and 8099 and the test is succesfull with kodi test connection.

thats super, your node configuration is ok! the pc can control the android kodi.

> There is an issue with IFTTT. the real external ip (whatsmyip.org), the message is :"connect ECONNREFUSED externalIP:8099 unable to make web request to externalIP:8099/playmovie? q=xxxx"

well either your port forwaring of 8099 from your router to your pc is not working (go double check that) or your internet provider is sharing your ipv4 address with other customers.
Try  "externalIP:8099" from your phone with disabled wifi, does that work?

**Comment by Brunathaur** [comment]
No, it doesn't work. I have the same error message : ERR CONNECTION REFUSED

**Comment by keydon** [comment]
Well, you cannot reach your pc from the internet. So if it worked with glitch, it has to be a bad router port forwarding configuration

**Comment by Brunathaur** [comment]
Keydon. I have succeeded to watch movies talking to Google home but when I try to open favorites, I have an issue, nothing happens. My favorites are mp4 and avi files which are not movies but karaoke clips. They are on the same external hard drive that the movies. The IFTTT message is

**Comment by Brunathaur** [comment]
Your server returned a 500. Unable to make web request to http://externalIP:8099/playfavourite?q=name of the mp4 or avi file. Any idea?

**Comment by Brunathaur** [comment]
![Uploading IMG_20210418_151636.jpg…]()

**Comment by keydon** [comment]
sorry, there was a bug in our helper functions.
I now fixed the playing of favorites. Should work for you after you upgrade to the newest commit.

**Comment by Brunathaur** [comment]
Hi Keydon. You can't imagine how happy I am. It works very well now. Best regards

**Comment by keydon** [comment]
glad it works for you now :)

I dont know an easy way of marking all files as favorites.
As an alternative I added a new feature `/playItemOfDirectory` which can be used like this:

![image](https://user-images.githubusercontent.com/2421541/115299927-ac52ba80-a15f-11eb-9969-86269b8cb4fa.png)

the directory needs to be configured in the IFTTT-Applet as an additional Query-Parameter.
Make sure your directory path is [URL-Encoded!](https://meyerweb.com/eric/tools/dencoder/)

**Comment by Brunathaur** [comment]
Keydon, I have forgotten to tell you that the videos are in subfolders (a, b, c, d....etc) in a folder. Finally, I have marked all the videos as favourites and it was quickly.
Thanks a lot for the very good job!

**Comment by keydon** [comment]
you are welcome, have fun with it :)
