### ISSUE TITLE
Missing Access Token

### ISSUE THREAD

**Issue by miketunes** [OmerTu/GoogleHomeKodi#340]
Ifttt doesn't seem to be passing along the access token, I get error 500:
Action failure message: Your server returned a 500. Unable to make web request to http://miketunes.dyndns.org:8099/playmovie?q={TextField}

I get the same error in step 1 troubleshooting, this command:
http://192.168.1.100:8099/jsonrpc?request={"jsonrpc":"2.0","method":"Application.GetProperties","params":{"properties":["volume"]},"id":1}
responds with: { "message": "401 - Missing access token", "name": "ResponseException", "status": 401, "statusText": "401 - Missing access token" }

I'm using the local node server method, the console shows 401 - missing access token errors.  

This does work if I manually type in the access token at this url, the message does show up in Kodi:
http://miketunes.dyndns.org:8099/

Here's my ifttt recipe: https://imgur.com/a/NyKN5Kn

**Comment by keydon** [comment]
> Ifttt doesn't seem to be passing along the access token, I get error 500:
> Action failure message: Your server returned a 500. Unable to make web request to [http://miketunes.dyndns.org:8099/playmovie?q={TextField}](http://miketunes.dyndns.org:8099/playmovie?q=%7BTextField%7D)

hm strange.

> I get the same error in step 1 troubleshooting, this command:
> [http://192.168.1.100:8099/jsonrpc?request={"jsonrpc":"2.0","method":"Application.GetProperties","params":{"properties":["volume"]},"id":1}](http://192.168.1.100:8099/jsonrpc?request=%7B%22jsonrpc%22:%222.0%22,%22method%22:%22Application.GetProperties%22,%22params%22:%7B%22properties%22:%5B%22volume%22%5D%7D,%22id%22:1%7D)
> responds with: { "message": "401 - Missing access token", "name": "ResponseException", "status": 401, "statusText": "401 - Missing access token" }
> I'm using the local node server method, the console shows 401 - missing access token errors.

this test is not meant for the node server, this request should target kodi. but since the notification from the node server works, this test is no longer necessary.

> This does work if I manually type in the access token at this url, the message does show up in Kodi:
> http://miketunes.dyndns.org:8099/

thats great, this tells us, that everything is  finde between the node server and kodi, the issue has to be between node and IFTTT.

> Here's my ifttt recipe: https://imgur.com/a/NyKN5Kn

hmm the applet looks fine, on what device are you configuring the applet?
we had issues with iphone in the past, maybe try to create the applet from scratch on a PC?

**Comment by keydon** [comment]
> I did create the applet from the PC, should I try on android instead?

hmm no, PC should be fine. very mysterious :o
maybe rewrite the body from scratch by hand, no copy&paste and no characters before and after the curly braces.

**Comment by miketunes** [comment]
I got it working now, had to reboot my pc, guess it was something with the node server.
