### ISSUE TITLE
Phrase broker - can you customize the phrases?

### ISSUE THREAD

**Issue by miketunes** [OmerTu/GoogleHomeKodi#341]
Do I need to say "Kodi toggle party mode" or could I change that to "Kodi start the party"?

**Comment by miketunes** [comment]
Is there a direct URL for this command, I'd like to simplify it to "Next Song" "Hey Google, kodi playlist next"?

**Comment by keydon** [comment]
> Do I need to say "Kodi toggle party mode" or could I change that to "Kodi start the party"?

out of the box, only "start the party" is available. But you have multiple options:
1. ask here for a new phrase to be added (pro: not much effort, con: can take a while)
2. extend the broker yourself and make a pull request (pro: quick, con: a little effort)
3. copy a broker-file and change it up however it suits you (see readme steps for "add a new language") (pro: easy & flexible, con: only benefits you, not the rest of us)

> Is there a direct URL for this command, "Hey Google, kodi playlist next"? I'd like to simplify it to "Next Song"

what do mean with direct?
is `YOUR_NODE_SERVER/playercontrol?q=next` direct?
or `YOUR_NODE_SERVER/broker?phrase=playlist next`?

**Comment by miketunes** [comment]
YOUR_NODE_SERVER/playercontrol?q=next worked, thank you.
