### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by Alfiegerner** [OmerTu/GoogleHomeKodi#343]
Hi,

I have a PR for adding seren searches I'd like to get through.

I'd inadvertently left it with broken linting, sorry about that. But just come back and fixed and seen it can't be merged due to other issues in the project, starting from this commit https://github.com/OmerTu/GoogleHomeKodi/commit/a9c72beda6ac1995790ca7ddf7e540bf0415b0c2.

Can we fix the build to allow this and future PRs?

Thanks.

**Comment by keydon** [comment]
build fixed and pr merged with adjutment to the phrases
