### ISSUE TITLE
Feature request: audio versions of video playback controls

### ISSUE THREAD

**Issue by Scefing** [OmerTu/GoogleHomeKodi#35]
I.e. Have the assistant be able to do for audio what it can for video. I primarily use my kodi setup to play my music, so the video controls aren't useful to me.

I'm not a js dev, but I think that the audio commands can essentially be copied and edited from the video commands, so I'm going to try my hand at this and hopefully be able to post a PR.

**Comment by damianodonoghue** [comment]
I have added the requested and made a poll request

**Comment by keydon** [comment]
@p0psicles @OmerTu plz close this, pull request already merged.
