### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by anthony19801** [OmerTu/GoogleHomeKodi#36]
Hi, I have tried every which way to get this to work, but unfortunately, nothing. 
I'm by no means a coder of any description, to be honest I've had no idea how to forward a port. I've had to look that up. Even after doing that, I followed the instructions to the letter, several times over, and still absolutely nothing. I'm feeling a bit stupid even saying this to be honest, but I'm finding it pretty frustrating now. Can someone please tell me where I could be going wrong? I'm on the verge of tearing my hair out!

**Comment by p0psicles** [comment]
The more you try yourself and the more info you provide the better we can help. We can't do anything with the info you provided.

**Comment by keydon** [comment]
Closed due to inactivity
