### ISSUE TITLE
Play specific Episode clarification

### ISSUE THREAD

**Issue by atomicsunset** [OmerTu/GoogleHomeKodi#39]
I've successfully installed and have most features working, but I can only play unwatched TV episodes. The change log says that you can ask it to play a specific Episode from a show from a season. The guide only explains how to setup for show and Episode number, not season. Could you update the information to show syntax for including season and what syntax to use in IFTTT. Thank you for a well documented guide and your hard work.

**Comment by OmerTu** [comment]
Hey,
There is a more detailed explanation in the guide (see [this](https://github.com/OmerTu/GoogleHomeKodi#setting-up-other-actions) for more info)

In short, choose "Say a phrase with both a number and a text ingredient"
Use a phrase similar to: "Kodi play $ episode #"
Once you follow these instructions, you could say the following to trigger a specific episode in a specific season:
"OK Google, kodi play bla season 4 episode 1"  
(i.e. the $ part should include the tv show name, then the explicit word "SEASON" and then season number)
