### ISSUE TITLE
Access Token error?

### ISSUE THREAD

**Issue by markadamhfx** [OmerTu/GoogleHomeKodi#44]
When I set up everything as described exactly, it doesn't work.

When I run the TROUBLESHOOTING line provided:

`http://YOUR_EXTERNAL_IP:PORT/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}`

it connects and asks me for a password/username, but then returns the following:

`{"error":{"code":-32100,"message":"Failed to execute method."},"id":1,"jsonrpc":"2.0"}`

When I enter the actual URL of my glitch project:

`YOUR_GLITCH_SERVER_ADDRESS/playpause`

It returns this error in my LOGS on Glitch:

`(node:95) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): You should configure an access token, to secure your app.`

When I run the command as a voice command through Google Assistant with everything set up, my Glitch project log returns this:

`Request token = guest`
`Authentication succeeded`
`Play/Pause request received`
`Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.PlayPause","params":{"playerid":1}}`

but nothing actually happens.

What am I missing? I'm a newb at github coding. Any help would be appreciated.

**Comment by p0psicles** [comment]
Make sure you have configured the kodi op address. That's your external ip. And make sure your used kodi username pass is correct.

**Comment by p0psicles** [comment]
All the tests you did above should actually fail.
You need to address your Glitch app, with a proper url + authentication token configured in the json body. You could also test it using a chrome extension named `Postman`.

If you check out the develop branch, there is a new route in there. /koditestconnection.
It provides some more logging. As also shows a notification in kodi, if the connection is okay.
Can you try that one?

**Comment by keydon** [comment]
Closed due to inactivity
