### ISSUE TITLE
Close of pvr functions

### ISSUE THREAD

**Issue by mirecekd** [OmerTu/GoogleHomeKodi#48]
Hi,

pvr functions (kodiPlayChannelByName, kodiPlayChannelByNumber) are not closing properly towards IFTTT, 

IFTTT applet works, but stays in Applet skipped state and after few attempts it will stop for couple of minutes.

I added dirty fix:  `response.sendStatus(200);` at the end of both functions and applet in IFTTT works properly.

As not JS master did not do check of end code status.

Could you look at, please?

Thanks
Mirek

**Comment by p0psicles** [comment]
Should be fixed in develop. Can you test?

**Comment by mirecekd** [comment]
Hi,

devel version works as expected. Good to add return code to all functions :-)
