### ISSUE TITLE
Do I really need to create local server for multiple installation of Kodi?

### ISSUE THREAD

**Issue by mwink4689** [OmerTu/GoogleHomeKodi#51]
I am extremely new to this, so please excuse me for my lack of knowledge. You gave such great directions on how to make Google Home work with Kodi and believe it or not, I got to work flawlessly. The problem is that I am setting up a second installation of Kodi in another room and I'm not able to understand and make work your local server instructions (for many reasons). So trying to keep this simple, I would like to know if I can just add an additional installation entry in the kodi-hosts.config.js.dist file. That is, not create a kodi-hosts.config.js file and just add another id such as "living room" and use the same external IP address, the same port, same username, and the same password in the kodi-host.config.js.dist file. Then when I create all the new IFTTT files, all I'll have to do is change the body to include the new room id. Bottom line, do I really need to create a local server to use the second installation of Kodi?

**Comment by maffbm** [comment]
Just an idea, if you're happy setting up duplicate IFTTT for each Kodi instance...
use different ports for each Kodi, set port forwarding for each one on your router
copy your glitch project for each one and change the port in the env file
set IFTTT to something like:
Play $ on TV
in Webhooks make sure it has the glitch server URL for the project pointing at your TV
then another one:
Play $ in the bedroom
in Webhooks make sure it has the glitch server URL for the project pointing at the bedroom

**Comment by mwink4689** [comment]
Thank you, worked like a charm!!!!!
