### ISSUE TITLE
Issue starting local nodejs

### ISSUE THREAD

**Issue by mediavanpe** [OmerTu/GoogleHomeKodi#54]
Hello,

Great work, i love the idea of using google home with kodi. But i have an issue when i try to use the local webserver.
I configured the kodi-hosts.config.js with my kodi info (IP, port, user, password), I changed the authtoken and left the default listenerport (redirected by my routeur). But when I want to start the server, I get this error : 
```
const express = require('express');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Do you have any idea what I'm missing ?

Thanks for your help

**Comment by Stefan300381** [comment]
forgot to install dependencies? iirc: npm install

**Comment by mediavanpe** [comment]
Which dependencies are needed ?
I installed npm, node and nodejs, and did a " npm install express" too

**Comment by p0psicles** [comment]
Your on node4. Upgrade to 6 minimum. 8 preferred.

**Comment by p0psicles** [comment]
@omertu should we mention the minimal required  nodejs version?

**Comment by mediavanpe** [comment]
Thanks for your help. It works 👍 
# node server.js
Loaded 1 hosts from the config.js
Starting using kodi-hosts.config.js, {"authToken":"*******","listenerPort":"8099","youtubeKey":"********"}
Your app is listening on port 8099

Is it normal to have this message : "Cannot GET /jsonrpc" when I try : 
http://<IP>:<Port>/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22id%22:1,%22method%22:%22Player.playpause%22,%22params%22:{%22playerid%22:1}}

**Comment by p0psicles** [comment]
Your testing your kodi api? I think you should use a post and make sure you are authenticated.

If you check out the develop branch there is a /koditestconnection route that you can use to test the end2end communication.

**Comment by keydon** [comment]
> Is it normal to have this message : "Cannot GET /jsonrpc" when I try :
http://:/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22id%22:1,%22method%22:%22Player.playpause%22,%22params%22:{%22playerid%22:1}}

you seem to mix up the endpoints. the error you get is a nodejs error from our middleware.
but the request you are sending looks like it is meant for kodi.

**Comment by keydon** [comment]
Closed due to inactivity
