### ISSUE TITLE
Wont work for me caused by ipv6

### ISSUE THREAD

**Issue by Beliar-666** [OmerTu/GoogleHomeKodi#56]
Hello. This wont work to me. I only have a public ipv6 Adress.
I set up everything correctly, google home answers me with the right answer but nothing happens on my Rasp running Kodi

**Comment by Beliar-666** [comment]
Glitch Log:
`Loaded config from .env
12:35 AM
📉👹 Your app is listening on port 3000
12:35 AM
4 minutes ago
SyntaxError: Unexpected token L in JSON at position 9
12:36 AM
    at Object.parse (native)
12:36 AM
    at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)
12:36 AM
    at /app/node_modules/body-parser/lib/read.js:121:18
12:36 AM
    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
12:36 AM
    at done (/app/node_modules/raw-body/index.js:213:7)
12:36 AM
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
12:36 AM
    at emitNone (events.js:86:13)
12:36 AM
    at IncomingMessage.emit (events.js:185:7)
12:36 AM
    at endReadableNT (_stream_readable.js:974:12)
12:36 AM
    at _combinedTickCallback (internal/process/next_tick.js:80:11)`

**Comment by p0psicles** [comment]
There seems to be going something wrong with parsing the requests body.
Maybe search for known issues using body-parser with ipv6?

**Comment by Beliar-666** [comment]
I now tried any things. In my local network everything works fine. Its only a Problem that my Kodi is not reachable from outside...
My Fritz!Box is reachable from Outside if i try to connect via Dynamic DNS Host.

**Comment by p0psicles** [comment]
But apparently it's already having issues connecting to glitch. Which is odd. As glitch is hosted on ipv4. From the logs it doesn't error on trying to connect to your public ip.

**Comment by Beliar-666** [comment]
Yes. now i got the test working with my.public.ip:xxxx/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.playpause","params":{"playerid":1}}   Player paused. But if i Try with voice i got same error as above.
I did everything like explained on the Codepage. I don´t know where the error is. I´m not very good in programming

**Comment by p0psicles** [comment]
Can you setup the route ... /koditestconnection? And report back?

**Comment by Beliar-666** [comment]
I don´t know how. But i´ve a screen from ifttt. 
![ifttt](https://user-images.githubusercontent.com/27926921/33454117-1e75a2e2-d618-11e7-8bd9-b9d09009ca2c.JPG)

**Comment by Beliar-666** [comment]
How to set up the route and test the connection?

**Comment by p0psicles** [comment]
Like the /scanlibrary but now in the URL replace scanlibrary with koditestconnection. You can think  of a simple phrase yourself.

**Comment by Beliar-666** [comment]
Same Error with /koditestconnection.

**Comment by p0psicles** [comment]
Can you share your iffft config?
