### ISSUE TITLE
Do I use quotation marks?

### ISSUE THREAD

**Issue by mannyman** [OmerTu/GoogleHomeKodi#6]
KODI_IP="192.168.1.1"  <-- Quotation marks
or 
KODI_IP=192.168.1.1

where ip address is internet IP not local LAN IP

Thanks (sorry for noob question),
Manny

**Comment by OmerTu** [comment]
Yes, you should use quotation marks for the IP (and all other values)

**Comment by mannyman** [comment]
Thanks
