### ISSUE TITLE
Request Timeout

### ISSUE THREAD

**Issue by mmschmutter** [OmerTu/GoogleHomeKodi#60]
Hi,

All the parts of this project seem to work independently for me (including the tests outlined at the end of the README), but when I try to execute a command from Google Assistant, I get the following error message in the Glitch log:

Request token = XXXXXX
12:57 PM
Authentication succeeded
12:57 PM
Movie request received to play "baby driver"
12:57 PM
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies"}
12:57 PM
{ FetchError: request to http://XX.XXX.XX.XX:XXXX/jsonrpc failed, reason: connect ETIMEDOUT XX.XXX.XX.XX:XXXX
12:59 PM
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
12:59 PM
    at emitOne (events.js:96:13)
12:59 PM
    at ClientRequest.emit (events.js:188:7)
12:59 PM
    at Socket.socketErrorListener (_http_client.js:309:9)
12:59 PM
    at emitOne (events.js:96:13)
12:59 PM
    at Socket.emit (events.js:188:7)
12:59 PM
    at emitErrorNT (net.js:1277:8)
12:59 PM
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
12:59 PM
    at process._tickCallback (internal/process/next_tick.js:104:9)
12:59 PM
  name: 'FetchError',
12:59 PM
  message: 'request to http://XX.XXX.XX.XX:XXXX/jsonrpc failed, reason: connect ETIMEDOUT XX.XXX.XX.XX:XXXX',
12:59 PM
  type: 'system',
12:59 PM
  errno: 'ETIMEDOUT',
12:59 PM
  code: 'ETIMEDOUT' }

Any help would be appreciated. Thanks!

**Comment by keydon** [comment]
Well its most likely a _port forwarding issue_.
So if you successfully tested the kodi-rpc call from the readme-troubleshot-section with your external ip **within** your own network, that does not actually mean that the port is indeed reachable **from the internet**. Some routers do shortcuts in those cases.
To really test that you have to truly connect **from _outside_** (i.e. mobile phone with disabled wifi)
