### ISSUE TITLE
Is it Possible to Control Kodi Installed in FireTV using Google home from the Procedure provided ?

### ISSUE THREAD

**Issue by heyvimo** [OmerTu/GoogleHomeKodi#61]
Hello !!

a. Is it possible to control Kodi installed inside the FIreTV using google home voice control? using similar steps provided in the thread?

b. I assume, the steps provided is for Kodi installed in the laptop and the flow was like : 
Google Home -> IFTTT -> Router [Port Forwarded To Laptop IP] -> Control Kodi [Installed in Laptop]

c. BUT, I have my Kodi installed in Amazon Fire TV. Now the setup is like,
    Kodi [Fire TV] and Google Mini -> Both are connected to Same WiFi Network . Can voice control to Google Mini be controlled via IFTTT -> to the Kodi [in Fire TV] and control the Kodi options ?

It would be great if anyone throw some light on this possibility !! Have a gr8 Time !!

**Comment by p0psicles** [comment]
Doesn't matter where kodi is installed. As long as the kodi api is accessible.

**Comment by p0psicles** [comment]
I could run a test trying to control kodi running on my android phone.
LOL maybe I could use Google assistant on that same phone.

**Comment by heyvimo** [comment]
Hello p0psicles,

Thanks for your response. Any other way to make sure the Kodi API is accessible ?

I tried following the steps provides in the procedure page and when I said "Hey Google, Kodi Play Movie Gladiator", the google responds back saying "I am unable to play from Kodi"!!. Think I am stuck with the router configs + port forwarding etc.

a. In the Kodi -> Settings -> webserver, I choose http, entered the port-id as 8080 and other required details.  [ Note: When I check the system information in Kodi, it shows a different IP number - For Eg: 192.168.66.1. ]
b. In the router for single port forwarding setup page, I tried setting the following. Here I provided my laptop IP number. 
Application Name - Kodi 
External Port - 8080 
Internal Port - 8080 
Protocol To - Choose Both[Do I need to use TCP or both??] 
IP Address - 192.168.1.109 [IP Address from my Laptop. Is this correct ??] 
Enabled - Yes

c. Then in the google I tried checking what is my ip and it provided some "random ip number". So i entered those details in the glitch .env file. Do I need to provide the google provided IP number in the .env file ? or do I need to provide the same number as provided in the router port forwarding ? i.e. 192.168.1.109 ? or the IP number which the Kodi device is showing ??
    KODI_IP="23.256.19.879"
    KODI_PORT="8080"

After setting these defaults and then filling up the applets in the glitch "if this then that". When I tried saying "Hey Google, Kodi Play Movie Gladiator", then the Google mini responds back saying "I am Unable to play from Kodi" ! 

Please share in your inputs ! [ I am circling between IP number of Kodi, Laptop and IP number from Google and getting lost.]

**Comment by Stefan300381** [comment]
In Glitch you provide your public ip address (like  23.256.19.879) and port 8080
In your router (for the port forwarding) you provide the internal IP address of the machine where Kodi is running on (something that begins with 192) and port 8080. You can test the correct address in your browser. For example, do you see the Kodi web interface asking for a username/password when you browse to http://192.168.1.109:8080
If this works, then test with your public ip, like http://23.256.19.879:8080
Please note, some internet connection will change the public ip every day, like in my case. So every day 23.256.19.879 will be something different.

**Comment by heyvimo** [comment]
@Stefan300381 : Thanks a lot for your response. Got some insight from your comments.
a. Kodi is installed in Amazon Fire TV.
b. Now, I changed/set a static IP for my Amazon Fire TV.
c. But still when I checking system details in the Kodi which is launched from Amazon fire TV its picks up a random IP [192.168.49.1] number. Note: Think there is some issue going on when Kodi is installed in Amazon Fire TV and Kodi picks up some random IP number.
d. Good Part is, now I am able to put http://<amazon fire tv static IP>:8080 and I am been asked for the User name and password for Kodi and able to log-in. [Inside the webui I see the IP webacces port as the once which I had set for Amazon TV static IP, but when I switch on Kodi ~ I see a different number.]
e. Next, when I try pining http://<my global ip number>:8080, its just timing out and going un-noticed. I will check on this part. 

**Quickly Wanted to understand the data flow process :** Is it like, 
Voice command From User -> Google Mini -> IFTTT Applet -> Which connects to web-hook API -> Which calls the user defined server launched in Glitch running the Kodi-Git Hub package -> Goes Via Wireless Router -> Port-Forwarded to the Kodi API installed in Amazon Fire TV and controls the Kodi API application ?  Is this the actual data flow that happens ? Can you kindly clarify the same ?

Some followup queries:
a. When I give the Voice commands through Google Mini. This goes to the IFTTT applet right? if so will there be any logs recorded just as some debug ? just to check whatever voice command I provide goes to IFTTT applet ?
b. Similarly if this above step works, then the data goes via Webhook and goes to the Server launched in Glitch. So I can see some logs in the glitch right? Because in the log section all I always see is your API is listerning in the port 3000.... 
c. And in the Glitch Server, in the KODI_IP area, do I need to provide the my gloabl IP addres which I get from google or do I need to provide the IP address of the device [ in my case its the Amazon fire TV] where the Kodi is installed ? Because the end point is the Kodi right?

So meaning I am stuck in the 1st step itself right? Can you kindly clarify my queries and do the needful help.

**Comment by Stefan300381** [comment]
>> c. But still when I checking system details in the Kodi which is launched from Amazon fire TV its picks up a random IP [192.168.49.1] number. Note: Think there is some issue going on when Kodi is installed in Amazon Fire TV and Kodi picks up some random IP number.

Sorry, cannot help with this. Dont' have a fire TV device. Usually either your routers dhcp server will assign the same ip address again automatically (dhcp lease time), or your device is configure to use a static ip address. in both scenarios the ip address will stay the same.

>> d. Good Part is, now I am able to put http://amazon fire tv static IP:8080 and I am been asked for the User name and password for Kodi and able to log-in. [Inside the webui I see the IP webacces port as the once which I had set for Amazon TV static IP, but when I switch on Kodi ~ I see a different number.]

I don't understand. can you share screenshots?

>> e. Next, when I try pining http://my global ip number:8080, its just timing out and going un-noticed. I will check on this part.

Seems your port forwarding doesn't work

>> Quickly Wanted to understand the data flow process : Is it like,
Voice command From User -> Google Mini -> IFTTT Applet -> Which connects to web-hook API -> Which calls the user defined server launched in Glitch running the Kodi-Git Hub package -> Goes Via Wireless Router -> Port-Forwarded to the Kodi API installed in Amazon Fire TV and controls the Kodi API application ? Is this the actual data flow that happens ? Can you kindly clarify the same ?

Yes, correct. From IFTTT to Glitch to your router to Kodi.

>> Some followup queries:
a. When I give the Voice commands through Google Mini. This goes to the IFTTT applet right? if so will there be any logs recorded just as some debug ? just to check whatever voice command I provide goes to IFTTT applet ?

Well, I am not an expert but in IFTTT you can in deed check the "activites"

>> b. Similarly if this above step works, then the data goes via Webhook and goes to the Server launched in Glitch. So I can see some logs in the glitch right? Because in the log section all I always see is your API is listerning in the port 3000....

If I remember correctly glitch runs either on port 80 or 443. In my environment I am running the NodeJS server (like Glitch) on a local Linux machine (running on a complete different port). Here I can check syslog daemon logfile (not sure if something like this is available for Glitch applications)

>> c. And in the Glitch Server, in the KODI_IP area, do I need to provide the my gloabl IP address which I get from google or do I need to provide the IP address of the device [ in my case its the Amazon fire TV] where the Kodi is installed ? Because the end point is the Kodi right?

In Glitch you need to assign your public IP address. Glitch will use this address to connect to your router, the router will then forward the request to your internal ip address of the kodi device (via port forwarding).

Stefan

**Comment by heyvimo** [comment]
Hello Stefan,

Thanks for your response.

a. Attaching the snapshot of the kodi web-page when I access it using http:// [amazon fire tv static ip]:8080. [My kodi is installed in amazon fire tv and have set a static ip for it.]
<img width="1163" alt="screen_shot_kodi_api_accessed_using_static_ip_of_fire_tv" src="https://user-images.githubusercontent.com/33966812/33422236-e0205de2-d569-11e7-9b85-a56bb1a95066.png">

This is the screenshot showing the static ip which I had set for amazon fire tv:
<img width="793" alt="scshot_kodi_webui_when_access_using_amazon_firetv" src="https://user-images.githubusercontent.com/33966812/33422801-acd12b9a-d56b-11e7-9ae9-cd87cd195901.png">

This is the screenshot of kodi system info after launching it in the tv:
<img width="580" alt="screen shot 2017-11-30 at 1 09 09 am" src="https://user-images.githubusercontent.com/33966812/33422839-cc206434-d56b-11e7-8874-9b9541a5111b.png">


b. I am now confused on the port forwarding part as you said its not working properly. Since I wanted the commands to be port forwarded to my Kodi which is installed in my amazon fire tv, I have entered the details of my fire tv as given below.
<img width="622" alt="pf stp router" src="https://user-images.githubusercontent.com/33966812/33422473-a7cd292e-d56a-11e7-84b5-57a6b4f7fa39.png">

<img width="572" alt="port forwarding setup in router" src="https://user-images.githubusercontent.com/33966812/33422339-3c83d8a2-d56a-11e7-8467-0518e3121e82.png">

When you say public ip ? this is nothing but the IP address which gets displayed when i enter "what is my ip" in google ? or its the randomly picked up Ip address provided by my wireless router?

Kindly clarify these queries. Thanks a lot !

**Comment by Stefan300381** [comment]
Does your Amazon device have two network adapters, like WiFi and LAN? This would explain the two different IP addresses. According to your routers screenshot I assume all of your devices use the 192.168.1.X subnet (and not the ...49.X). Thus I would just use 192.168.1.101 and NOT the .49.1. (as shown in your screenshot).

Btw: This web page shows your public IP address: http://whatismyip.org/
Does this differ from something you see in your wireless router?? 
What is your routers internal ip address? Is it 192.168.1.1 or similar?

**Comment by heyvimo** [comment]
Hello Stefan,

a. The Amazon fire TV can be connected via wired or wireless connection. So I assume the Fire TV has both wired+wireless adapters. Bw for the wired connection also I had setup static IP.
b. When I connect the Amazon fire TV using either wired or wireless connection, and when I launch the Kodi Application, in the system information it always shows same default IP and MAC address. Think there is some issue in the Amazon Fire TV + Kodi combination. [I will dig at my end in the Internet for this issue.]
c. **Yes Stefan its different. When I click the link you provided this shows some IP address and that is different from the dynamic IP address generated from the router.** 
d. Yes the router internal IP address is the default 192.168.1.1.

So looks like there is some issue with the IP address that gets generated b/w the router and the search in the google "what is my ip". Can you confirm the same? If you have any other suggestions its highly welcome! Appreciate all your help.

**Follow-Up Query:**
a. If you see here, both Amazon Fire TV which runs Kodi is connected to the Wireless Network, and then the Google Mini is Connected to the Similar Wireless network. 
b. We have launched the Side-Server in the Glitch. Then why do I need the laptop's dynamic [or best static] IP address to be provided in the Glitch Server ? And every-time I wanted to launch Kodi using Google assistant, do I need to launch the Glitch Server again n again in my Laptop? or Just switching on once is enough?

**Comment by keydon** [comment]
any updates on this issue? whats the current status

**Comment by heyvimo** [comment]
@keydon  Was able to resolve the issue. You can close this ticket! Thanks to all !!

**Comment by vlamikov** [comment]
How was this issue resolved? I have the same issue. Thx!
