### ISSUE TITLE
[request] Play movie from where stopped

### ISSUE THREAD

**Issue by maffbm** [OmerTu/GoogleHomeKodi#63]
Not sure if this is possible, but would it be possible to add a command that will allow us to continue watching a movie from where we left off?

I know you can jump straight to a time, but what if it's a few days later and you can't remember where you were?

"Hey Google, Kodi continue playing $"

Does that make sense?

EDIT: I believe it could be Player.Open > Resume = true
http://kodi.wiki/view/JSON-RPC_API/v6#Player.Open

Thanks

**Comment by maffbm** [comment]
never mind, figured it out :D
I've now made "Play $" have the resume: true option and added "play $ from the start" as an option

**Comment by Stefan300381** [comment]
can you please explain how you did this or initiate that this will be implemented into the project? :-)

**Comment by maffbm** [comment]
sure, this is in develop branch!
in helper.js I copied lines 692 to 708 and pasted on line 709 and changed exports.kodiPlayMovie to exports.kodiPlayMovieFromStart
back up on line 703 add (include the comma at the start!):
,
			options: {
				resume: true
			}

then on server.js, copy lines 109 to 115 and paste on 116
on line 109 change '/playmovie' to '/playmoviestart' and on line 111 change kodiPlayMovie to kodiPlayMovieFromStart

then create the IFTTT applets:
Play $
point to /playmovie?q={{TextField}} (as before, but if you're partway through the movie it will start from there)

Play $ from the start (or beginning)
point to /playmoviestart?q={{TextField}}

There's probably an easier way the devs can put this in than the way I've done it, but it works for me!

**Comment by Stefan300381** [comment]
awesome! especially if it's in develop branch
