### ISSUE TITLE
You should configure an access token, to secure your app.

### ISSUE THREAD

**Issue by Try2Fly** [OmerTu/GoogleHomeKodi#64]
Hi, I'm trying to use this, but I get this message:
You should configure an access token, to secure your app.

I'm certain that I included an auth_token and this is the same in IFTTT, I also get this message when trying the url in postman.

Don't know what I'm doing wrong

Log from glitch:
9 minutes ago
node v6.10.3, npm 3.10.10
11:20 PM
Installing...
11:20 PM
9 minutes ago
Loaded config from .env
11:21 PM
🌁🌻 Your app is listening on port 3000
11:21 PM
a few seconds ago
Error trying to validate the request. Error: You should configure an access token, to secure your app.

**Comment by keydon** [comment]
Are you sure you have configured you token like so:

![image](https://user-images.githubusercontent.com/2421541/33462050-9ca922e8-d635-11e7-9ff3-221736712ed1.png)

**Comment by keydon** [comment]
Closed due to inactivity
