### ISSUE TITLE
Facing Issue While Using Both External Server and Internal Local Server !!!

### ISSUE THREAD

**Issue by heyvimo** [OmerTu/GoogleHomeKodi#68]
Hello Folks,

Facing issues while running in both external glitch server an internal local host!

**a. Issue faced in Glitch Server:**
    1. Finally I was able to set up IFTTT, Glitch, port forward etc and get the google mini connected.
    2. When I say "Kodi Play Titanic", I get the error shown in the below snapshot. 

<img width="553" alt="ss_while_running_external_srv_error_log_in_glitch_server" src="https://user-images.githubusercontent.com/33966812/33519422-f2a35828-d75a-11e7-99ea-e3b7c5b87635.png">

 Is the program in glitch server automatically searches for movie and runs from Kodi or does it look out for movies in our video add-ons and play ? or how does it work?

**b. Issue faced while using the Local Host Server:**
    1. Followed all the steps and when I launch the localhost, I see the "Your app is listening on port 8099".
    2. 1st, When I tried saying "hey google, kodi play titanic" - I don't see anything happening in the local server terminal. Query here is, does "WebHooks works only using external server? Because thats the note I see under webhooks app in IFTTT. Won't it work using localhost ?"
    3. 2nd, just to debug I tried using "postman" to send "playpause" command with the required authentication key I get the below error. When I tried printing the authentication key in the server.js, the token is empty and its failing authentication I think. Not sure why its not picking the authentication key.

<img width="902" alt="ss_localserver_error" src="https://user-images.githubusercontent.com/33966812/33519458-d5cc86c4-d75b-11e7-9b58-31cbef4a4f48.png">

Can anyone please help me on these issues. Any help would be really useful !!

**Comment by maffbm** [comment]
A) I believe that's Kodi not being able to find the movie in your library
B) you can't use localhost, webhooks is online and doesn't know that 'localhost' is, it needs your external IP address

**Comment by keydon** [comment]
Ad A) You seam not to have a single movie in your library, that wont work for you.

B) doesn't really matter with an empty library ;o

**Comment by heyvimo** [comment]
@maffbm : Gotcha !! So either I should use external ip address for local host or use glitch server for external server.

@keydon : a. So do I need to add movies to my local library? b. So even if you want to play any tv shows, do I need to add it as separate list so that Kodi can play from it ? Won't the program automatically searches from the video addon's and play ?

Kindly clarify the same ! Appreciate your comments !

**Comment by keydon** [comment]
Well kodi is meant for local files similar VLC or windows media player. But you are right, it can also be used to play YouTube or other streams.
So for Youtube you can try /playyoutube instead of /playmovie

**Comment by keydon** [comment]
Other streaming add-ons are not yet supported

**Comment by maffbm** [comment]
It doesn't use video add-ons.
You add a folder for movies and it goes away and finds all the info about them. You add a folder for TV shows and it goes away and finds all about them and on your main menu screen you have Videos, TV Shows and Movies.
It's the way Kodi's always worked and what it was originally made for, but recently there's more and more people using it just for streaming stuff.

**Comment by heyvimo** [comment]
THanks folks. But one more query:

a. Is it possible to add movies from add-ons to the movie folder on the Kodi main menu?

I tried adding movies from add-ons but its not seen in the main menu .. Is there a way to add instead of adding movies from local drives or so ?

**Comment by maffbm** [comment]
Don't think so

**Comment by heyvimo** [comment]
@maffbm THanks a lot for the clarification. So even for the TV shows do I need to locally have the required TV shows in the TV folder in the Kodi home directory ? How do you play them ? You have the movies, TV shows in the external hard-disk and access from it ? is it ? Kindly let me know the same. THanks !
