### ISSUE TITLE
Where would you edit the env file?

### ISSUE THREAD

**Issue by dannieboiz** [OmerTu/GoogleHomeKodi#7]
Does this look right?
``# Environment Config

# store your secrets and config variables in here
# only invited collaborators will be able to see your .env values

# reference these in your code with process.env.SECRET

SECRET=
MADE_WITH=

# note: .env is a shell file so there can't be spaces around =
KODI_IP=abc.com
KODI_PORT=8282
KODI_USER=kodi
KODI_PASSWORD=kodi
AUTH_TOKEN=kodi`

**Comment by MrLachdanan** [comment]
That worked for me, but i left the " " in place.
