### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by warlord0** [OmerTu/GoogleHomeKodi#74]
Thought I'd say thanks for this. Great little project and thought I'd share a spin off I'm working on based on your code.

I thought it might be useful to do something similar with Sonarr and your use of express and node-fetch lends itself well to be able to proxy Google Home requests there too.

Very early days with a few more tweaks to do, but so far working as I need .

https://github.com/warlord0/GoogleHomeSonarr

**Comment by keydon** [comment]
thanks for sharing
