### ISSUE TITLE
Unable To Play The Movie From Movie Folder in Kodi Home

### ISSUE THREAD

**Issue by heyvimo** [OmerTu/GoogleHomeKodi#76]
Hello All,

a. As suggested, just to try I added a movie say 'Jurassic Park Part 1' onto the Movie folder in the Kodi home with the use of pen-drive via network.
b. When I say, Hey Google Kodi Play 'Jurassic Park Part 1', the google says 'Ok Playing Jurassic Park Part 1'.
c. But nothing happens and when I check the logs in the glitch server, I see the below error.
<img width="549" alt="screen shot 2017-12-07 at 12 12 28 am" src="https://user-images.githubusercontent.com/33966812/33705191-311d0040-dae4-11e7-9a79-8382775e8a6e.png">

Query: Which is the VideoLibrary in the command that gets called ? And how does this API works VideoLibrary.GetMovies ? Please provide your comments/inputs.

Where should I add the shared movies etc locally in Kodi ? Do I need to add it in the Movie folder in Kodi home? or somewhere else ?

**Comment by p0psicles** [comment]
You have to set content on your movie folder in kodi. Meaning it has to be added to the kodi library.

**Comment by heyvimo** [comment]
@p0psicles  Awesome.. Huff.. final got it working.. Mistake was didnt add the required tag to the movie folder.. 

This is mainly to play around with stuffs from local movies, shows, files etc.. It would be great if we can add support to play from particular add-onn.. for eg "Hey google, kodi play jurassic park from Exodus or Covenant" ... Is that option available ?

**Comment by p0psicles** [comment]
I doubt it. Would need to be added to kodi api by addon dev.
