### ISSUE TITLE
IFTTT including 'of' in the ingredient

### ISSUE THREAD

**Issue by konradwalsh** [OmerTu/GoogleHomeKodi#79]
If the show is a singular word like Dynasty the it seems it cant match the show name. 

This is because IFTTT is passing 'of Dynasty' as the textfield .
However I find with longer tv show names, it still works even though 'of' is passed

`Authentication succeeded
TV Show request received to play "of dynasty"
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetTVShows","params":{"properties":["file"]}}
Searching for next episode of Show ID 327...
Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetEpisodes","params":{"tvshowid":327,"properties":["playcount","showtitle","season","episode"],"sort":{"order":"ascending","method":"episode","ignorearticle":true}}}
Error: no results
`

![image](https://user-images.githubusercontent.com/7996482/33765180-9a0a27fa-dc0f-11e7-943a-05f3de671cb4.png)

**Comment by keydon** [comment]
i never noticed the additional "of" beeing part of the text-field. its not ideal, but should not be a problem either. we dont expect the spoken title be an exact match of the actual show title. we perform a fuzzy search.

And according to your log, it found the show just fine. But the show seems not to contain any episodes at all.

**Comment by gbaldridge** [comment]
Just seen this. Same issue. Removed an OF in the response section of IFTTT and it 'corrects" it. Having thhe same issue with the TV Show Ballers.

**Comment by keydon** [comment]
closing this issue.
1. the original author was inactive for a while now
2. the additional "of" was fixed in the meantime
