### ISSUE TITLE
Invalid applet

### ISSUE THREAD

**Issue by chefffe** [OmerTu/GoogleHomeKodi#84]
Hello,

choosing a movie via google home mini works fine with my Openelec Kodi setup and GoogleHomeKodi.

I have a problem with IFTTT with the error "invalid applet".
The applet is configured by the manual:
![unbenannt](https://user-images.githubusercontent.com/34404580/33848764-0162eb84-deaf-11e7-80ff-ec2babade948.JPG)

Whats wrong with my applet?

**Comment by keydon** [comment]
well the part visible in your screenshot looks good.
But you are in an advanced applet maker mode for publishing, on purpose?
I guess you wanted to go here: https://ifttt.com/create/ then click on the huge blue "this".

**Comment by keydon** [comment]
closed due to inactivity
