### ISSUE TITLE
[Request] Have "play next episode" populate playlist

### ISSUE THREAD

**Issue by Christyguy** [OmerTu/GoogleHomeKodi#89]
I would love it if when a TV episode was started (specifically the first unwatched episode) that Kodi would queue all the remaining episodes from the season. Basically duplicate what Kodi does when selecting an episode when the option "play the next video automatically" is turned on.

**Comment by PrSinister** [comment]
Have you tried installing this:

https://kodi.tv/addon/services/nextup-service-notification

**Comment by Christyguy** [comment]
Hmmmm. I was hoping to be able to skip to the next episode while current is still playing as well, but this service may solve the issue of playing the next video automatically. I will give it a try. Thanks!
