### ISSUE TITLE
New episodes and new movies

### ISSUE THREAD

**Issue by duduke** [OmerTu/GoogleHomeKodi#9]
Can you add an option for Google Home to read out what new episodes and new movies have been added today?

Something like: "Hey Google, ask kodi about new episodes", "Hey Google, ask kodi about new movies"

**Comment by McMoobud** [comment]
I'm assuming you could use this to structure your own commands:

http://kodi.wiki/view/JSON-RPC_API/Examples

But I'm not sure you could get Google Home to actually read them back. I might be wrong though !

**Comment by jansverre** [comment]
I must say i really love this!! I would be happy if i could ask kodi to just show me recently added movies and tv shows. But the link provided might help me with this. Great work on this :-D

**Comment by OmerTu** [comment]
It's possible to get the latest episodes or movies, but as of now it's impossible to get Google Home read them back.

**Comment by McMoobud** [comment]
I'm loving your work dude. It's great. Thankyou!!!

**Comment by p0psicles** [comment]
I'm working on adding api.ai support. And with that, this feature would become possible. IFTTT does not support it.

**Comment by keydon** [comment]
A feature, where you can open the kodi views of recently added episodes/movies has been added to master.
thats the best we can do atm. #125
