### ISSUE TITLE
[REQUEST] Turn on the TV works. What about the turning it off function?

### ISSUE THREAD

**Issue by Garret** [OmerTu/GoogleHomeKodi#91]
I have set up GoogleHomeKodi and everything works fine, even the turning on the TV via CEC. However, I would really like also to command my tv to turn off with the Google Assistant. That would be very convenient while I am in bed and do not want to look for the TV remote. 

I am currently using Kodi on Retropie (Raspberry Pi 3) and I have installed a local node.js server. 

Do you know if that is possible? Thank you very much in advance.

**Comment by OmerTu** [comment]
I couldn't get kodi to turn off my tv.  It might be just a limitation with my own tv.
See if running the following in your browser turn off your tv:
`http://KODI_INTERNAL_IP:KODI_PORT/jsonrpc?request={"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.json-cec","params":{"command":"standby"}},"id":1}`

Apparently if you have chromecast  plugged in the tv, you can simply say "turn off tv" (see - [http://www.androidpolice.com/2017/10/05/can-now-turn-off-chromecast-connected-tv-google-home-command](http://www.androidpolice.com/2017/10/05/can-now-turn-off-chromecast-connected-tv-google-home-command/)

**Comment by Garret** [comment]
I gave that command and on my browser I get this string:
`{"id":1,"jsonrpc":"2.0","result":"OK"}`
However, nothing happens. 

I know that if I have a chromecast it will work (I already tried that) but, unfortunately, I do not have one :/

I will probably buy one if it is not possible. Thank you in the meanwhile!

**Comment by p0psicles** [comment]
Instead of standby try toggle?

**Comment by Garret** [comment]
@p0psicles I had also tried that command after reading more into the README of the referring script but it does not work as well :(

The question is: does that command work for you?

**Comment by keydon** [comment]
i use /shutdown to turn everything off: kodi, AVR and tv. did you play around with the cec-settings within kodi?

**Comment by Garret** [comment]
@keydon sorry how do you exactly give that command and set it up for GoogleHomeKodi? Could you be more precise?

**Comment by keydon** [comment]
@Garret what do you mean? its set up like any other command, nothing special here,

and how to set up CEC in kodi itself is described here: http://kodi.wiki/view/CEC

**Comment by Garret** [comment]
I tried the "shutdown"command and it closes Kodi but the TV stays on while trying with a Chromecast I am sure the TV should also able to turn itself off

**Comment by Gramps** [comment]
> I couldn't get kodi to turn off my tv. It might be just a limitation with my own tv.
See if running the following in your browser turn off your tv:
http://KODI_INTERNAL_IP:KODI_PORT/jsonrpc?request={"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.json-cec","params":{"command":"standby"}},"id":1}

How would I add this as a voice command?  It works great with my TV.

**Comment by keydon** [comment]
try reading the readme.
https://github.com/OmerTu/GoogleHomeKodi#c-set-up-ifttt-with-your-google-home

**Comment by keydon** [comment]
sorry, support for standby is not added yet. it will come

**Comment by Gramps** [comment]
It's OK; I did double-check the readme prior and didn't see it.  Noted that it is not yet added.  I'll keep an eye out for the update.  Thanks!

**Comment by keydon** [comment]
```
/standbytv
```

Feature is now available in master #122
