### ISSUE TITLE
Trouble with external IP and port forwarding

### ISSUE THREAD

**Issue by bronsonmcsmash** [OmerTu/GoogleHomeKodi#95]
Hey guys,  

Pretty excited about getting this to work but so far no luck.  Basically I was able to do the test where I pasted the line into the browser and it worked for internal ip.  But as soon as I used my external Ip and it doesn't work.  It says your internet connection is currently down.   (but my internet is working fine)  Is this because of port forwarding or something.  Am I supposed to try and turn that on or off.

**Comment by srmysqldba** [comment]
@bronsonmcsmash ,
In order to use your public ip you will need to set up port forwarding in your router. I also want to add that if you dont have a static ip from your isp, I would set up a free dns service. This way if your isp issues you a new ip you dont have to update your calls.

**Comment by keydon** [comment]
closed due to inactivity.
