### ISSUE TITLE
Syntax Error but test with URLs from Troubleshoot works

### ISSUE THREAD

**Issue by Beliar-666** [OmerTu/GoogleHomeKodi#96]
Hello, 
got following error If i Try to start a Movie

`SyntaxError: Unexpected token L in JSON at position 9
    at Object.parse (native)
    at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)
    at /app/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
    at done (/app/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
`

and the following if i try to Pause

`Request token = Loli1974
Authentication succeeded
Play/Pause request received
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.PlayPause","params":{"playerid":0}}
Command sent = {"jsonrpc":"2.0","id":1,"method":"Player.PlayPause","params":{"playerid":1}}
(node:325) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): FetchError: request to http://http://openelec.selk8kqa8kbebbks.myfritz.net:8080/jsonrpc failed, reason: getaddrinfo ENOTFOUND http http:80
(node:325) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): FetchError: request to http://http://openelec.selk8kqa8kbebbks.myfritz.net:8080/jsonrpc failed, reason: getaddrinfo ENOTFOUND http http:80
`

If I try to Pause via the URLs from Troubleshoot, bot URL work for me. So what to do  to get it work?
![ifttt1](https://user-images.githubusercontent.com/27926921/34207538-30fa9d00-e58b-11e7-8555-78ac9657d67d.JPG)

![ifttt2](https://user-images.githubusercontent.com/27926921/34207672-becc08d0-e58b-11e7-892c-a9317343e6f1.JPG)

**Comment by p0psicles** [comment]
What's this: `http://http://openelec.selk8kqa8kbebbks.myfritz.net:8080/jsonrpc`?

**Comment by p0psicles** [comment]
Where have you installed GoogleHomeKodi? On glitch or your home server?

**Comment by Beliar-666** [comment]
Installed on glitch. Using the .env file.

http://openelec.selk8kqa8kbebbks.myfritz.net:8080  is the public URL to my Kodi

The Config from glitch?

**Comment by p0psicles** [comment]
Yeah it's errorring at the http://http://.
Yeah can you give your .env config. Something is wrong there.
Just replace sensitive info.

**Comment by p0psicles** [comment]
Never mind. You entered http://..... in the field for the KODI_IP. You should only enter the dns name. In your case: `openelec.selk8kqa8kbebbks.myfritz.net`

**Comment by Beliar-666** [comment]
Just tested again. ok, again my IP was not reachable. Fixed it again with Portforwarding host. Now new Config:
`# Environment Config
KODI_IP=beliar666.feste-ip.net
KODI_PORT=34099
KODI_USER=****
KODI_PASSWORD=****
AUTH_TOKEN=*****`


Now i get following:
`request failed
route:  
query:  { q: ' Inferno' }
error:  { SyntaxError: Unexpected token L in JSON at position 9
    at Object.parse (native)
    at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)
    at /app/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
    at done (/app/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
  expose: true,
  statusCode: 400,
  status: 400,
  body: '{"token":*****}',
  type: 'entity.parse.failed' }
body:  {}`

**Comment by p0psicles** [comment]
in IFTTT, in the URL field. I'm not sure if that's the cause. But there seems to be a space in: `q= {{TextField}}`.
Can you remove the space?

**Comment by Beliar-666** [comment]
Space is removed, same error. 
May it be that my Kodi has not everything it needs? or maybe wrong version of Node?  Its Kodi running on a raspberry. Based on openelec.

**Comment by p0psicles** [comment]
Wait your kodi is accesable using this url: http://openelec.selk8kqa8kbebbks.myfritz.net:8080?
Then in your .env file you should have:
# Environment Config KODI_IP=openelec.selk8kqa8kbebbks.myfritz.net KODI_PORT=8080 KODI_USER=**** KODI_PASSWORD=**** AUTH_TOKEN=*****

**Comment by Beliar-666** [comment]
This URL is not ever reachable from outside. So i must use the URL beliar666.feste-ip.net. Its an Portforwardhost for sucking IPV6. With beliar666.feste-ip.net:34099  My Kodi is accesable from outside. The other URL should be, but is not. Fucking DS-Lite without IPV4 from my provider.

Just started a Movie via Remotecontrol, then send Kodi Pause via Google Home and this works. But Play still wont work....

**Comment by Beliar-666** [comment]
After Playpause i tested resume, and also works. Only Play seems to make an error...

**Comment by OmerTu** [comment]
Do you get the same error as before?
Perhaps the Portforwardhost you're using doesn't forward the response back ?
Try running this in your browser and post the response you're getting (remove the movie names..)
`http://YOUR_EXTERNAL_IP_OR_DNS_NAME:KODI_EXTERNAL_PORT/jsonrpc?request={"jsonrpc":"2.0","method":"VideoLibrary.GetMovies","id":1}`

**Comment by Beliar-666** [comment]
Hello OmerTu, 
If i do so, i get back a list of my Movies:
`{"id":1,"jsonrpc":"2.0","result":{"limits":{"end":320,"start":0,"total":320},"movies":[{"label":"******","movieid":1}, .......... {"label":"*****","movieid":316},{"label":"*********","movieid":317},{"label":"*******","movieid":318},{"label":"*****","movieid":319},{"label":"*****","movieid":320}]}}`

Shortened the Output, but first and last row are here.  i think this works. 

The Error if i try to use the play Command:
`request failed

route:  

query:  { q: '*******' }

error:  { SyntaxError: Unexpected token L in JSON at position 9

    at Object.parse (native)

    at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)

    at /app/node_modules/body-parser/lib/read.js:121:18
11:27 PM

    at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
11:27 PM

    at done (/app/node_modules/raw-body/index.js:213:7)
11:27 PM

    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)

    at emitNone (events.js:86:13)

    at IncomingMessage.emit (events.js:185:7)

    at endReadableNT (_stream_readable.js:974:12)

    at _combinedTickCallback (internal/process/next_tick.js:80:11)

  expose: true,

  statusCode: 400,

  status: 400,

  body: '{"token":Loli1974}',

  type: 'entity.parse.failed' }

body:  {}`


The Movienames i try i´ve also seen in the List i got via `http://YOUR_EXTERNAL_IP_OR_DNS_NAME:KODI_EXTERNAL_PORT/jsonrpc?request={"jsonrpc":"2.0","method":"VideoLibrary.GetMovies","id":1}

`

**Comment by keydon** [comment]
the problem is json body containing the auth token, you need to wrap your secret in quotes like so:
```
{"token": "Loli1974"}
```

**Comment by Beliar-666** [comment]
That´s it. such a small error. It really was the "" in the Token i forgot.....  Thank U very much!
