### ISSUE TITLE
"There was a problem with Webhooks Service"

### ISSUE THREAD

**Issue by 5p4c3d** [OmerTu/GoogleHomeKodi#97]
Hello,

Thanks for taking the time to make this possible. Unfortunately, I am unable to get it working. 

In Glitch, testing /koditestconnection shows "Test Successful!". In Fact, I see IFTTT test successful pop up in Kodi as well. When executing command "Hey Google, Kodi play movie $" my google mini responds with "Playing movie $" as you would expect. However, nothing plays in Kodi. Upon further inspection, IFTTT notes "There was a problem with the Webhooks service". 

I have a static IP and have forwarded the appropriate ports.

Any help would be much appreciated
-K

**Comment by keydon** [comment]
So the problem seems to be somewhere between IFTT and glitch.

What does the glitch-log say?
Show us how you configured one of your IFTTT-Applets.

**Comment by 5p4c3d** [comment]
Here is glitch log directly after issuing command today

`Authentication succeeded
12:52 PM

Movie request received to play "boss baby"
12:52 PM

Command sent = {"jsonrpc":"2.0","id":1,"method":"VideoLibrary.GetMovies"}`

not sure how to send you IFTTT applet without taking a picture.

Here is a copy paste of link I'm using to connect to my glitch though since I'm sure the problem is in the web host part of the applet

Link: https://swamp-kayak.glitch.me/playmovie?q= {{TextField}}

Method: Post

Content: App/Json

ofc followed by my log in token

**Comment by keydon** [comment]
hmm thats weird, nothing after the line with "Command sent"?

**Comment by 5p4c3d** [comment]
I saw nothing initially. Came back after I saw your comment to double check and then I saw this. Guess I didn't wait long enough.

`request failed
2:26 PM

route:  /playmovie
2:26 PM

query:  { q: ' boss baby' }
2:26 PM

error:  { FetchError: request to http://EDITEDOUT:8080/jsonrpc failed, reason: connect ETIMEDOUT EDITEDOUT:8080
2:26 PM

    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/index.js:133:11)
2:26 PM

    at emitOne (events.js:96:13)
2:26 PM

    at ClientRequest.emit (events.js:188:7)
2:26 PM

    at Socket.socketErrorListener (_http_client.js:309:9)
2:26 PM

    at emitOne (events.js:96:13)
2:26 PM

    at Socket.emit (events.js:188:7)
2:26 PM

    at emitErrorNT (net.js:1277:8)
2:26 PM

    at _combinedTickCallback (internal/process/next_tick.js:80:11)
2:26 PM

    at process._tickCallback (internal/process/next_tick.js:104:9)
2:26 PM

  name: 'FetchError',
2:26 PM

  message: 'request to http://EDITEDOUT:8080/jsonrpc failed, reason: connect ETIMEDOUT 70.122.17.2:8080',
2:26 PM

  type: 'system',
2:26 PM

  errno: 'ETIMEDOUT',
2:26 PM

  code: 'ETIMEDOUT' }
2:26 PM

body:  { token: 'EDITEDOUT' }`

I edited out my IP and Token in case you did not notice ;)

**Comment by keydon** [comment]
hmm even stranger. this log suggests, that everything if fine between glitch and IFTTT.
And the /koditestconnection from glitch to your kodi still works?

**Comment by 5p4c3d** [comment]
Correct, I am still getting "Test Successful" message. 

Do you think its because my computer is hardwired into a wifi extender? All my devices are technically on the same channel (5G-ext). I just figured since I was getting Test successful message it didn't matter.

**Comment by keydon** [comment]
mhh this is a mystery to me.
1. the /koditestconnection command verifies that your kodi can be controlled by the glitch app. This should also be true for every other command.
2. the glitch-log proves that IFTTT can successfully reach the glitch app. but it suggests that it cannot reach your kodi, which contradicts the first point.

could you try the following:
1. go pack to your glitch app where you did the koditestconnection-command.
2. put in your token as before.
3. but instead of the /koditest-command put in the following: ` /playmovie?q=boss%20baby`

**Comment by 5p4c3d** [comment]
Well.....now I feel dumb for assuming this would work with my addons. OFC it says I don't have a single movie. Guess I need to merge my libraries. Thanks for all the help and sorry I wasted your time. I'll be closing this ticket.
