### ISSUE TITLE
Struck at glitch TestConnectionToKodi Button | Not working | Please help

### ISSUE THREAD

**Issue by abhishek-bafna** [OmerTu/GoogleHomeKodi#99]
Hi All, 
I created Glitch project and now when i click on TestConnectionToKodi button, it takes long time and it responds with Gateway timed out. I have got IP Address from Kodi --> System Information and enabled webserver and port forwarding in my router with external ip address as 0.0.0.0 and port 8090 and internal ip appresss as KODI_IP_ADDRESS and port 8090. Am i doing anything wrong because i am struck at basic level. Can someone guide on port forwarding?
Important information: My android TV box is connected via LAN and my google home is on Wifi. could that be a problem? 
Please help.

**Comment by keydon** [comment]
seems to be a duplicate, please close this issue.
